apiVersion: v1
kind: Service
metadata:
  name: vultr-mcp
  labels:
    app: vultr-mcp
spec:
  type: ClusterIP
  selector:
    app: vultr-mcp
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
