apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vultr-mcp-sessions
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: vultr-vfs-storage
  resources:
    requests:
      storage: 10Gi