<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /account endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class AccountTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * Get Account Info.
     * 
     * Get your Vultr account, permission, and billing information.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_account')]
    public function getAccount(): array
    {
        return $this->getClient()->get('/account');
    }

    /**
     * Get Account Bandwidth Info.
     * 
     * Get your Vultr account bandwidth information.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_account_bandwidth')]
    public function getAccountBandwidth(): array
    {
        return $this->getClient()->get('/account/bandwidth');
    }

    /**
     * Get Account BGP Info.
     * 
     * Get your Vultr account BGP information.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_account_bgp')]
    public function getAccountBgp(): array
    {
        return $this->getClient()->get('/account/bgp');
    }

    /**
     * Add new BGP prefixes..
     * 
     * Open a request to add new BGP prefixes.
     * 
     * @param  array  $prefixes  An array of prefixes you intend to announce to us.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_account_bgp_prefixes')]
    public function createAccountBgpPrefixes(
        array $prefixes,
    ): array
    {
        return $this->client->post('/account/bgp/prefixes', [
            'prefixes' => $prefixes,
        ]);
    }

    /**
     * Setup BGP on your Account.
     * 
     * Request BGP setup on your account.
     * 
     * @param  array  $prefixes  An array of prefixes you intend to announce to us. Required, but can be empty if you don't intend to bring your own IP space.
     * @param  int|null  $asn  The BGP ASN your instances will use. If specified, this should be a public ASN you control. If unspecified, Vultr will assign a private range ASN for you to use.
     * @param  string|null  $password  The plaintext password (TCP-MD5) to use on your BGP sessions with Vultr. Optional but recommended.
     * @param  string|null  $letterOfAuthorization  A base64-encoded PDF, PNG, or JPEG file. Required when announcing your own prefixes.
     * @param  string  $requestedRoutes  The routes Vultr should send to you. One of:
 none  Vultr sends no routes
 full  Full BGP table
* default_only  Only default routes
     * @param  string  $usecase  Description of your use case for BGP.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_account_bgp_setup')]
    public function createAccountBgpSetup(
        array $prefixes,
        string $requestedRoutes,
        string $usecase,
        ?int $asn = null,
        ?string $password = null,
        ?string $letterOfAuthorization = null,
    ): array
    {
        return $this->client->post('/account/bgp/setup', [
            'prefixes' => $prefixes,
            'asn' => $asn,
            'password' => $password,
            'letter_of_authorization' => $letterOfAuthorization,
            'requested_routes' => $requestedRoutes,
            'usecase' => $usecase,
        ]);
    }

    /**
     * List Custom Subscriptions.
     * 
     * List all custom subscriptions in your account.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_custom_subscriptions')]
    public function listCustomSubscriptions(): array
    {
        return $this->getClient()->get('/account/custom-subscriptions');
    }

}