<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /apikeys endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class ApiKeysTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List API Keys.
     * 
     * Gets all API keys for the currently authenticated user. API keys returned by this method are masked.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_api_keys')]
    public function listApiKeys(): array
    {
        return $this->getClient()->get('/apikeys');
    }

    /**
     * Create API Key.
     * 
     * Adds an API key to the currently authenticated user's API key list.
     * 
     * @param  string|null  $name  Custom name of the API key.
     * @param  bool|null  $expire  Will the API key expire?
     * @param  string|null  $dateExpire  Date when the API key expires. Only valid when expire is true.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_api_key')]
    public function createApiKey(
        ?string $name = null,
        ?bool $expire = null,
        ?string $dateExpire = null,
    ): array
    {
        return $this->client->post('/apikeys', [
            'name' => $name,
            'expire' => $expire,
            'date_expire' => $dateExpire,
        ]);
    }

    /**
     * Delete API Key.
     * 
     * Delete an API key from the currently authenticated user's API key list.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_api_key')]
    public function deleteApiKey(): array
    {
        $this->getClient()->delete('/apikeys/{apikey-id}');

        return ['success' => true];
    }

    /**
     * Get API Key.
     * 
     * Gets information about an API key for the currently authenticated user. API keys returned by this
     * method are masked.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_api_key')]
    public function getApiKey(): array
    {
        return $this->getClient()->get('/apikeys/{apikey-id}');
    }

}