<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /backups endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class BackupTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Backups.
     * 
     * Get information about Backups in your account.
     * 
     * @param  string|null  $instanceId  Filter the backup list by Instance id.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_backups')]
    public function listBackups(
        ?string $instanceId = null,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/backups', [
            'instance_id' => $instanceId,
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Get a Backup.
     * 
     * Get the information for the Backup.
     * 
     * @param  string  $backupId  The Backup id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_backup')]
    public function getBackup(
        string $backupId,
    ): array
    {
        return $this->getClient()->get('/backups/{backupId');
    }

}