<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /bare-metals endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class BareMetalTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Bare Metal Instances.
     * 
     * List all Bare Metal instances in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_baremetals')]
    public function listBaremetals(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/bare-metals', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Bare Metal Instance.
     * 
     * Create a new Bare Metal instance in a region with the desired plan. Choose one of the following to
     * deploy the instance:
     * 
     *  os_id
     *  snapshot_id
     *  app_id
     *  image_id
     * 
     * Supply other attributes as desired.
     * 
     * @param  string  $region  The Region id to create the instance.
     * @param  string  $plan  The Bare Metal plan id to use for this instance.
     * @param  string|null  $scriptId  The Startup Script id to use for this instance.
     * @param  bool|null  $enableIpv6  Enable IPv6.

* true
     * @param  array|null  $sshkeyId  The SSH Key id to install on this instance.
     * @param  string|null  $userData  The user-supplied, base64 encoded user data for this Instance.
     * @param  string|null  $label  The user-supplied label.
     * @param  bool|null  $activationEmail  Notify by email after deployment.

 true
 false (default)
     * @param  string|null  $hostname  The user-supplied hostname to use when deploying this instance.
     * @param  string|null  $reservedIpv4  The Reserved IP id for this instance.
     * @param  int|null  $osId  If supplied, deploy the instance using this Operating System id.
     * @param  string|null  $snapshotId  If supplied, deploy the instance using this Snapshot ID.
     * @param  int|null  $appId  If supplied, deploy the instance using this Application id.
     * @param  string|null  $imageId  If supplied, deploy the instance using this Application image_id.
     * @param  string|null  $ipxeChainUrl  The URL location of the iPXE chainloader. If used, os_id must be set to 159.
     * @param  bool|null  $persistentPxe  Enable persistent PXE.

 true
 false (default)
     * @param  array|null  $attachVpc  An array of VPC IDs to attach to this Bare Metal Instance. This parameter takes precedence over enable_vpc. Please choose one parameter.
     * @param  bool|null  $enableVpc  If true, VPC support will be added to the new server.

This parameter attaches a single VPC. When no VPC exists in the region, it will be automatically created.

If there are multiple VPCs in the instance's region, use attach_vpc instead to specify a network.
     * @param  array|null  $tags  Tags to apply to the instance.
     * @param  string|null  $userScheme  Linux-only: The user scheme used for logging into this instance. By default, the "root" user is configured. Alternatively, a limited user with sudo permissions can be selected.

 root
 limited
     * @param  string|null  $mdiskMode  The RAID configuration used for the disks on this instance. The instance must be reinstalled for this change to take effect.

 raid1
 jbod
* none (default)
     * @param  array|null  $appVariables  The app variable inputs for configuring the marketplace app (name/value pairs).
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_baremetal')]
    public function createBaremetal(
        string $region,
        string $plan,
        ?string $scriptId = null,
        ?bool $enableIpv6 = null,
        ?array $sshkeyId = null,
        ?string $userData = null,
        ?string $label = null,
        ?bool $activationEmail = null,
        ?string $hostname = null,
        ?string $reservedIpv4 = null,
        ?int $osId = null,
        ?string $snapshotId = null,
        ?int $appId = null,
        ?string $imageId = null,
        ?string $ipxeChainUrl = null,
        ?bool $persistentPxe = null,
        ?array $attachVpc = null,
        ?bool $enableVpc = null,
        ?array $tags = null,
        ?string $userScheme = null,
        ?string $mdiskMode = null,
        ?array $appVariables = null,
    ): array
    {
        return $this->client->post('/bare-metals', [
            'region' => $region,
            'plan' => $plan,
            'script_id' => $scriptId,
            'enable_ipv6' => $enableIpv6,
            'sshkey_id' => $sshkeyId,
            'user_data' => $userData,
            'label' => $label,
            'activation_email' => $activationEmail,
            'hostname' => $hostname,
            'reserved_ipv4' => $reservedIpv4,
            'os_id' => $osId,
            'snapshot_id' => $snapshotId,
            'app_id' => $appId,
            'image_id' => $imageId,
            'ipxe_chain_url' => $ipxeChainUrl,
            'persistent_pxe' => $persistentPxe,
            'attach_vpc' => $attachVpc,
            'enable_vpc' => $enableVpc,
            'tags' => $tags,
            'user_scheme' => $userScheme,
            'mdisk_mode' => $mdiskMode,
            'app_variables' => $appVariables,
        ]);
    }

    /**
     * Halt Bare Metals.
     * 
     * @param  array|null  $baremetalIds
     * @return array<string, mixed>
     */
    #[McpTool(name: 'halt_baremetals')]
    public function haltBaremetals(
        ?array $baremetalIds = null,
    ): array
    {
        return $this->client->post('/bare-metals/halt', [
            'baremetal_ids' => $baremetalIds,
        ]);
    }

    /**
     * Reboot Bare Metals.
     * 
     * @param  array|null  $baremetalIds
     * @return array<string, mixed>
     */
    #[McpTool(name: 'reboot_bare_metals')]
    public function rebootBareMetals(
        ?array $baremetalIds = null,
    ): array
    {
        return $this->client->post('/bare-metals/reboot', [
            'baremetal_ids' => $baremetalIds,
        ]);
    }

    /**
     * Start Bare Metals.
     * 
     * @param  array|null  $baremetalIds
     * @return array<string, mixed>
     */
    #[McpTool(name: 'start_bare_metals')]
    public function startBareMetals(
        ?array $baremetalIds = null,
    ): array
    {
        return $this->client->post('/bare-metals/start', [
            'baremetal_ids' => $baremetalIds,
        ]);
    }

    /**
     * Delete Bare Metal.
     * 
     * Delete a Bare Metal instance.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_baremetal')]
    public function deleteBaremetal(
        string $baremetalId,
    ): array
    {
        $this->getClient()->delete('/bare-metals/{baremetalId');

        return ['success' => true];
    }

    /**
     * Get Bare Metal.
     * 
     * Get information for a Bare Metal instance.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_baremetal')]
    public function getBaremetal(
        string $baremetalId,
    ): array
    {
        return $this->getClient()->get('/bare-metals/{baremetalId');
    }

    /**
     * Update Bare Metal.
     * 
     * Update a Bare Metal instance. All attributes are optional. If not set, the attributes will retain
     * their original values.
     * 
     * Note: Changing os_id, app_id or image_id may take a few extra seconds to complete.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @param  string|null  $userData  The user-supplied, base64 encoded user data to attach to this instance.
     * @param  string|null  $label  The user-supplied label.
     * @param  int|null  $osId  If supplied, reinstall the instance using this Operating System id.
     * @param  int|null  $appId  If supplied, reinstall the instance using this Application id.
     * @param  string|null  $imageId  If supplied, reinstall the instance using this Application image_id.
     * @param  bool|null  $enableIpv6  Enable IPv6.

* true
     * @param  array|null  $tags  Tags to apply to the instance.
     * @param  string|null  $userScheme  Linux-only: The user scheme used for logging into this instance. The instance must be reinstalled for this change to take effect.

 root
 limited
     * @param  string|null  $mdiskMode  The RAID configuration used for the disks on this instance. The instance must be reinstalled for this change to take effect.

 raid1
 jbod
* none (default)
     * @param  string|null  $ipxeChainUrl  The URL location of the iPXE chainloader.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_baremetal')]
    public function updateBaremetal(
        string $baremetalId,
        ?string $userData = null,
        ?string $label = null,
        ?int $osId = null,
        ?int $appId = null,
        ?string $imageId = null,
        ?bool $enableIpv6 = null,
        ?array $tags = null,
        ?string $userScheme = null,
        ?string $mdiskMode = null,
        ?string $ipxeChainUrl = null,
    ): array
    {
        return $this->client->patch('/bare-metals/{baremetalId', [
            'user_data' => $userData,
            'label' => $label,
            'os_id' => $osId,
            'app_id' => $appId,
            'image_id' => $imageId,
            'enable_ipv6' => $enableIpv6,
            'tags' => $tags,
            'user_scheme' => $userScheme,
            'mdisk_mode' => $mdiskMode,
            'ipxe_chain_url' => $ipxeChainUrl,
        ]);
    }

    /**
     * Bare Metal Bandwidth.
     * 
     * Get bandwidth information for the Bare Metal instance.<br><br>The bandwidth object in a successful
     * response contains objects representing a day in the month. The date is denoted by the nested object
     * keys. Days begin and end in the UTC timezone. Bandwidth utilization data contained within the date
     * object is refreshed periodically. We do not recommend using this endpoint to gather real-time
     * metrics.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_bandwidth_baremetal')]
    public function getBandwidthBaremetal(
        string $baremetalId,
    ): array
    {
        return $this->getClient()->get('/bare-metals/{baremetalId/bandwidth');
    }

    /**
     * Halt Bare Metal.
     * 
     * Halt the Bare Metal instance.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'halt_baremetal')]
    public function haltBaremetal(
        string $baremetalId,
    ): array
    {
        return $this->client->post('/bare-metals/{baremetalId/halt');
    }

    /**
     * Bare Metal IPv4 Addresses.
     * 
     * Get the IPv4 information for the Bare Metal instance.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_ipv4_baremetal')]
    public function getIpv4Baremetal(
        string $baremetalId,
    ): array
    {
        return $this->getClient()->get('/bare-metals/{baremetalId/ipv4');
    }

    /**
     * Create Baremetal Reverse IPv4.
     * 
     * Create a reverse IPv4 entry for a Bare Metal Instance. The ip and reverse attributes are required.
     * 
     * @param  string  $baremetalId  The Bare Metal ID.
     * @param  string  $ip  The IPv4 address.
     * @param  string  $reverse  The IPv4 reverse entry.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_baremetal_reverse_ipv4')]
    public function createBaremetalReverseIpv4(
        string $baremetalId,
        string $ip,
        string $reverse,
    ): array
    {
        return $this->client->post('/bare-metals/{baremetalId/ipv4/reverse', [
            'ip' => $ip,
            'reverse' => $reverse,
        ]);
    }

    /**
     * Set Default Reverse DNS Entry.
     * 
     * Set a reverse DNS entry for an IPv4 address
     * 
     * @param  string  $baremetalId  The Bare Metal ID.
     * @param  string  $ip
     * @return array<string, mixed>
     */
    #[McpTool(name: 'post_baremetal_instance_id_ipv4_reverse_default')]
    public function postBaremetalInstanceIdIpv4ReverseDefault(
        string $baremetalId,
        string $ip,
    ): array
    {
        return $this->client->post('/bare-metals/{baremetalId/ipv4/reverse/default', [
            'ip' => $ip,
        ]);
    }

    /**
     * Bare Metal IPv6 Addresses.
     * 
     * Get the IPv6 information for the Bare Metal instance.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_ipv6_baremetal')]
    public function getIpv6Baremetal(
        string $baremetalId,
    ): array
    {
        return $this->getClient()->get('/bare-metals/{baremetalId/ipv6');
    }

    /**
     * Create Baremetal Reverse IPv6.
     * 
     * Create a reverse IPv6 entry for a Bare Metal Instance. The ip and reverse attributes are required.
     * IP address must be in full, expanded format.
     * 
     * @param  string  $baremetalId  The Bare metal ID.
     * @param  string  $ip  The IPv6 address in full, expanded format.
     * @param  string  $reverse  The IPv6 reverse entry.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_baremetal_reverse_ipv6')]
    public function createBaremetalReverseIpv6(
        string $baremetalId,
        string $ip,
        string $reverse,
    ): array
    {
        return $this->client->post('/bare-metals/{baremetalId/ipv6/reverse', [
            'ip' => $ip,
            'reverse' => $reverse,
        ]);
    }

    /**
     * Delete BareMetal Reverse IPv6.
     * 
     * Delete the reverse IPv6 for a Bare metal instance.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @param  string  $ipv6  The IPv6 address.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_baremetal_reverse_ipv6')]
    public function deleteBaremetalReverseIpv6(
        string $baremetalId,
        string $ipv6,
    ): array
    {
        $this->getClient()->delete('/bare-metals/{baremetalId/ipv6/reverse/{ipv6');

        return ['success' => true];
    }

    /**
     * Reboot Bare Metal.
     * 
     * Reboot the Bare Metal instance.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'reboot_baremetal')]
    public function rebootBaremetal(
        string $baremetalId,
    ): array
    {
        return $this->client->post('/bare-metals/{baremetalId/reboot');
    }

    /**
     * Reinstall Bare Metal.
     * 
     * Reinstall the Bare Metal instance using an optional hostname.
     * 
     * Note: This action may take some time to complete.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @param  string|null  $hostname  The hostname to use when reinstalling this bare metal server.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'reinstall_baremetal')]
    public function reinstallBaremetal(
        string $baremetalId,
        ?string $hostname = null,
    ): array
    {
        return $this->client->post('/bare-metals/{baremetalId/reinstall', [
            'hostname' => $hostname,
        ]);
    }

    /**
     * Start Bare Metal.
     * 
     * Start the Bare Metal instance.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'start_baremetal')]
    public function startBaremetal(
        string $baremetalId,
    ): array
    {
        return $this->client->post('/bare-metals/{baremetalId/start');
    }

    /**
     * Get Available Bare Metal Upgrades.
     * 
     * Get available upgrades for a Bare Metal
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @param  string|null  $type  Filter upgrade by type:

- all (applications, plans)
- applications
- os
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_bare_metals_upgrades')]
    public function getBareMetalsUpgrades(
        string $baremetalId,
        ?string $type = null,
    ): array
    {
        return $this->getClient()->get('/bare-metals/{baremetalId/upgrades', [
            'type' => $type,
        ]);
    }

    /**
     * Get Bare Metal User Data.
     * 
     * Get the user-supplied, base64 encoded user data for a Bare Metal.
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_bare_metal_userdata')]
    public function getBareMetalUserdata(
        string $baremetalId,
    ): array
    {
        return $this->getClient()->get('/bare-metals/{baremetalId/user-data');
    }

    /**
     * Get VNC URL for a Bare Metal.
     * 
     * Get the VNC URL for a Bare Metal
     * 
     * @param  string  $baremetalId  The Bare Metal id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_bare_metal_vnc')]
    public function getBareMetalVnc(
        string $baremetalId,
    ): array
    {
        return $this->getClient()->get('/bare-metals/{baremetalId/vnc');
    }

    /**
     * List Bare Metal Instance VPC Networks.
     * 
     * List the VPC networks for a Bare Metal Instance.
     * 
     * @param  string  $baremetalId  The Bare Metal ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_baremetal_vpcs')]
    public function listBaremetalVpcs(
        string $baremetalId,
    ): array
    {
        return $this->getClient()->get('/bare-metals/{baremetalId/vpcs');
    }

    /**
     * Attach VPC Network to Bare Metal Instance.
     * 
     * Attach a VPC Network to a Bare Metal Instance.
     * 
     * @param  string  $baremetalId  The Bare Metal ID.
     * @param  string|null  $vpcId  The VPC ID to attach to this Bare Metal Instance.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'attach_baremetals_vpcs')]
    public function attachBaremetalsVpcs(
        string $baremetalId,
        ?string $vpcId = null,
    ): array
    {
        return $this->client->post('/bare-metals/{baremetalId/vpcs/attach', [
            'vpc_id' => $vpcId,
        ]);
    }

    /**
     * Detach VPC Network from Bare Metal Instance.
     * 
     * Detach a VPC Network from an Bare Metal Instance.
     * 
     * @param  string  $baremetalId  The bare-metal ID.
     * @param  string|null  $vpcId  The VPC ID to detach from this Bare Metal Instance.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'detach_baremetal_vpcs')]
    public function detachBaremetalVpcs(
        string $baremetalId,
        ?string $vpcId = null,
    ): array
    {
        return $this->client->post('/bare-metals/{baremetalId/vpcs/detach', [
            'vpc_id' => $vpcId,
        ]);
    }

}