<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /billing endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class BillingTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Billing History.
     * 
     * Retrieve list of billing history
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_billing_history')]
    public function listBillingHistory(): array
    {
        return $this->getClient()->get('/billing/history');
    }

    /**
     * List Invoices.
     * 
     * Retrieve a list of invoices
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_invoices')]
    public function listInvoices(): array
    {
        return $this->getClient()->get('/billing/invoices');
    }

    /**
     * Get Invoice.
     * 
     * Retrieve specified invoice
     * 
     * @param  string  $invoiceId  ID of invoice
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_invoice')]
    public function getInvoice(
        string $invoiceId,
    ): array
    {
        return $this->getClient()->get('/billing/invoices/{invoiceId');
    }

    /**
     * Get Invoice Items.
     * 
     * Retrieve full specified invoice
     * 
     * @param  string  $invoiceId  ID of invoice
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_invoice_items')]
    public function getInvoiceItems(
        string $invoiceId,
    ): array
    {
        return $this->getClient()->get('/billing/invoices/{invoiceId/items');
    }

    /**
     * List Pending Charges.
     * 
     * Retrieve list of billing pending charges
     * @return array<string, mixed>
     */
    #[McpTool(name: 'pending_charges')]
    public function pendingCharges(): array
    {
        return $this->getClient()->get('/billing/pending-charges');
    }

    /**
     * Get Pending Charges CSV.
     * 
     * Get pending charges as CSV file. Returns all current month charges.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'pending_charges_csv')]
    public function pendingChargesCsv(): array
    {
        return $this->getClient()->get('/billing/pending-charges/csv');
    }

}