<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /blocks endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class BlockStorageTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Block storages.
     * 
     * List all Block Storage in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_blocks')]
    public function listBlocks(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/blocks', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Block Storage.
     * 
     * Create new Block Storage in a region with a size of size_gb. Size may range between 10 and 40000
     * depending on the block_type.
     * 
     * @param  string  $region  The Region id where the Block Storage will be created.
     * @param  int  $sizeGb  Size in GB may range between 10 and 40000, depending on the block_type.
     * @param  string|null  $label  The user-supplied label.
     * @param  string|null  $blockType  An optional parameter, that determines on the type of block storage volume that will be created.
Soon to become a required parameter.

 high_perf from 10GB to 10,000GB
 storage_opt from 40GB to 40,000GB
     * @param  string|null  $snapshotId  An optional paremeter, allows you to create a block device as a clone of an existing block snapshot.
     * @param  bool|null  $bootable  An optional parameter. Allows you to flag a block device as bootable.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_block')]
    public function createBlock(
        string $region,
        int $sizeGb,
        ?string $label = null,
        ?string $blockType = null,
        ?string $snapshotId = null,
        ?bool $bootable = null,
    ): array
    {
        return $this->client->post('/blocks', [
            'region' => $region,
            'size_gb' => $sizeGb,
            'label' => $label,
            'block_type' => $blockType,
            'snapshot_id' => $snapshotId,
            'bootable' => $bootable,
        ]);
    }

    /**
     * List Block storage snapshots.
     * 
     * List all Block Storage Snapshots in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_block_snapshots')]
    public function listBlockSnapshots(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/blocks/snapshots', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Block Storage Snapshot.
     * 
     * Create new Block Snapshot of a Block Storage subscription.
     * 
     * @param  string  $blockId  The Block id of the block subscription you want to snapshot
     * @param  string  $description  The user-supplied description.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_block_snapshot')]
    public function createBlockSnapshot(
        string $blockId,
        string $description,
    ): array
    {
        return $this->client->post('/blocks/snapshots', [
            'block_id' => $blockId,
            'description' => $description,
        ]);
    }

    /**
     * Delete Block Storage Snapshot.
     * 
     * @param  string  $snapshotId  The Block Storage snapshot id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_block_snapshot')]
    public function deleteBlockSnapshot(
        string $snapshotId,
    ): array
    {
        $this->getClient()->delete('/blocks/snapshots/{snapshotId');

        return ['success' => true];
    }

    /**
     * Get Block Storage Snapshots.
     * 
     * Get information for Block Storage Snapshot.
     * 
     * @param  string  $snapshotId  The Block Storage snapshot id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_block_snapshot')]
    public function getBlockSnapshot(
        string $snapshotId,
    ): array
    {
        return $this->getClient()->get('/blocks/snapshots/{snapshotId');
    }

    /**
     * Update Block Storage Snapshot.
     * 
     * Update information for Block Storage Snapshot.
     * 
     * @param  string  $snapshotId  The Block Storage snapshot id.
     * @param  string|null  $description  The user-supplied description.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_block_snapshot')]
    public function updateBlockSnapshot(
        string $snapshotId,
        ?string $description = null,
    ): array
    {
        return $this->client->put('/blocks/snapshots/{snapshotId', [
            'description' => $description,
        ]);
    }

    /**
     * Delete Block Storage.
     * 
     * @param  string  $blockId  The Block Storage id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_block')]
    public function deleteBlock(
        string $blockId,
    ): array
    {
        $this->getClient()->delete('/blocks/{blockId');

        return ['success' => true];
    }

    /**
     * Get Block Storage.
     * 
     * Get information for Block Storage.
     * 
     * @param  string  $blockId  The Block Storage id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_block')]
    public function getBlock(
        string $blockId,
    ): array
    {
        return $this->getClient()->get('/blocks/{blockId');
    }

    /**
     * Update Block Storage.
     * 
     * Update information for Block Storage.
     * 
     * @param  string  $blockId  The Block Storage id.
     * @param  string|null  $label  The user-supplied label.
     * @param  int|null  $sizeGb  New size of the Block Storage in GB. Size may range between 10 and 40000 depending on the block_type.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_block')]
    public function updateBlock(
        string $blockId,
        ?string $label = null,
        ?int $sizeGb = null,
    ): array
    {
        return $this->client->patch('/blocks/{blockId', [
            'label' => $label,
            'size_gb' => $sizeGb,
        ]);
    }

    /**
     * Attach Block Storage.
     * 
     * Attach Block Storage to Instance instance_id.
     * 
     * @param  string  $blockId  The Block Storage id.
     * @param  string  $instanceId  Attach the Block Storage to this Instance id.
     * @param  bool|null  $live  Attach Block Storage without restarting the Instance.

|   | Value | Description |
| - | ----- | ----------- |
|   | true | Attach live, do not restart the instance. |
|   | false | Restart the instance and attach the Block Storage. |
     * @return array<string, mixed>
     */
    #[McpTool(name: 'attach_block')]
    public function attachBlock(
        string $blockId,
        string $instanceId,
        ?bool $live = null,
    ): array
    {
        return $this->client->post('/blocks/{blockId/attach', [
            'instance_id' => $instanceId,
            'live' => $live,
        ]);
    }

    /**
     * Detach Block Storage.
     * 
     * @param  string  $blockId  The Block Storage id.
     * @param  bool|null  $live  Detach Block Storage without restarting the Instance.

|   | Value | Description |
| - | ----- | ----------- |
|   | true | Detach live, do not restart the instance. |
|   | false | Restart the instance and detach the Block Storage. |
     * @return array<string, mixed>
     */
    #[McpTool(name: 'detach_block')]
    public function detachBlock(
        string $blockId,
        ?bool $live = null,
    ): array
    {
        return $this->client->post('/blocks/{blockId/detach', [
            'live' => $live,
        ]);
    }

}