<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /cdns endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class CdnsTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List CDN Pull Zones.
     * 
     * List CDN Pull Zones
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_pullzones')]
    public function listPullzones(): array
    {
        return $this->getClient()->get('/cdns/pull-zones');
    }

    /**
     * Create CDN Pull Zones.
     * 
     * Create a new CDN Pull Zone.
     * 
     * @param  string  $label  The user-supplied label.
     * @param  string  $originScheme  The URI scheme of the origin domain.
     * @param  string  $originDomain  The domain name from which the content stored in the CDN will be pulled.
     * @param  string|null  $vanityDomain  An optional domain name that can be used to access the cached files in adition to the domain that is automaticaly created.  This vanity domain will need to have a CNAME DNS record created to point it at the standard CDN domain that is automaticaly generated on creation of the CDN.
     * @param  string|null  $sslCert  Base 64 encoded file content for an ssl/tls certificate associated with the optional vanity_domain.  This field is required if a vanity domain is provided and the origin_scheme is https.
     * @param  string|null  $sslCertKey  Base 64 encoded file content for the private key associated with the ssl_cert.  This field is required if a vanity domain is provided and the origin_scheme is https.
     * @param  bool|null  $cors  Enable Cross-origin resource sharing.  CORS is a content validation mechanism used by web browsers to validate file access permissions. The Vultr CDN CORS policy protects your static assets from hotlinking threats by only accepting requests associated with your Origin URL.
     * @param  bool|null  $gzip  Enable Gzip compression to reduce the static content size to speed up the delivery process.
     * @param  bool|null  $blockAi  Block AI bots.
     * @param  bool|null  $blockBadBots  Block potentially malicious bots.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_pullzone')]
    public function createPullzone(
        string $label,
        string $originScheme,
        string $originDomain,
        ?string $vanityDomain = null,
        ?string $sslCert = null,
        ?string $sslCertKey = null,
        ?bool $cors = null,
        ?bool $gzip = null,
        ?bool $blockAi = null,
        ?bool $blockBadBots = null,
    ): array
    {
        return $this->client->post('/cdns/pull-zones', [
            'label' => $label,
            'origin_scheme' => $originScheme,
            'origin_domain' => $originDomain,
            'vanity_domain' => $vanityDomain,
            'ssl_cert' => $sslCert,
            'ssl_cert_key' => $sslCertKey,
            'cors' => $cors,
            'gzip' => $gzip,
            'block_ai' => $blockAi,
            'block_bad_bots' => $blockBadBots,
        ]);
    }

    /**
     * Delete CDN Pullzone.
     * 
     * Delete a CDN Pull Zone.
     * 
     * @param  string  $pullzoneId  The Pull Zone ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_pullzone')]
    public function deletePullzone(
        string $pullzoneId,
    ): array
    {
        $this->getClient()->delete('/cdns/pull-zones/{pullzoneId');

        return ['success' => true];
    }

    /**
     * Get CDN Pull Zone.
     * 
     * Get information about a CDN Pull Zones
     * 
     * @param  string  $pullzoneId  The Pull Zone ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_pullzone')]
    public function getPullzone(
        string $pullzoneId,
    ): array
    {
        return $this->getClient()->get('/cdns/pull-zones/{pullzoneId');
    }

    /**
     * Update CDN Pull Zone.
     * 
     * Update information for a CDN Pullzone. All attributes are optional. If not set, the attributes will
     * retain their original values.
     * 
     * @param  string  $pullzoneId  The Pull Zone ID.
     * @param  string|null  $label  The user-supplied label.
     * @param  string|null  $vanityDomain  An optional domain name that can be used to access the cached files in adition to the domain that is automaticaly created.  This vanity domain will need to have a CNAME DNS record created to point it at the standard CDN domain that is automaticaly generated on creation of the CDN.
     * @param  string|null  $sslCert  Base 64 encoded file content for an ssl/tls certificate associated with the optional vanity_domain.  This field is required if a vanity domain is provided and the origin_scheme is https.
     * @param  string|null  $sslCertKey  Base 64 encoded file content for the private key associated with the ssl_cert.  This field is required if a vanity domain is provided and the origin_scheme is https.
     * @param  bool|null  $cors  Cross-origin resource sharing.
     * @param  bool|null  $gzip  Optional feature to compress files, reduce the amount of data that's transferred.
     * @param  bool|null  $blockAi  Optional feature to block AI bots.
     * @param  bool|null  $blockBadBots  Optional feature to block potentially malicious bots.
     * @param  array|null  $regions  a list of Region ids for locations to be used for content delivery.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_pullzone')]
    public function updatePullzone(
        string $pullzoneId,
        ?string $label = null,
        ?string $vanityDomain = null,
        ?string $sslCert = null,
        ?string $sslCertKey = null,
        ?bool $cors = null,
        ?bool $gzip = null,
        ?bool $blockAi = null,
        ?bool $blockBadBots = null,
        ?array $regions = null,
    ): array
    {
        return $this->client->put('/cdns/pull-zones/{pullzoneId', [
            'label' => $label,
            'vanity_domain' => $vanityDomain,
            'ssl_cert' => $sslCert,
            'ssl_cert_key' => $sslCertKey,
            'cors' => $cors,
            'gzip' => $gzip,
            'block_ai' => $blockAi,
            'block_bad_bots' => $blockBadBots,
            'regions' => $regions,
        ]);
    }

    /**
     * Purge CDN Pull Zone.
     * 
     * Clears cached content on server proxies so that visitors can get the latest page versions.
     * 
     * Note: This action may only be performed once every six hours.
     * 
     * Note: This action may take a few extra seconds to complete.
     * 
     * @param  string  $pullzoneId  The Pull Zone ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'purge_pullzone')]
    public function purgePullzone(
        string $pullzoneId,
    ): array
    {
        return $this->getClient()->get('/cdns/pull-zones/{pullzoneId/purge');
    }

    /**
     * List CDN Push Zones.
     * 
     * List CDN Push Zones
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_pushzones')]
    public function listPushzones(): array
    {
        return $this->getClient()->get('/cdns/push-zones');
    }

    /**
     * Create CDN Push Zones.
     * 
     * Create a new CDN Push Zone.
     * 
     * @param  string  $label  The user-supplied label.
     * @param  string|null  $vanityDomain  An optional domain name that can be used to access the cached files in adition to the domain that is automaticaly created.  This vanity domain will need to have a CNAME DNS record created to point it at the standard CDN domain that is automaticaly generated on creation of the CDN.
     * @param  string|null  $sslCert  Base 64 encoded file content for an ssl/tls certificate associated with the optional vanity_domain.  This field is required if a vanity domain is provided.
     * @param  string|null  $sslCertKey  Base 64 encoded file content for the private key associated with the ssl_cert.  This field is required if a vanity domain is provided.
     * @param  bool|null  $cors  Enable Cross-origin resource sharing.  CORS is a content validation mechanism used by web browsers to validate file access permissions. The Vultr CDN CORS policy protects your static assets from hotlinking threats by only accepting requests associated with your Origin URL.
     * @param  bool|null  $gzip  Enable Gzip compression to reduce the static content size to speed up the delivery process.
     * @param  bool|null  $blockAi  Block AI bots.
     * @param  bool|null  $blockBadBots  Block potentially malicious bots.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_pushzone')]
    public function createPushzone(
        string $label,
        ?string $vanityDomain = null,
        ?string $sslCert = null,
        ?string $sslCertKey = null,
        ?bool $cors = null,
        ?bool $gzip = null,
        ?bool $blockAi = null,
        ?bool $blockBadBots = null,
    ): array
    {
        return $this->client->post('/cdns/push-zones', [
            'label' => $label,
            'vanity_domain' => $vanityDomain,
            'ssl_cert' => $sslCert,
            'ssl_cert_key' => $sslCertKey,
            'cors' => $cors,
            'gzip' => $gzip,
            'block_ai' => $blockAi,
            'block_bad_bots' => $blockBadBots,
        ]);
    }

    /**
     * Delete CDN Pushzone.
     * 
     * Delete a CDN Push Zone.
     * 
     * @param  string  $pushzoneId  The Push Zone ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_pushzone')]
    public function deletePushzone(
        string $pushzoneId,
    ): array
    {
        $this->getClient()->delete('/cdns/push-zones/{pushzoneId');

        return ['success' => true];
    }

    /**
     * Get CDN Push Zone.
     * 
     * Get information about a CDN Push Zone
     * 
     * @param  string  $pushzoneId  The Push Zone ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_pushzone')]
    public function getPushzone(
        string $pushzoneId,
    ): array
    {
        return $this->getClient()->get('/cdns/push-zones/{pushzoneId');
    }

    /**
     * Update CDN Push Zone.
     * 
     * Update information for a CDN Pushzone. All attributes are optional. If not set, the attributes will
     * retain their original values.
     * 
     * @param  string  $pushzoneId  The Push Zone ID.
     * @param  string|null  $label  The user-supplied label.
     * @param  string|null  $vanityDomain  An optional domain name that can be used to access the cached files in adition to the domain that is automaticaly created.  This vanity domain will need to have a CNAME DNS record created to point it at the standard CDN domain that is automaticaly generated on creation of the CDN.
     * @param  string|null  $sslCert  Base 64 encoded file content for an ssl/tls certificate associated with the optional vanity_domain.  This field is required if a vanity domain is provided.
     * @param  string|null  $sslCertKey  Base 64 encoded file content for the private key associated with the ssl_cert.  This field is required if a vanity domain is provided.
     * @param  bool|null  $cors  Cross-origin resource sharing.
     * @param  bool|null  $gzip  Optional feature to compress files, reduce the amount of data that's transferred.
     * @param  bool|null  $blockAi  Optional feature to block AI bots.
     * @param  bool|null  $blockBadBots  Optional feature to block potentially malicious bots.
     * @param  array|null  $regions  a list of Region ids for locations to be used for content delivery.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_pushzone')]
    public function updatePushzone(
        string $pushzoneId,
        ?string $label = null,
        ?string $vanityDomain = null,
        ?string $sslCert = null,
        ?string $sslCertKey = null,
        ?bool $cors = null,
        ?bool $gzip = null,
        ?bool $blockAi = null,
        ?bool $blockBadBots = null,
        ?array $regions = null,
    ): array
    {
        return $this->client->put('/cdns/push-zones/{pushzoneId', [
            'label' => $label,
            'vanity_domain' => $vanityDomain,
            'ssl_cert' => $sslCert,
            'ssl_cert_key' => $sslCertKey,
            'cors' => $cors,
            'gzip' => $gzip,
            'block_ai' => $blockAi,
            'block_bad_bots' => $blockBadBots,
            'regions' => $regions,
        ]);
    }

    /**
     * List CDN Push Zone Files.
     * 
     * Get a list of files that have been uploaded to a specific CDN Push Zones
     * 
     * @param  string  $pushzoneId  The Push Zone ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_pushzone_files')]
    public function getPushzoneFiles(
        string $pushzoneId,
    ): array
    {
        return $this->getClient()->get('/cdns/push-zones/{pushzoneId/files');
    }

    /**
     * Create CDN Push Zone File Upload Endpoint.
     * 
     * Create a presigned post endpoint that can be used to upload a file to your Push Zone.  After sending
     * this request you must send a second POST request to the returned URL. Include all of the returned
     * inputs as form-data fields using the same key and value.  You must also include a field named "file"
     * that holds the file to be uploaded.
     * 
     * @param  string  $pushzoneId  The Push Zone ID.
     * @param  string  $name  the name of the file to be uploaded including the file extension. If the uploaded file does not match this name the upload will fail.
     * @param  int  $size  the size of the file to be uploaded.  If the uploaded file does not match this size the upload will fail.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_pushzone_upload')]
    public function createPushzoneUpload(
        string $pushzoneId,
        string $name,
        int $size,
    ): array
    {
        return $this->client->post('/cdns/push-zones/{pushzoneId/files', [
            'name' => $name,
            'size' => $size,
        ]);
    }

    /**
     * Delete CDN Pushzone File.
     * 
     * Delete a CDN Push Zone file.
     * 
     * @param  string  $pushzoneId  The Push Zone ID.
     * @param  string  $fileName  The File Name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_pushzone_file')]
    public function deletePushzoneFile(
        string $pushzoneId,
        string $fileName,
    ): array
    {
        $this->getClient()->delete('/cdns/push-zones/{pushzoneId/files/{fileName');

        return ['success' => true];
    }

    /**
     * Get CDN Push Zone File.
     * 
     * Get information about a CDN Push Zone file
     * 
     * @param  string  $pushzoneId  The Push Zone ID.
     * @param  string  $fileName  The File Name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_pushzone_filename')]
    public function getPushzoneFilename(
        string $pushzoneId,
        string $fileName,
    ): array
    {
        return $this->getClient()->get('/cdns/push-zones/{pushzoneId/files/{fileName');
    }

}