<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /clusters endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class ClustersTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Clusters.
     * 
     * List all clusters in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_clusters')]
    public function listClusters(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/clusters', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Cluster.
     * 
     * Create a new cluster in a region. Provide exactly one of plan or instance_template.
     * 
     * When use_vfs is true, vfs_label and vfs_storage_size are required.
     * 
     * When use_head_node is true, provide exactly one of head_node_plan or head_node_template.
     * head_node_plan also requires one of os_id, app_id, or image_id.
     * 
     * @param  string  $region  The Region id where the cluster will be deployed.
     * @param  string|null  $plan  The Plan id for cluster instances. Provide plan OR instance_template (mutually exclusive).
     * @param  string|null  $instanceTemplate  The Instance Template id. Provide instance_template OR plan (mutually exclusive).
     * @param  string|null  $label  A user-supplied label for this cluster.
     * @param  int|null  $minPoolCount  Minimum number of instances in the cluster's pool.
     * @param  int|null  $desiredPoolCount  Desired number of instances in the cluster's pool.
     * @param  string|null  $hostname  Hostname to apply to cluster instances.
     * @param  int|null  $pkey  Private network key.
     * @param  int|null  $vlanid  VLAN ID for the cluster's private network.
     * @param  bool|null  $notifyActivate  Notify by email when the cluster is activated.
     * @param  int|null  $osId  The Operating System id to install on cluster instances.
     * @param  int|null  $appId  The Application id to install on cluster instances.
     * @param  int|null  $imageId  The Application image_id to install on cluster instances.
     * @param  bool|null  $gpuFabric  If true, the cluster is created as a GPU fabric cluster.
     * @param  array|null  $vfsIds  Array of existing VFS subscription ids to attach to the cluster's instance template.
     * @param  bool|null  $useVfs  Enable VFS for the cluster. When true, vfs_label and vfs_storage_size are required.
     * @param  string|null  $vfsLabel  Label for the VFS subscription. Required when use_vfs is true.
     * @param  string|null  $vfsStorageSize
     * @param  bool|null  $useHeadNode  Enable a head node for the cluster. When true, provide exactly one of head_node_plan or head_node_template.
     * @param  string|null  $headNodePlan  Plan for the head node. Mutually exclusive with head_node_template. Also requires one of os_id, app_id, or image_id.
     * @param  string|null  $headNodeTemplate  Instance template id for the head node. Mutually exclusive with head_node_plan.
     * @param  array|null  $vpcIds  Array of VPC ids to attach to the cluster.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_cluster')]
    public function createCluster(
        string $region,
        ?string $plan = null,
        ?string $instanceTemplate = null,
        ?string $label = null,
        ?int $minPoolCount = null,
        ?int $desiredPoolCount = null,
        ?string $hostname = null,
        ?int $pkey = null,
        ?int $vlanid = null,
        ?bool $notifyActivate = null,
        ?int $osId = null,
        ?int $appId = null,
        ?int $imageId = null,
        ?bool $gpuFabric = null,
        ?array $vfsIds = null,
        ?bool $useVfs = null,
        ?string $vfsLabel = null,
        ?string $vfsStorageSize = null,
        ?bool $useHeadNode = null,
        ?string $headNodePlan = null,
        ?string $headNodeTemplate = null,
        ?array $vpcIds = null,
    ): array
    {
        return $this->client->post('/clusters', [
            'region' => $region,
            'plan' => $plan,
            'instance_template' => $instanceTemplate,
            'label' => $label,
            'min_pool_count' => $minPoolCount,
            'desired_pool_count' => $desiredPoolCount,
            'hostname' => $hostname,
            'pkey' => $pkey,
            'vlanid' => $vlanid,
            'notify_activate' => $notifyActivate,
            'os_id' => $osId,
            'app_id' => $appId,
            'image_id' => $imageId,
            'gpu_fabric' => $gpuFabric,
            'vfs_ids' => $vfsIds,
            'use_vfs' => $useVfs,
            'vfs_label' => $vfsLabel,
            'vfs_storage_size' => $vfsStorageSize,
            'use_head_node' => $useHeadNode,
            'head_node_plan' => $headNodePlan,
            'head_node_template' => $headNodeTemplate,
            'vpc_ids' => $vpcIds,
        ]);
    }

    /**
     * Get Cluster Availability.
     * 
     * Returns available cluster types for a region. The request body is required on this GET endpoint.
     * 
     * Note: This endpoint accepts a JSON body on a GET request. Some HTTP clients and proxies may strip
     * the body from GET requests.
     * 
     * @param  string  $region  The Region id to check cluster availability in.
     * @param  string|null  $type  Optional filter for cluster type.

 vps
 bare-metal
* gpu-fabric
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_cluster_availability')]
    public function getClusterAvailability(
        string $region,
        ?string $type = null,
    ): array
    {
        return $this->getClient()->get('/clusters/availability');
    }

    /**
     * Delete Cluster.
     * 
     * Delete a cluster.
     * 
     * @param  string  $clusterId  The Cluster ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_cluster')]
    public function deleteCluster(
        string $clusterId,
    ): array
    {
        $this->getClient()->delete('/clusters/{clusterId');

        return ['success' => true];
    }

    /**
     * Get Cluster.
     * 
     * Get information about a cluster.
     * 
     * @param  string  $clusterId  The Cluster ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_cluster')]
    public function getCluster(
        string $clusterId,
    ): array
    {
        return $this->getClient()->get('/clusters/{clusterId');
    }

    /**
     * Mass Update Cluster Instances.
     * 
     * Attach or Detach multiple instances on a cluster in a single request.
     * 
     * @param  string  $clusterId  The Cluster ID.
     * @param  string  $action  The action to perform.

 attach
 detach
     * @param  array  $instances  Array of Instance ids to attach or detach.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'mass_update_cluster_instances')]
    public function massUpdateClusterInstances(
        string $clusterId,
        string $action,
        array $instances,
    ): array
    {
        return $this->client->post('/clusters/{clusterId', [
            'action' => $action,
            'instances' => $instances,
        ]);
    }

    /**
     * Update Cluster.
     * 
     * Update properties of a cluster. All parameters are optional.
     * 
     * @param  string  $clusterId  The Cluster ID.
     * @param  string|null  $label  A user-supplied label for this cluster.
     * @param  int|null  $minPoolCount  Minimum number of instances in the cluster's pool.
     * @param  string|null  $hostname  Hostname for cluster instances.
     * @param  int|null  $desiredPoolCount  Desired number of instances in the cluster's pool.
     * @param  array|null  $vpcIds  Array of VPC ids to attach to the cluster.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_cluster')]
    public function updateCluster(
        string $clusterId,
        ?string $label = null,
        ?int $minPoolCount = null,
        ?string $hostname = null,
        ?int $desiredPoolCount = null,
        ?array $vpcIds = null,
    ): array
    {
        return $this->client->put('/clusters/{clusterId', [
            'label' => $label,
            'min_pool_count' => $minPoolCount,
            'hostname' => $hostname,
            'desired_pool_count' => $desiredPoolCount,
            'vpc_ids' => $vpcIds,
        ]);
    }

    /**
     * Get Cluster Metrics.
     * 
     * Retrieve GPU and fabric metrics for all instances in a cluster.
     * 
     * @param  string  $clusterId  The Cluster ID.
     * @param  string|null  $period  Time period for metrics. Defaults to -1days.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_cluster_metrics')]
    public function getClusterMetrics(
        string $clusterId,
        ?string $period = null,
    ): array
    {
        return $this->getClient()->get('/clusters/{clusterId/metrics', [
            'period' => $period,
        ]);
    }

    /**
     * Update Cluster Instance.
     * 
     * Attach or Detach a single instance on a cluster.
     * 
     * @param  string  $clusterId  The Cluster ID.
     * @param  string  $action  The action to perform.

 attach
 detach
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_cluster_instance')]
    public function updateClusterInstance(
        string $clusterId,
        string $action,
        string $instanceId,
    ): array
    {
        return $this->client->post('/clusters/{clusterId/{action/{instanceId');
    }

}