<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /registry endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class ContainerRegistryTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * Create Container Registry.
     * 
     * Create a new Container Registry Subscription
     * 
     * @param  string  $name
     * @param  string  $public
     * @param  string  $region  The name of the region you'd like to deploy this Registry in. Can get list of regions from /registry/region/list endpoint i.e. sjc
     * @param  string  $plan  The key of the plan you'd like to select which dictates how much storage you're allocated and the monthly cost. Can get list of plans from /plan/list endpoint i.e. start_up
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_registry')]
    public function createRegistry(
        string $name,
        string $public,
        string $region,
        string $plan,
    ): array
    {
        return $this->client->post('/registry', [
            'name' => $name,
            'public' => $public,
            'region' => $region,
            'plan' => $plan,
        ]);
    }

    /**
     * List Registry Plans.
     * 
     * List All Plans to help choose which one is the best fit for your Container Registry
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_registry_plans')]
    public function listRegistryPlans(): array
    {
        return $this->getClient()->get('/registry/plan/list');
    }

    /**
     * List Registry Regions.
     * 
     * List All Regions where a Container Registry can be deployed
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_registry_regions')]
    public function listRegistryRegions(): array
    {
        return $this->getClient()->get('/registry/region/list');
    }

    /**
     * Delete Container Registry.
     * 
     * Deletes a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_registry')]
    public function deleteRegistry(): array
    {
        $this->getClient()->delete('/registry/{registry-id}');

        return ['success' => true];
    }

    /**
     * Read Container Registry.
     * 
     * Get a single Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'read_registry')]
    public function readRegistry(): array
    {
        return $this->getClient()->get('/registry/{registry-id}');
    }

    /**
     * Update Container Registry.
     * 
     * Update a Container Registry Subscription
     * 
     * @param  string|null  $public
     * @param  string|null  $plan  The key of the plan you'd like to upgrade to which dictates how much storage you're allocated and the monthly cost. Can get list of plans from /plan/list endpoint i.e. business
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_registry')]
    public function updateRegistry(
        ?string $public = null,
        ?string $plan = null,
    ): array
    {
        return $this->client->put('/registry/{registry-id}', [
            'public' => $public,
            'plan' => $plan,
        ]);
    }

    /**
     * Create Replication Policy.
     * 
     * Create a new Replication Policy for a Container Registry Subscription
     * 
     * @param  string  $region  The name of the region you'd like to replicate this Container Registry in. Get a list of regions from /registry/region/list endpoint, i.e. sjc
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_replication')]
    public function createReplication(
        string $region,
    ): array
    {
        return $this->client->post('/registry/{registry-id}/replication', [
            'region' => $region,
        ]);
    }

    /**
     * Delete Replication Policy.
     * 
     * Deletes a Replication Policy from a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_replication')]
    public function deleteReplication(): array
    {
        $this->getClient()->delete('/registry/{registry-id}/replication/{region}');

        return ['success' => true];
    }

    /**
     * Read Replication Policy.
     * 
     * Get a single Replication Policy in a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'read_replication')]
    public function readReplication(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/replication/{region}');
    }

    /**
     * List Replication Policies.
     * 
     * List All Replication Policies in a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_replications')]
    public function listReplications(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/replications');
    }

    /**
     * List Repositories.
     * 
     * List All Repositories in a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_registry_repositories')]
    public function listRegistryRepositories(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/repositories');
    }

    /**
     * Delete Repository.
     * 
     * Deletes a Repository from a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_repository')]
    public function deleteRepository(): array
    {
        $this->getClient()->delete('/registry/{registry-id}/repository/{repository-image}');

        return ['success' => true];
    }

    /**
     * Read Repository.
     * 
     * Get a single Repository in a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'read_registry_repository')]
    public function readRegistryRepository(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/repository/{repository-image}');
    }

    /**
     * Update Repository.
     * 
     * Update a Repository in a Container Registry Subscription
     * 
     * @param  string|null  $description
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_repository')]
    public function updateRepository(
        ?string $description = null,
    ): array
    {
        return $this->client->put('/registry/{registry-id}/repository/{repository-image}', [
            'description' => $description,
        ]);
    }

    /**
     * Delete Artifact.
     * 
     * Deletes an Artifact from a Container Registry Repository
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_registry_registry_id_repository_repository_image_artifact_artifact_digest')]
    public function deleteRegistryRegistryIdRepositoryRepositoryImageArtifactArtifactDigest(): array
    {
        $this->getClient()->delete('/registry/{registry-id}/repository/{repository-image}/artifact/{artifact-digest}');

        return ['success' => true];
    }

    /**
     * Read Artifact.
     * 
     * Get a single Artifact in a Container Registry Repository
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_registry_registry_id_repository_repository_image_artifact_artifact_digest')]
    public function getRegistryRegistryIdRepositoryRepositoryImageArtifactArtifactDigest(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/repository/{repository-image}/artifact/{artifact-digest}');
    }

    /**
     * List Artifacts.
     * 
     * List All Artifacts in a Container Registry Repository
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_registry_repository_artifacts')]
    public function listRegistryRepositoryArtifacts(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/repository/{repository-image}/artifacts');
    }

    /**
     * Trigger Retention Policy Execution.
     * 
     * Manually initiate the execution of a Retention Policy in a Container Registry Subscription
     * 
     * @param  bool  $dryRun  If true, simulates the retention policy execution without deleting any artifacts
     * @return array<string, mixed>
     */
    #[McpTool(name: 'execute_retention_policy')]
    public function executeRetentionPolicy(
        bool $dryRun,
    ): array
    {
        return $this->client->post('/registry/{registry-id}/retention/executions', [
            'dry_run' => $dryRun,
        ]);
    }

    /**
     * List Retention Rules.
     * 
     * List all Retention Rules for a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_retention_rules')]
    public function listRetentionRules(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/retention/rules');
    }

    /**
     * Create Retention Rule.
     * 
     * Create a new Retention Rule for a Container Regsitry Subscription
     * 
     * @param  string  $ruleType  The type of retention rule logic to apply.

Possible values:

 'artifacts pushed'
 'artifacts pulled'
 'days pushed'
 'days pulled'
* 'always retain'
     * @param  int|null  $count  The numeric parameter for the rule, for example, if rule_type is "artifacts pushed", this defines how many artifacts to retain
     * @param  string  $repositoryAction  Specifies whether to match or exclude repositories.
- 'matches': include repositories matching the pattern
- 'excludes': exclude repositories matching the pattern
     * @param  string  $repositoryMatch  The glob-style pattern to match repository names, supports wildcards like ` and `.
     * @param  string  $tagAction  Specifies whether to match or exclude tags.
- 'matches': include tags matching the pattern
- 'excludes': exclude tags matching the pattern
     * @param  string  $tagMatch  Glob-style pattern to match tag names.
Common patterns include:
  - `: match all
  - release-`: match tags starting with 'release-'
     * @param  bool  $untagged  Whether to include untagged artifacts when applying the rule
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_retention_rule')]
    public function createRetentionRule(
        string $ruleType,
        string $repositoryAction,
        string $repositoryMatch,
        string $tagAction,
        string $tagMatch,
        bool $untagged,
        ?int $count = null,
    ): array
    {
        return $this->client->post('/registry/{registry-id}/retention/rules', [
            'rule_type' => $ruleType,
            'count' => $count,
            'repository_action' => $repositoryAction,
            'repository_match' => $repositoryMatch,
            'tag_action' => $tagAction,
            'tag_match' => $tagMatch,
            'untagged' => $untagged,
        ]);
    }

    /**
     * Delete Retention Rule.
     * 
     * Deletes a Retention Rule from a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_retention_rule')]
    public function deleteRetentionRule(): array
    {
        $this->getClient()->delete('/registry/{registry-id}/retention/rules/{retention-rule-id}');

        return ['success' => true];
    }

    /**
     * Read Retention Rule.
     * 
     * Get a single Retention Rule in a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'read_retention_rule')]
    public function readRetentionRule(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/retention/rules/{retention-rule-id}');
    }

    /**
     * Update Retention Rule.
     * 
     * Update a Retention Rule in a Container Registry Subscription
     * 
     * @param  string  $disabled
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_retention_rule')]
    public function updateRetentionRule(
        string $disabled,
    ): array
    {
        return $this->client->put('/registry/{registry-id}/retention/rules/{retention-rule-id}', [
            'disabled' => $disabled,
        ]);
    }

    /**
     * Update Retention Policy Schedule.
     * 
     * Update when a Retention Policy is scheduled to run in a Container Registry Subscription
     * 
     * @param  string  $cron  The schedule in which the Retention Policy is triggered

Possible values:

 'hourly'
 'daily'
 'weekly'
 'monthly'
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_retention_schedule')]
    public function updateRetentionSchedule(
        string $cron,
    ): array
    {
        return $this->client->put('/registry/{registry-id}/retention/schedule', [
            'cron' => $cron,
        ]);
    }

    /**
     * Delete Robot.
     * 
     * Deletes a Robot from a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_robot')]
    public function deleteRobot(): array
    {
        $this->getClient()->delete('/registry/{registry-id}/robot/{robot-name}');

        return ['success' => true];
    }

    /**
     * Read Robot.
     * 
     * Get a single Robot in a Container Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_registry_registry_id_robot_robot_name')]
    public function getRegistryRegistryIdRobotRobotName(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/robot/{robot-name}');
    }

    /**
     * Update Robot.
     * 
     * Update the description, disable, duration, and add or remove access, in a Container Registry
     * Subscription Robot
     * 
     * @param  string|null  $description
     * @param  string|null  $disable
     * @param  string|null  $duration
     * @param  string|null  $access
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_robot')]
    public function updateRobot(
        ?string $description = null,
        ?string $disable = null,
        ?string $duration = null,
        ?string $access = null,
    ): array
    {
        return $this->client->put('/registry/{registry-id}/robot/{robot-name}', [
            'description' => $description,
            'disable' => $disable,
            'duration' => $duration,
            'access' => $access,
        ]);
    }

    /**
     * List Robots.
     * 
     * List All Robots in a Conainer Registry Subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_registry_robots')]
    public function listRegistryRobots(): array
    {
        return $this->getClient()->get('/registry/{registry-id}/robots');
    }

    /**
     * Update Container Registry Password.
     * 
     * Update the Container Registy Password for this Container Registry Subscription
     * 
     * @param  string|null  $oldPassword  The API Key provided on Container Registry Subscription creation if the password has not been updated yet
     * @param  string|null  $newPassword  The new user provided password
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_container_registry_password')]
    public function updateContainerRegistryPassword(
        ?string $oldPassword = null,
        ?string $newPassword = null,
    ): array
    {
        return $this->client->put('/registry/{registry-id}/user/password', [
            'old_password' => $oldPassword,
            'new_password' => $newPassword,
        ]);
    }

}