<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /domains endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class DnsTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List DNS Domains.
     * 
     * List all DNS Domains in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_dns_domains')]
    public function listDnsDomains(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/domains', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create DNS Domain.
     * 
     * Create a DNS Domain for domain. If no ip address is supplied a domain with no records will be
     * created.
     * 
     * @param  string  $domain  Your registered DNS Domain name.
     * @param  string|null  $ip  The default IP address for your DNS Domain. If omitted an empty domain zone will be created.
     * @param  string|null  $dnsSec  Enable or disable DNSSEC.

 enabled
 disabled (default)
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_dns_domain')]
    public function createDnsDomain(
        string $domain,
        ?string $ip = null,
        ?string $dnsSec = null,
    ): array
    {
        return $this->client->post('/domains', [
            'domain' => $domain,
            'ip' => $ip,
            'dns_sec' => $dnsSec,
        ]);
    }

    /**
     * Delete Domain.
     * 
     * Delete the DNS Domain.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_dns_domain')]
    public function deleteDnsDomain(
        string $dnsDomain,
    ): array
    {
        $this->getClient()->delete('/domains/{dnsDomain');

        return ['success' => true];
    }

    /**
     * Get DNS Domain.
     * 
     * Get information for the DNS Domain.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_dns_domain')]
    public function getDnsDomain(
        string $dnsDomain,
    ): array
    {
        return $this->getClient()->get('/domains/{dnsDomain');
    }

    /**
     * Update a DNS Domain.
     * 
     * Update the DNS Domain.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @param  string  $dnsSec  Enable or disable DNSSEC.

 enabled
 disabled
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_dns_domain')]
    public function updateDnsDomain(
        string $dnsDomain,
        string $dnsSec,
    ): array
    {
        return $this->client->put('/domains/{dnsDomain', [
            'dns_sec' => $dnsSec,
        ]);
    }

    /**
     * Get DNSSec Info.
     * 
     * Get the DNSSEC information for the DNS Domain.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_dns_domain_dnssec')]
    public function getDnsDomainDnssec(
        string $dnsDomain,
    ): array
    {
        return $this->getClient()->get('/domains/{dnsDomain/dnssec');
    }

    /**
     * List Records.
     * 
     * Get the DNS records for the Domain.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_dns_domain_records')]
    public function listDnsDomainRecords(
        string $dnsDomain,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/domains/{dnsDomain/records', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Record.
     * 
     * Create a DNS record.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @param  string  $name  The hostname for this DNS record.
     * @param  string  $type  The DNS record type.

 A
 AAAA
 CNAME
 NS
 MX
 SRV
 TXT
 CAA
* SSHFP
     * @param  string  $data  The DNS data for this record type.
     * @param  int|null  $ttl  Time to Live in seconds.
     * @param  int|null  $priority  DNS priority. Does not apply to all record types. (Only required for MX and SRV)
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_dns_domain_record')]
    public function createDnsDomainRecord(
        string $dnsDomain,
        string $name,
        string $type,
        string $data,
        ?int $ttl = null,
        ?int $priority = null,
    ): array
    {
        return $this->client->post('/domains/{dnsDomain/records', [
            'name' => $name,
            'type' => $type,
            'data' => $data,
            'ttl' => $ttl,
            'priority' => $priority,
        ]);
    }

    /**
     * Delete Record.
     * 
     * Delete the DNS record.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @param  string  $recordId  The DNS Record id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_dns_domain_record')]
    public function deleteDnsDomainRecord(
        string $dnsDomain,
        string $recordId,
    ): array
    {
        $this->getClient()->delete('/domains/{dnsDomain/records/{recordId');

        return ['success' => true];
    }

    /**
     * Get Record.
     * 
     * Get information for a DNS Record.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @param  string  $recordId  The DNS Record id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_dns_domain_record')]
    public function getDnsDomainRecord(
        string $dnsDomain,
        string $recordId,
    ): array
    {
        return $this->getClient()->get('/domains/{dnsDomain/records/{recordId');
    }

    /**
     * Update Record.
     * 
     * Update the information for a DNS record. All attributes are optional. If not set, the attributes
     * will retain their original values.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @param  string  $recordId  The DNS Record id.
     * @param  string|null  $name  The hostname for this DNS record.
     * @param  string|null  $data  The DNS data for this record type.
     * @param  int|null  $ttl  Time to Live in seconds.
     * @param  int|null  $priority  DNS priority. Does not apply to all record types.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_dns_domain_record')]
    public function updateDnsDomainRecord(
        string $dnsDomain,
        string $recordId,
        ?string $name = null,
        ?string $data = null,
        ?int $ttl = null,
        ?int $priority = null,
    ): array
    {
        return $this->client->patch('/domains/{dnsDomain/records/{recordId', [
            'name' => $name,
            'data' => $data,
            'ttl' => $ttl,
            'priority' => $priority,
        ]);
    }

    /**
     * Get SOA information.
     * 
     * Get SOA information for the DNS Domain.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_dns_domain_soa')]
    public function getDnsDomainSoa(
        string $dnsDomain,
    ): array
    {
        return $this->getClient()->get('/domains/{dnsDomain/soa');
    }

    /**
     * Update SOA information.
     * 
     * Update the SOA information for the DNS Domain. All attributes are optional. If not set, the
     * attributes will retain their original values.
     * 
     * @param  string  $dnsDomain  The DNS Domain.
     * @param  string|null  $nsprimary  Set the primary nameserver.
     * @param  string|null  $email  Set the contact email address.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_dns_domain_soa')]
    public function updateDnsDomainSoa(
        string $dnsDomain,
        ?string $nsprimary = null,
        ?string $email = null,
    ): array
    {
        return $this->client->patch('/domains/{dnsDomain/soa', [
            'nsprimary' => $nsprimary,
            'email' => $email,
        ]);
    }

}