<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /firewalls endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class FirewallTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Firewall Groups.
     * 
     * Get a list of all Firewall Groups.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_firewall_groups')]
    public function listFirewallGroups(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/firewalls', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Firewall Group.
     * 
     * Create a new Firewall Group.
     * 
     * @param  string|null  $description  User-supplied description of this Firewall Group.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_firewall_group')]
    public function createFirewallGroup(
        ?string $description = null,
    ): array
    {
        return $this->client->post('/firewalls', [
            'description' => $description,
        ]);
    }

    /**
     * Delete Firewall Group.
     * 
     * Delete a Firewall Group.
     * 
     * @param  string  $firewallGroupId  The Firewall Group id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_firewall_group')]
    public function deleteFirewallGroup(
        string $firewallGroupId,
    ): array
    {
        $this->getClient()->delete('/firewalls/{firewallGroupId');

        return ['success' => true];
    }

    /**
     * Get Firewall Group.
     * 
     * Get information for a Firewall Group.
     * 
     * @param  string  $firewallGroupId  The Firewall Group id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_firewall_group')]
    public function getFirewallGroup(
        string $firewallGroupId,
    ): array
    {
        return $this->getClient()->get('/firewalls/{firewallGroupId');
    }

    /**
     * Update Firewall Group.
     * 
     * Update information for a Firewall Group.
     * 
     * @param  string  $firewallGroupId  The Firewall Group id.
     * @param  string  $description  User-supplied description of this Firewall Group.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_firewall_group')]
    public function updateFirewallGroup(
        string $firewallGroupId,
        string $description,
    ): array
    {
        return $this->client->put('/firewalls/{firewallGroupId', [
            'description' => $description,
        ]);
    }

    /**
     * List Firewall Rules.
     * 
     * Get the Firewall Rules for a Firewall Group.
     * 
     * @param  string  $firewallGroupId  The Firewall Group id.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_firewall_group_rules')]
    public function listFirewallGroupRules(
        string $firewallGroupId,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/firewalls/{firewallGroupId/rules', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Firewall Rules.
     * 
     * Create a Firewall Rule for a Firewall Group. The attributes ip_type, protocol, subnet, and
     * subnet_size are required.
     * 
     * @param  string  $firewallGroupId  The Firewall Group id.
     * @param  string  $ipType  The type of IP rule.

 v4
 v6
     * @param  string  $protocol  The protocol for this rule.

 ICMP
 TCP
 UDP
 GRE
 ESP
 AH
     * @param  string  $subnet  IP address representing a subnet. The IP address format must match with the "ip_type" parameter value.
     * @param  int  $subnetSize  The number of bits for the netmask in CIDR notation. Example: 32
     * @param  string|null  $port  TCP/UDP only. This field can be a specific port or a colon separated port range.
     * @param  string|null  $source  If the source string is given a value of "cloudflare" subnet and subnet_size will both be ignored.
Possible values:

|   | Value | Description |
| - | ------ | ------------- |
|   | "" | Use the value from subnet and subnet_size. |
|   | cloudflare | Allow all of Cloudflare's IP space through the firewall |
|   | Load Balancer id | Provide a load balancer ID to use its IPs |
     * @param  string|null  $notes  User-supplied notes for this rule.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'post_firewalls_firewall_group_id_rules')]
    public function postFirewallsFirewallGroupIdRules(
        string $firewallGroupId,
        string $ipType,
        string $protocol,
        string $subnet,
        int $subnetSize,
        ?string $port = null,
        ?string $source = null,
        ?string $notes = null,
    ): array
    {
        return $this->client->post('/firewalls/{firewallGroupId/rules', [
            'ip_type' => $ipType,
            'protocol' => $protocol,
            'subnet' => $subnet,
            'subnet_size' => $subnetSize,
            'port' => $port,
            'source' => $source,
            'notes' => $notes,
        ]);
    }

    /**
     * Delete Firewall Rule.
     * 
     * Delete a Firewall Rule.
     * 
     * @param  string  $firewallGroupId  The Firewall Group id.
     * @param  string  $firewallRuleId  The Firewall Rule id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_firewall_group_rule')]
    public function deleteFirewallGroupRule(
        string $firewallGroupId,
        string $firewallRuleId,
    ): array
    {
        $this->getClient()->delete('/firewalls/{firewallGroupId/rules/{firewallRuleId');

        return ['success' => true];
    }

    /**
     * Get Firewall Rule.
     * 
     * Get a Firewall Rule.
     * 
     * @param  string  $firewallGroupId  The Firewall Group id.
     * @param  string  $firewallRuleId  The Firewall Rule id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_firewall_group_rule')]
    public function getFirewallGroupRule(
        string $firewallGroupId,
        string $firewallRuleId,
    ): array
    {
        return $this->getClient()->get('/firewalls/{firewallGroupId/rules/{firewallRuleId');
    }

}