<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /v2 endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class IamTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * Assume Role.
     * 
     * Create an assumed-role session by assuming an IAM Role.
     * 
     * @param  string|null  $roleId  The Role ID to assume.
     * @param  string|null  $sessionName  A name for the session.
     * @param  int|null  $duration  Session duration in seconds. Default is 3600.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'iam_assume_role')]
    public function iamAssumeRole(
        ?string $roleId = null,
        ?string $sessionName = null,
        ?int $duration = null,
    ): array
    {
        return $this->client->post('/v2/assumed-roles/assume', [
            'role_id' => $roleId,
            'session_name' => $sessionName,
            'duration' => $duration,
        ]);
    }

    /**
     * AWS STS AssumeRole Compatibility.
     * 
     * AWS STS-compatible AssumeRole endpoint. Accepts application/x-www-form-urlencoded and returns XML.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'iam_aws_sts_assume_role')]
    public function iamAwsStsAssumeRole(): array
    {
        return $this->client->post('/v2/assumed-roles/compatibility/aws/sts');
    }

    /**
     * List Assumed Role Sessions.
     * 
     * List all assumed-role sessions for a User.
     * 
     * @param  string  $userId  The User ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_assumed_role_sessions')]
    public function listIamAssumedRoleSessions(
        string $userId,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/assumed-roles/users/{userId/sessions', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Delete Assumed Role Session.
     * 
     * Delete an assumed-role session.
     * 
     * @param  string  $sessionToken  The session token.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_iam_assumed_role_session')]
    public function deleteIamAssumedRoleSession(
        string $sessionToken,
    ): array
    {
        $this->getClient()->delete('/v2/assumed-roles/{sessionToken');

        return ['success' => true];
    }

    /**
     * List Groups.
     * 
     * Get a list of all Groups in your account.
     * 
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_groups')]
    public function listIamGroups(
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/groups', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Group.
     * 
     * Create a new IAM Group.
     * 
     * @param  string|null  $displayName  The group display name.
     * @param  string|null  $description  A description of the group.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_iam_group')]
    public function createIamGroup(
        ?string $displayName = null,
        ?string $description = null,
    ): array
    {
        return $this->client->post('/v2/groups', [
            'display_name' => $displayName,
            'description' => $description,
        ]);
    }

    /**
     * List Group Members.
     * 
     * List all Members in a Group.
     * 
     * @param  string  $groupId  The Group ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_group_members')]
    public function listIamGroupMembers(
        string $groupId,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/groups/{groupId/members', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Add Group Member.
     * 
     * Add a User to a Group.
     * 
     * @param  string  $groupId  The Group ID.
     * @param  string|null  $displayName  The User ID or display name to add to the group.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'add_iam_group_member')]
    public function addIamGroupMember(
        string $groupId,
        ?string $displayName = null,
    ): array
    {
        return $this->client->post('/v2/groups/{groupId/members', [
            'display_name' => $displayName,
        ]);
    }

    /**
     * Remove Group Member.
     * 
     * Remove a Member from a Group.
     * 
     * @param  string  $groupId  The Group ID.
     * @param  string  $id  The Group Member ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'remove_iam_group_member')]
    public function removeIamGroupMember(
        string $groupId,
        string $id,
    ): array
    {
        $this->getClient()->delete('/v2/groups/{groupId/members/{id');

        return ['success' => true];
    }

    /**
     * Get Group Member.
     * 
     * Get information about a Group Member.
     * 
     * @param  string  $groupId  The Group ID.
     * @param  string  $id  The Group Member ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_iam_group_member')]
    public function getIamGroupMember(
        string $groupId,
        string $id,
    ): array
    {
        return $this->getClient()->get('/v2/groups/{groupId/members/{id');
    }

    /**
     * Restore Group Member.
     * 
     * Restore a soft-deleted Group Member.
     * 
     * @param  string  $groupId  The Group ID.
     * @param  string  $id  The Group Member ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'restore_iam_group_member')]
    public function restoreIamGroupMember(
        string $groupId,
        string $id,
    ): array
    {
        return $this->client->put('/v2/groups/{groupId/members/{id');
    }

    /**
     * Delete Group.
     * 
     * Delete a Group.
     * 
     * @param  string  $id  The Group ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_iam_group')]
    public function deleteIamGroup(
        string $id,
    ): array
    {
        $this->getClient()->delete('/v2/groups/{id');

        return ['success' => true];
    }

    /**
     * Get Group.
     * 
     * Get information about a Group.
     * 
     * @param  string  $id  The Group ID.
     * @param  bool|null  $showLastActivity  Set to true to include the last_activity field in the response.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_iam_group')]
    public function getIamGroup(
        string $id,
        ?bool $showLastActivity = null,
    ): array
    {
        return $this->getClient()->get('/v2/groups/{id', [
            'show_last_activity' => $showLastActivity,
        ]);
    }

    /**
     * Update Group.
     * 
     * Update a Group.
     * 
     * @param  string  $id  The Group ID.
     * @param  string|null  $displayName  The group display name.
     * @param  string|null  $description  A description of the group.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_iam_group')]
    public function updateIamGroup(
        string $id,
        ?string $displayName = null,
        ?string $description = null,
    ): array
    {
        return $this->client->put('/v2/groups/{id', [
            'display_name' => $displayName,
            'description' => $description,
        ]);
    }

    /**
     * List Group Policies.
     * 
     * List the Policies assigned to a Group.
     * 
     * @param  string  $id  The Group ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_group_policies')]
    public function listIamGroupPolicies(
        string $id,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/groups/{id/policies', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * List Group Roles.
     * 
     * List the Roles assigned to a Group.
     * 
     * @param  string  $id  The Group ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_group_roles')]
    public function listIamGroupRoles(
        string $id,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/groups/{id/roles', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * List Policies.
     * 
     * Get a list of all Policies in your account.
     * 
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_policies')]
    public function listIamPolicies(
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/policies', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Policy.
     * 
     * Create a new IAM Policy.
     * 
     * @param  string|null  $name  The policy name.
     * @param  string|null  $description  A description of the policy.
     * @param  array|null  $policyDocument  The policy document defining permissions.
     * @param  string|null  $version  The policy version. Default is 2012-10-17.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_iam_policy')]
    public function createIamPolicy(
        ?string $name = null,
        ?string $description = null,
        ?array $policyDocument = null,
        ?string $version = null,
    ): array
    {
        return $this->client->post('/v2/policies', [
            'name' => $name,
            'description' => $description,
            'policy_document' => $policyDocument,
            'version' => $version,
        ]);
    }

    /**
     * Delete Policy.
     * 
     * Delete a Policy.
     * 
     * @param  string  $id  The Policy ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_iam_policy')]
    public function deleteIamPolicy(
        string $id,
    ): array
    {
        $this->getClient()->delete('/v2/policies/{id');

        return ['success' => true];
    }

    /**
     * Get Policy.
     * 
     * Get information about a Policy.
     * 
     * @param  string  $id  The Policy ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_iam_policy')]
    public function getIamPolicy(
        string $id,
    ): array
    {
        return $this->getClient()->get('/v2/policies/{id');
    }

    /**
     * Update Policy.
     * 
     * Update a Policy.
     * 
     * @param  string  $id  The Policy ID.
     * @param  string|null  $name  The policy name.
     * @param  string|null  $description  A description of the policy.
     * @param  array|null  $policyDocument  The policy document defining permissions.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_iam_policy')]
    public function updateIamPolicy(
        string $id,
        ?string $name = null,
        ?string $description = null,
        ?array $policyDocument = null,
    ): array
    {
        return $this->client->put('/v2/policies/{id', [
            'name' => $name,
            'description' => $description,
            'policy_document' => $policyDocument,
        ]);
    }

    /**
     * Restore Policy.
     * 
     * Restore a soft-deleted Policy.
     * 
     * @param  string  $id  The Policy ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'restore_iam_policy')]
    public function restoreIamPolicy(
        string $id,
    ): array
    {
        return $this->client->patch('/v2/policies/{id/restore');
    }

    /**
     * List Policy Groups.
     * 
     * List the Groups attached to a Policy.
     * 
     * @param  string  $policyId  The Policy ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_policy_groups')]
    public function listIamPolicyGroups(
        string $policyId,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/policies/{policyId/groups', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Detach Group from Policy.
     * 
     * Detach a Group from a Policy.
     * 
     * @param  string  $policyId  The Policy ID.
     * @param  string  $groupId  The Group ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'detach_iam_group_from_policy')]
    public function detachIamGroupFromPolicy(
        string $policyId,
        string $groupId,
    ): array
    {
        $this->getClient()->delete('/v2/policies/{policyId/groups/{groupId');

        return ['success' => true];
    }

    /**
     * Attach Group to Policy.
     * 
     * Attach a Group to a Policy.
     * 
     * @param  string  $policyId  The Policy ID.
     * @param  string  $groupId  The Group ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'attach_iam_group_to_policy')]
    public function attachIamGroupToPolicy(
        string $policyId,
        string $groupId,
    ): array
    {
        return $this->client->post('/v2/policies/{policyId/groups/{groupId');
    }

    /**
     * List Policy Users.
     * 
     * List the Users attached to a Policy.
     * 
     * @param  string  $policyId  The Policy ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_policy_users')]
    public function listIamPolicyUsers(
        string $policyId,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/policies/{policyId/users', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Detach User from Policy.
     * 
     * Detach a User from a Policy.
     * 
     * @param  string  $policyId  The Policy ID.
     * @param  string  $userId  The User ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'detach_iam_user_from_policy')]
    public function detachIamUserFromPolicy(
        string $policyId,
        string $userId,
    ): array
    {
        $this->getClient()->delete('/v2/policies/{policyId/users/{userId');

        return ['success' => true];
    }

    /**
     * Attach User to Policy.
     * 
     * Attach a User to a Policy.
     * 
     * @param  string  $policyId  The Policy ID.
     * @param  string  $userId  The User ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'attach_iam_user_to_policy')]
    public function attachIamUserToPolicy(
        string $policyId,
        string $userId,
    ): array
    {
        return $this->client->post('/v2/policies/{policyId/users/{userId');
    }

    /**
     * List Role Trusts.
     * 
     * Get a list of all Role Trusts in your account.
     * 
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_role_trusts')]
    public function listIamRoleTrusts(
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/role-trusts', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Role Trust.
     * 
     * Create a new Role Trust.
     * 
     * @param  string|null  $roleId  The Role ID this trust applies to.
     * @param  string|null  $trustType  The trust type: TemporaryAssumption, FederatedAssumption, or IAMAssumption.
     * @param  string|null  $trustedUserId  The trusted User ID (for TemporaryAssumption or IAMAssumption).
     * @param  string|null  $trustedGroupId  The trusted Group ID.
     * @param  string|null  $trustedOidcIssuerId  The trusted OIDC Issuer ID (for FederatedAssumption).
     * @param  array|null  $conditions  Conditions that must be met for the trust to apply.
     * @param  string|null  $validUntil  Expiration date of the trust (ISO 8601).
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_iam_role_trust')]
    public function createIamRoleTrust(
        ?string $roleId = null,
        ?string $trustType = null,
        ?string $trustedUserId = null,
        ?string $trustedGroupId = null,
        ?string $trustedOidcIssuerId = null,
        ?array $conditions = null,
        ?string $validUntil = null,
    ): array
    {
        return $this->client->post('/v2/role-trusts', [
            'role_id' => $roleId,
            'trust_type' => $trustType,
            'trusted_user_id' => $trustedUserId,
            'trusted_group_id' => $trustedGroupId,
            'trusted_oidc_issuer_id' => $trustedOidcIssuerId,
            'conditions' => $conditions,
            'valid_until' => $validUntil,
        ]);
    }

    /**
     * List Assumable Roles for User.
     * 
     * List all Roles that a User can assume.
     * 
     * @param  string  $userId  The User ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_assumable_roles')]
    public function listIamAssumableRoles(
        string $userId,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/role-trusts/assumable/{userId', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * List Role Trusts by Role.
     * 
     * List all Role Trusts for a specific Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_role_trusts_by_role')]
    public function listIamRoleTrustsByRole(
        string $roleId,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/role-trusts/by-role/{roleId', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Delete Role Trust.
     * 
     * Delete a Role Trust.
     * 
     * @param  string  $id  The Role Trust ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_iam_role_trust')]
    public function deleteIamRoleTrust(
        string $id,
    ): array
    {
        $this->getClient()->delete('/v2/role-trusts/{id');

        return ['success' => true];
    }

    /**
     * Get Role Trust.
     * 
     * Get information about a Role Trust.
     * 
     * @param  string  $id  The Role Trust ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_iam_role_trust')]
    public function getIamRoleTrust(
        string $id,
    ): array
    {
        return $this->getClient()->get('/v2/role-trusts/{id');
    }

    /**
     * Update Role Trust.
     * 
     * Update a Role Trust.
     * 
     * @param  string  $id  The Role Trust ID.
     * @param  string|null  $trustType  The trust type: TemporaryAssumption, FederatedAssumption, or IAMAssumption.
     * @param  string|null  $trustedUserId  The trusted User ID.
     * @param  string|null  $trustedGroupId  The trusted Group ID.
     * @param  string|null  $trustedOidcIssuerId  The trusted OIDC Issuer ID.
     * @param  array|null  $conditions  Conditions that must be met for the trust to apply.
     * @param  string|null  $validUntil  Expiration date of the trust (ISO 8601).
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_iam_role_trust')]
    public function updateIamRoleTrust(
        string $id,
        ?string $trustType = null,
        ?string $trustedUserId = null,
        ?string $trustedGroupId = null,
        ?string $trustedOidcIssuerId = null,
        ?array $conditions = null,
        ?string $validUntil = null,
    ): array
    {
        return $this->client->put('/v2/role-trusts/{id', [
            'trust_type' => $trustType,
            'trusted_user_id' => $trustedUserId,
            'trusted_group_id' => $trustedGroupId,
            'trusted_oidc_issuer_id' => $trustedOidcIssuerId,
            'conditions' => $conditions,
            'valid_until' => $validUntil,
        ]);
    }

    /**
     * Restore Role Trust.
     * 
     * Restore a soft-deleted Role Trust.
     * 
     * @param  string  $id  The Role Trust ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'restore_iam_role_trust')]
    public function restoreIamRoleTrust(
        string $id,
    ): array
    {
        return $this->client->patch('/v2/role-trusts/{id/restore');
    }

    /**
     * List Roles.
     * 
     * Get a list of all Roles in your account.
     * 
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_roles')]
    public function listIamRoles(
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/roles', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Role.
     * 
     * Create a new IAM Role.
     * 
     * @param  string|null  $name  The role name.
     * @param  string|null  $description  A description of the role.
     * @param  string|null  $roleType  The role type. Default is assumable.
     * @param  int|null  $maxSessionDuration  Maximum session duration in seconds. Default is 3600.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_iam_role')]
    public function createIamRole(
        ?string $name = null,
        ?string $description = null,
        ?string $roleType = null,
        ?int $maxSessionDuration = null,
    ): array
    {
        return $this->client->post('/v2/roles', [
            'name' => $name,
            'description' => $description,
            'role_type' => $roleType,
            'max_session_duration' => $maxSessionDuration,
        ]);
    }

    /**
     * Delete Role.
     * 
     * Delete a Role.
     * 
     * @param  string  $id  The Role ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_iam_role')]
    public function deleteIamRole(
        string $id,
    ): array
    {
        $this->getClient()->delete('/v2/roles/{id');

        return ['success' => true];
    }

    /**
     * Get Role.
     * 
     * Get information about a Role.
     * 
     * @param  string  $id  The Role ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_iam_role')]
    public function getIamRole(
        string $id,
    ): array
    {
        return $this->getClient()->get('/v2/roles/{id');
    }

    /**
     * Update Role.
     * 
     * Update a Role.
     * 
     * @param  string  $id  The Role ID.
     * @param  string|null  $name  The role name.
     * @param  string|null  $description  A description of the role.
     * @param  string|null  $roleType  The role type.
     * @param  int|null  $maxSessionDuration  Maximum session duration in seconds.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_iam_role')]
    public function updateIamRole(
        string $id,
        ?string $name = null,
        ?string $description = null,
        ?string $roleType = null,
        ?int $maxSessionDuration = null,
    ): array
    {
        return $this->client->put('/v2/roles/{id', [
            'name' => $name,
            'description' => $description,
            'role_type' => $roleType,
            'max_session_duration' => $maxSessionDuration,
        ]);
    }

    /**
     * Restore Role.
     * 
     * Restore a soft-deleted Role.
     * 
     * @param  string  $id  The Role ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'restore_iam_role')]
    public function restoreIamRole(
        string $id,
    ): array
    {
        return $this->client->patch('/v2/roles/{id/restore');
    }

    /**
     * List Role Groups.
     * 
     * List the Groups assigned to a Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_role_groups')]
    public function listIamRoleGroups(
        string $roleId,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/roles/{roleId/groups', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Remove Group from Role.
     * 
     * Remove a Group from a Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  string  $groupId  The Group ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'remove_iam_group_from_role')]
    public function removeIamGroupFromRole(
        string $roleId,
        string $groupId,
    ): array
    {
        $this->getClient()->delete('/v2/roles/{roleId/groups/{groupId');

        return ['success' => true];
    }

    /**
     * Assign Group to Role.
     * 
     * Assign a Group to a Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  string  $groupId  The Group ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'assign_iam_group_to_role')]
    public function assignIamGroupToRole(
        string $roleId,
        string $groupId,
    ): array
    {
        return $this->client->post('/v2/roles/{roleId/groups/{groupId');
    }

    /**
     * List Role Policies.
     * 
     * List the Policies assigned to a Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_role_policies')]
    public function listIamRolePolicies(
        string $roleId,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/roles/{roleId/policies', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Remove Policy from Role.
     * 
     * Remove a Policy from a Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  string  $policyId  The Policy ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'remove_iam_policy_from_role')]
    public function removeIamPolicyFromRole(
        string $roleId,
        string $policyId,
    ): array
    {
        $this->getClient()->delete('/v2/roles/{roleId/policies/{policyId');

        return ['success' => true];
    }

    /**
     * Assign Policy to Role.
     * 
     * Assign a Policy to a Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  string  $policyId  The Policy ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'assign_iam_policy_to_role')]
    public function assignIamPolicyToRole(
        string $roleId,
        string $policyId,
    ): array
    {
        return $this->client->post('/v2/roles/{roleId/policies/{policyId');
    }

    /**
     * List Role Users.
     * 
     * List the Users assigned to a Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_iam_role_users')]
    public function listIamRoleUsers(
        string $roleId,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/roles/{roleId/users', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Remove User from Role.
     * 
     * Remove a User from a Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  string  $userId  The User ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'remove_iam_user_from_role')]
    public function removeIamUserFromRole(
        string $roleId,
        string $userId,
    ): array
    {
        $this->getClient()->delete('/v2/roles/{roleId/users/{userId');

        return ['success' => true];
    }

    /**
     * Assign User to Role.
     * 
     * Assign a User to a Role.
     * 
     * @param  string  $roleId  The Role ID.
     * @param  string  $userId  The User ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'assign_iam_user_to_role')]
    public function assignIamUserToRole(
        string $roleId,
        string $userId,
    ): array
    {
        return $this->client->post('/v2/roles/{roleId/users/{userId');
    }

}