<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /instances/templates endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class InstanceTemplatesTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Instance Templates.
     * 
     * List all instance templates in your account.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_instance_templates')]
    public function listInstanceTemplates(): array
    {
        return $this->getClient()->get('/instances/templates');
    }

    /**
     * Create Instance Template.
     * 
     * Create a new instance template.
     * 
     * @param  string  $plan  The Plan id for instances created from this template.
     * @param  string|null  $label  A user-supplied label for this template.
     * @param  string|null  $isoId  The ISO id to deploy from.
     * @param  int|null  $marketplaceAppId  The Marketplace Application id.
     * @param  int|null  $marketplaceImageId  The Marketplace image_id.
     * @param  int|null  $osId  The Operating System id to deploy.
     * @param  string|null  $snapshotId  The Snapshot id to deploy from.
     * @param  array|null  $sshKeyIds  Array of SSH Key ids to install.
     * @param  array|null  $vfsIds  Array of VFS subscription ids to attach.
     * @param  array|null  $template  Additional template configuration as a JSON object.
     * @param  string|null  $userData  base64 encoded string containing user_data that should be executed by cloud init.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_instance_template')]
    public function createInstanceTemplate(
        string $plan,
        ?string $label = null,
        ?string $isoId = null,
        ?int $marketplaceAppId = null,
        ?int $marketplaceImageId = null,
        ?int $osId = null,
        ?string $snapshotId = null,
        ?array $sshKeyIds = null,
        ?array $vfsIds = null,
        ?array $template = null,
        ?string $userData = null,
    ): array
    {
        return $this->client->post('/instances/templates', [
            'plan' => $plan,
            'label' => $label,
            'iso_id' => $isoId,
            'marketplace_app_id' => $marketplaceAppId,
            'marketplace_image_id' => $marketplaceImageId,
            'os_id' => $osId,
            'snapshot_id' => $snapshotId,
            'ssh_key_ids' => $sshKeyIds,
            'vfs_ids' => $vfsIds,
            'template' => $template,
            'user_data' => $userData,
        ]);
    }

    /**
     * Delete Instance Template.
     * 
     * Delete an instance template.
     * 
     * @param  string  $instancetemplateId  The Instance Template ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_instance_template')]
    public function deleteInstanceTemplate(
        string $instancetemplateId,
    ): array
    {
        $this->getClient()->delete('/instances/templates/{instancetemplateId');

        return ['success' => true];
    }

    /**
     * Get Instance Template.
     * 
     * Get information about an instance template.
     * 
     * @param  string  $instancetemplateId  The Instance Template ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_template')]
    public function getInstanceTemplate(
        string $instancetemplateId,
    ): array
    {
        return $this->getClient()->get('/instances/templates/{instancetemplateId');
    }

    /**
     * Update Instance Template.
     * 
     * Update an instance template. At least one parameter must be provided.
     * 
     * @param  string  $instancetemplateId  The Instance Template ID.
     * @param  string|null  $plan  The Plan id for instances created from this template.
     * @param  string|null  $label  A user-supplied label for this template.
     * @param  string|null  $isoId  The ISO id to deploy from.
     * @param  int|null  $marketplaceAppId  The Marketplace Application id.
     * @param  int|null  $marketplaceImageId  The Marketplace image_id.
     * @param  int|null  $osId  The Operating System id to deploy.
     * @param  string|null  $snapshotId  The Snapshot id to deploy from.
     * @param  array|null  $sshKeyIds  Array of SSH Key ids to install.
     * @param  array|null  $vfsIds  Array of VFS subscription ids to attach.
     * @param  array|null  $template  Additional template configuration as a JSON object.
     * @param  string|null  $userData  base64 encoded string containing user_data that should be executed by cloud init.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_instance_template')]
    public function updateInstanceTemplate(
        string $instancetemplateId,
        ?string $plan = null,
        ?string $label = null,
        ?string $isoId = null,
        ?int $marketplaceAppId = null,
        ?int $marketplaceImageId = null,
        ?int $osId = null,
        ?string $snapshotId = null,
        ?array $sshKeyIds = null,
        ?array $vfsIds = null,
        ?array $template = null,
        ?string $userData = null,
    ): array
    {
        return $this->client->put('/instances/templates/{instancetemplateId', [
            'plan' => $plan,
            'label' => $label,
            'iso_id' => $isoId,
            'marketplace_app_id' => $marketplaceAppId,
            'marketplace_image_id' => $marketplaceImageId,
            'os_id' => $osId,
            'snapshot_id' => $snapshotId,
            'ssh_key_ids' => $sshKeyIds,
            'vfs_ids' => $vfsIds,
            'template' => $template,
            'user_data' => $userData,
        ]);
    }

}