<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /instances endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class InstanceTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Instances.
     * 
     * List all VPS instances in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @param  string|null  $label  Filter by label.
     * @param  string|null  $mainIp  Filter by main ip address.
     * @param  string|null  $region  Filter by Region id.
     * @param  string|null  $firewallGroupId  Filter by Firewall group id.
     * @param  string|null  $hostname  Filter by hostname.
     * @param  bool|null  $showPendingCharges  Set to true to show pending charges.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_instances')]
    public function listInstances(
        ?int $perPage = null,
        ?string $cursor = null,
        ?string $label = null,
        ?string $mainIp = null,
        ?string $region = null,
        ?string $firewallGroupId = null,
        ?string $hostname = null,
        ?bool $showPendingCharges = null,
    ): array
    {
        return $this->getClient()->get('/instances', [
            'per_page' => $perPage,
            'cursor' => $cursor,
            'label' => $label,
            'main_ip' => $mainIp,
            'region' => $region,
            'firewall_group_id' => $firewallGroupId,
            'hostname' => $hostname,
            'show_pending_charges' => $showPendingCharges,
        ]);
    }

    /**
     * Create Instance.
     * 
     * Create a new VPS Instance in a region with the desired plan. Choose one of the following to deploy
     * the instance:
     * 
     *  os_id
     *  iso_id
     *  snapshot_id
     *  app_id
     * * image_id
     * 
     * Supply other attributes as desired.
     * 
     * @param  string  $region  The Region id where the Instance is located.
     * @param  string  $plan  The Plan id to use when deploying this instance.
     * @param  int|null  $osId  The Operating System id to use when deploying this instance.
     * @param  string|null  $ipxeChainUrl  The URL location of the iPXE chainloader.
     * @param  string|null  $isoId  The ISO id to use when deploying this instance.
     * @param  string|null  $scriptId  The Startup Script id to use when deploying this instance.
     * @param  string|null  $snapshotId  The Snapshot id to use when deploying the instance.
     * @param  bool|null  $enableIpv6  Enable IPv6.

* true
     * @param  bool|null  $disablePublicIpv4  Don't set up a public IPv4 address when IPv6 is enabled. Will not do anything unless enable_ipv6 is also true.

* true
     * @param  array|null  $attachVpc  An array of VPC IDs to attach to this Instance. This parameter takes precedence over enable_vpc. Please choose one parameter.
     * @param  string|null  $label  A user-supplied label for this instance.
     * @param  array|null  $sshkeyId  The SSH Key id to install on this instance.
     * @param  string|null  $backups  Enable automatic backups for the instance (does not work for VX1 block storage).

 enabled
 disabled
     * @param  array|null  $blockDevices  Available for VX1 instances: Define your block devices, create bootable block devices, use local storage (if plan has local storage) as scratch disk.
Local Only:
``
"block_devices": [
  {
    "block_id": "local",
    "bootable": true
  }
]
`
Local Boot + New Block:
`
"block_devices": [
  {
    "block_id": "local",
    "bootable": true
  },
  {
    "disk_size": 50,
    "label": "New Block Label"
  }
]
`
Bootable Block (new):
`
"block_devices": [
  {
    "disk_size": 50,
    "label": "New Bootable Block",
    "bootable": true
  }
]
`
Bootable Block (existing):
`
"block_devices": [
  {
    "block_id": "BLOCK_DEVICE_UUID",
    "bootable": true
  }
]
`
Bootable Block (existing) and Local NVMe:
`
"block_devices": [
  {
    "block_id": "local"
  },
  {
    "block_id": "BLOCK_DEVICE_UUID",
    "bootable": true
  }
]
``
     * @param  int|null  $appId  The Application id to use when deploying this instance.
     * @param  string|null  $imageId  The Application image_id to use when deploying this instance.
     * @param  string|null  $userData  The user-supplied, base64 encoded user data to attach to this instance.
     * @param  bool|null  $ddosProtection  Enable DDoS protection (there is an additional charge for this).

 true
 false
     * @param  bool|null  $activationEmail  Notify by email after deployment.

 true
 false (default)
     * @param  string|null  $hostname  The hostname to use when deploying this instance.
     * @param  string|null  $firewallGroupId  The Firewall Group id to attach to this Instance.
     * @param  string|null  $reservedIpv4  ID of the floating IP to use as the main IP of this server.
     * @param  bool|null  $enableVpc  If true, VPC support will be added to the new server.

This parameter attaches a single VPC. When no VPC exists in the region, it will be automatically created.

If there are multiple VPCs in the instance's region, use attach_vpc instead to specify a network.
     * @param  bool|null  $vpcOnly  if true, this VPS will not receive a public IP or public NIC.

A vpc_id will be required in the attach_vpc array. The first vpc_id provided must have a NAT Gateway attached.

This VPS will gain access to the internet via the NAT Gateway attached to the VPC.
     * @param  array|null  $tags  Tags to apply to the instance
     * @param  string|null  $userScheme  Linux-only: The user scheme used for logging into this instance. By default, the "root" user is configured. Alternatively, a limited user with sudo permissions can be selected.

 root
 limited
     * @param  array|null  $appVariables  The app variable inputs for configuring the marketplace app (name/value pairs).
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_instance')]
    public function createInstance(
        string $region,
        string $plan,
        ?int $osId = null,
        ?string $ipxeChainUrl = null,
        ?string $isoId = null,
        ?string $scriptId = null,
        ?string $snapshotId = null,
        ?bool $enableIpv6 = null,
        ?bool $disablePublicIpv4 = null,
        ?array $attachVpc = null,
        ?string $label = null,
        ?array $sshkeyId = null,
        ?string $backups = null,
        ?array $blockDevices = null,
        ?int $appId = null,
        ?string $imageId = null,
        ?string $userData = null,
        ?bool $ddosProtection = null,
        ?bool $activationEmail = null,
        ?string $hostname = null,
        ?string $firewallGroupId = null,
        ?string $reservedIpv4 = null,
        ?bool $enableVpc = null,
        ?bool $vpcOnly = null,
        ?array $tags = null,
        ?string $userScheme = null,
        ?array $appVariables = null,
    ): array
    {
        return $this->client->post('/instances', [
            'region' => $region,
            'plan' => $plan,
            'os_id' => $osId,
            'ipxe_chain_url' => $ipxeChainUrl,
            'iso_id' => $isoId,
            'script_id' => $scriptId,
            'snapshot_id' => $snapshotId,
            'enable_ipv6' => $enableIpv6,
            'disable_public_ipv4' => $disablePublicIpv4,
            'attach_vpc' => $attachVpc,
            'label' => $label,
            'sshkey_id' => $sshkeyId,
            'backups' => $backups,
            'block_devices' => $blockDevices,
            'app_id' => $appId,
            'image_id' => $imageId,
            'user_data' => $userData,
            'ddos_protection' => $ddosProtection,
            'activation_email' => $activationEmail,
            'hostname' => $hostname,
            'firewall_group_id' => $firewallGroupId,
            'reserved_ipv4' => $reservedIpv4,
            'enable_vpc' => $enableVpc,
            'vpc_only' => $vpcOnly,
            'tags' => $tags,
            'user_scheme' => $userScheme,
            'app_variables' => $appVariables,
        ]);
    }

    /**
     * Halt Instances.
     * 
     * @param  array|null  $instanceIds  The Instance IDs to halt.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'halt_instances')]
    public function haltInstances(
        ?array $instanceIds = null,
    ): array
    {
        return $this->client->post('/instances/halt', [
            'instance_ids' => $instanceIds,
        ]);
    }

    /**
     * Get Instance Job.
     * 
     * Get available information for an Instance job
     * 
     * @param  string  $jobId  The Job ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_job')]
    public function getInstanceJob(
        string $jobId,
    ): array
    {
        return $this->getClient()->get('/instances/jobs/{jobId');
    }

    /**
     * Reboot instances.
     * 
     * Reboot Instances.
     * 
     * @param  array|null  $instanceIds  The Instance IDs to reboot.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'reboot_instances')]
    public function rebootInstances(
        ?array $instanceIds = null,
    ): array
    {
        return $this->client->post('/instances/reboot', [
            'instance_ids' => $instanceIds,
        ]);
    }

    /**
     * Start instances.
     * 
     * Start Instances.
     * 
     * @param  array|null  $instanceIds  The Instance IDs to start.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'start_instances')]
    public function startInstances(
        ?array $instanceIds = null,
    ): array
    {
        return $this->client->post('/instances/start', [
            'instance_ids' => $instanceIds,
        ]);
    }

    /**
     * Delete Instance.
     * 
     * Delete an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_instance')]
    public function deleteInstance(
        string $instanceId,
    ): array
    {
        $this->getClient()->delete('/instances/{instanceId');

        return ['success' => true];
    }

    /**
     * Get Instance.
     * 
     * Get information about an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance')]
    public function getInstance(
        string $instanceId,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId');
    }

    /**
     * Update Instance.
     * 
     * Update information for an Instance. All attributes are optional. If not set, the attributes will
     * retain their original values.
     * 
     * Note: Changing os_id, app_id or image_id may take a few extra seconds to complete.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  int|null  $appId  Reinstall the instance with this Application id.
     * @param  string|null  $imageId  Reinstall the instance with this Application image_id.
     * @param  string|null  $backups  Enable automatic backups for the instance.

 enabled
 disabled
     * @param  string|null  $firewallGroupId  The Firewall Group id to attach to this Instance.
     * @param  bool|null  $enableIpv6  Enable IPv6.

* true
     * @param  string|null  $osId  Reinstall the instance with this ISO id.
     * @param  string|null  $userData  The user-supplied, base64 encoded user data to attach to this instance.
     * @param  string|null  $plan  Upgrade the instance with this Plan id.
     * @param  bool|null  $ddosProtection  Enable DDoS Protection (there is an additional charge for this).

 true
 false
     * @param  array|null  $attachVpc  An array of VPC IDs to attach to this Instance. This parameter takes precedence over enable_vpc. Please choose one parameter.
     * @param  array|null  $detachVpc  An array of VPC IDs to detach from this Instance. This parameter takes precedence over enable_vpc.
     * @param  bool|null  $enableVpc  If true, VPC support will be added to the new server.

This parameter attaches a single VPC. When no VPC exists in the region, it will be automatically created.

If there are multiple VPCs in the instance's region, use attach_vpc instead to specify a VPC.
     * @param  string|null  $label  The user supplied label.
     * @param  array|null  $tags  Tags to apply to the instance.
     * @param  string|null  $userScheme  Linux-only: The user scheme used for logging into this instance. The instance must be reinstalled for this change to take effect.

 root
 limited
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_instance')]
    public function updateInstance(
        string $instanceId,
        ?int $appId = null,
        ?string $imageId = null,
        ?string $backups = null,
        ?string $firewallGroupId = null,
        ?bool $enableIpv6 = null,
        ?string $osId = null,
        ?string $userData = null,
        ?string $plan = null,
        ?bool $ddosProtection = null,
        ?array $attachVpc = null,
        ?array $detachVpc = null,
        ?bool $enableVpc = null,
        ?string $label = null,
        ?array $tags = null,
        ?string $userScheme = null,
    ): array
    {
        return $this->client->patch('/instances/{instanceId', [
            'app_id' => $appId,
            'image_id' => $imageId,
            'backups' => $backups,
            'firewall_group_id' => $firewallGroupId,
            'enable_ipv6' => $enableIpv6,
            'os_id' => $osId,
            'user_data' => $userData,
            'plan' => $plan,
            'ddos_protection' => $ddosProtection,
            'attach_vpc' => $attachVpc,
            'detach_vpc' => $detachVpc,
            'enable_vpc' => $enableVpc,
            'label' => $label,
            'tags' => $tags,
            'user_scheme' => $userScheme,
        ]);
    }

    /**
     * Get Instance Backup Schedule.
     * 
     * Get the backup schedule for an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_backup_schedule')]
    public function getInstanceBackupSchedule(
        string $instanceId,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/backup-schedule');
    }

    /**
     * Set Instance Backup Schedule.
     * 
     * Set the backup schedule for an Instance in UTC. The type is required.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string  $type  Type of backup schedule:

|   | Value | Description |
| - | ------ | ------------- |
|   | daily | Back up once per day at hour. |
|   | weekly | Back up once per week on dow at hour. |
|   | monthly | Back up each month at dom at hour. |
|   | daily\_alt\_even | Back up on even dates at hour. |
|   | daily\_alt\_odd | Back up on odd dates at hour. |
     * @param  int|null  $hour  Hour of day to run in UTC.
     * @param  int|null  $dow  Day of week to run.

|   | Value | Description |
| - | ------ | ------------- |
|   | 1 | Sunday |
|   | 2 | Monday |
|   | 3 | Tuesday |
|   | 4 | Wednesday |
|   | 5 | Thursday |
|   | 6 | Friday |
|   | 7 | Saturday |
     * @param  int|null  $dom  Day of month to run. Use values between 1 and 28.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_instance_backup_schedule')]
    public function createInstanceBackupSchedule(
        string $instanceId,
        string $type,
        ?int $hour = null,
        ?int $dow = null,
        ?int $dom = null,
    ): array
    {
        return $this->client->post('/instances/{instanceId/backup-schedule', [
            'type' => $type,
            'hour' => $hour,
            'dow' => $dow,
            'dom' => $dom,
        ]);
    }

    /**
     * Instance Bandwidth.
     * 
     * Get bandwidth information about an Instance.<br><br>The bandwidth object in a successful response
     * contains objects representing a day in the month. The date is denoted by the nested object keys.
     * Days begin and end in the UTC timezone. The bandwidth utilization data contained within the date
     * object is refreshed periodically. We do not recommend using this endpoint to gather real-time
     * metrics.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  int|null  $dateRange  The range of days to include, represented as the number of days relative to the current date. Default 30, Minimum 1 and Max 180.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_bandwidth')]
    public function getInstanceBandwidth(
        string $instanceId,
        ?int $dateRange = null,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/bandwidth', [
            'date_range' => $dateRange,
        ]);
    }

    /**
     * Halt Instance.
     * 
     * Halt an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'halt_instance')]
    public function haltInstance(
        string $instanceId,
    ): array
    {
        return $this->client->post('/instances/{instanceId/halt');
    }

    /**
     * List Instance IPv4 Information.
     * 
     * List the IPv4 information for an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  bool|null  $publicNetwork  If true, includes information about the public network adapter (such as MAC address) with the main_ip entry.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_ipv4')]
    public function getInstanceIpv4(
        string $instanceId,
        ?bool $publicNetwork = null,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/ipv4', [
            'public_network' => $publicNetwork,
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create IPv4.
     * 
     * Create an IPv4 address for an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  bool|null  $reboot  Set if the server is rebooted immediately after the IPv4 address is created.

 true (default)
 false
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_instance_ipv4')]
    public function createInstanceIpv4(
        string $instanceId,
        ?bool $reboot = null,
    ): array
    {
        return $this->client->post('/instances/{instanceId/ipv4', [
            'reboot' => $reboot,
        ]);
    }

    /**
     * Create Instance Reverse IPv4.
     * 
     * Create a reverse IPv4 entry for an Instance. The ip and reverse attributes are required.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string  $ip  The IPv4 address.
     * @param  string  $reverse  The IPv4 reverse entry.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_instance_reverse_ipv4')]
    public function createInstanceReverseIpv4(
        string $instanceId,
        string $ip,
        string $reverse,
    ): array
    {
        return $this->client->post('/instances/{instanceId/ipv4/reverse', [
            'ip' => $ip,
            'reverse' => $reverse,
        ]);
    }

    /**
     * Set Default Reverse DNS Entry.
     * 
     * Set a reverse DNS entry for an IPv4 address
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string  $ip
     * @return array<string, mixed>
     */
    #[McpTool(name: 'post_instances_instance_id_ipv4_reverse_default')]
    public function postInstancesInstanceIdIpv4ReverseDefault(
        string $instanceId,
        string $ip,
    ): array
    {
        return $this->client->post('/instances/{instanceId/ipv4/reverse/default', [
            'ip' => $ip,
        ]);
    }

    /**
     * Delete IPv4 Address.
     * 
     * Delete an IPv4 address from an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string  $ipv4  The IPv4 address.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_instance_ipv4')]
    public function deleteInstanceIpv4(
        string $instanceId,
        string $ipv4,
    ): array
    {
        $this->getClient()->delete('/instances/{instanceId/ipv4/{ipv4');

        return ['success' => true];
    }

    /**
     * Get Instance IPv6 Information.
     * 
     * Get the IPv6 information for an VPS Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_ipv6')]
    public function getInstanceIpv6(
        string $instanceId,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/ipv6');
    }

    /**
     * List Instance IPv6 Reverse.
     * 
     * List the reverse IPv6 information for an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_instance_ipv6_reverse')]
    public function listInstanceIpv6Reverse(
        string $instanceId,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/ipv6/reverse');
    }

    /**
     * Create Instance Reverse IPv6.
     * 
     * Create a reverse IPv6 entry for an Instance. The ip and reverse attributes are required. IP address
     * must be in full, expanded format.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string  $ip  The IPv6 address in full, expanded format.
     * @param  string  $reverse  The IPv6 reverse entry.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_instance_reverse_ipv6')]
    public function createInstanceReverseIpv6(
        string $instanceId,
        string $ip,
        string $reverse,
    ): array
    {
        return $this->client->post('/instances/{instanceId/ipv6/reverse', [
            'ip' => $ip,
            'reverse' => $reverse,
        ]);
    }

    /**
     * Delete Instance Reverse IPv6.
     * 
     * Delete the reverse IPv6 for an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string  $ipv6  The IPv6 address.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_instance_reverse_ipv6')]
    public function deleteInstanceReverseIpv6(
        string $instanceId,
        string $ipv6,
    ): array
    {
        $this->getClient()->delete('/instances/{instanceId/ipv6/reverse/{ipv6');

        return ['success' => true];
    }

    /**
     * Get Instance ISO Status.
     * 
     * Get the ISO status for an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_iso_status')]
    public function getInstanceIsoStatus(
        string $instanceId,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/iso');
    }

    /**
     * Attach ISO to Instance.
     * 
     * Attach an ISO to an Instance.
     * 
     * @param  string  $instanceId
     * @param  string|null  $isoId  The ISO id to attach to this Instance.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'attach_instance_iso')]
    public function attachInstanceIso(
        string $instanceId,
        ?string $isoId = null,
    ): array
    {
        return $this->client->post('/instances/{instanceId/iso/attach', [
            'iso_id' => $isoId,
        ]);
    }

    /**
     * Detach ISO from instance.
     * 
     * Detach the ISO from an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'detach_instance_iso')]
    public function detachInstanceIso(
        string $instanceId,
    ): array
    {
        return $this->client->post('/instances/{instanceId/iso/detach');
    }

    /**
     * Get Instance neighbors.
     * 
     * Get a list of other instances in the same location as this Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_neighbors')]
    public function getInstanceNeighbors(
        string $instanceId,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/neighbors');
    }

    /**
     * Reboot Instance.
     * 
     * Reboot an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'reboot_instance')]
    public function rebootInstance(
        string $instanceId,
    ): array
    {
        return $this->client->post('/instances/{instanceId/reboot');
    }

    /**
     * Reinstall Instance.
     * 
     * Reinstall an Instance using an optional hostname.
     * 
     * Note: This action may take a few extra seconds to complete.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string|null  $hostname  The hostname to use when reinstalling this instance.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'reinstall_instance')]
    public function reinstallInstance(
        string $instanceId,
        ?string $hostname = null,
    ): array
    {
        return $this->client->post('/instances/{instanceId/reinstall', [
            'hostname' => $hostname,
        ]);
    }

    /**
     * Restore Instance.
     * 
     * Restore an Instance from either backup_id or snapshot_id.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string|null  $backupId  The Backup id used to restore this instance.
     * @param  string|null  $snapshotId  The Snapshot id used to restore this instance.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'restore_instance')]
    public function restoreInstance(
        string $instanceId,
        ?string $backupId = null,
        ?string $snapshotId = null,
    ): array
    {
        return $this->client->post('/instances/{instanceId/restore', [
            'backup_id' => $backupId,
            'snapshot_id' => $snapshotId,
        ]);
    }

    /**
     * Start instance.
     * 
     * Start an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'start_instance')]
    public function startInstance(
        string $instanceId,
    ): array
    {
        return $this->client->post('/instances/{instanceId/start');
    }

    /**
     * Get Available Instance Upgrades.
     * 
     * Get available upgrades for an Instance
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string|null  $type  Filter upgrade by type:

- all (applications, os, plans)
- applications
- os
- plans
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_upgrades')]
    public function getInstanceUpgrades(
        string $instanceId,
        ?string $type = null,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/upgrades', [
            'type' => $type,
        ]);
    }

    /**
     * Get Instance User Data.
     * 
     * Get the user-supplied, base64 encoded user data for an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_instance_userdata')]
    public function getInstanceUserdata(
        string $instanceId,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/user-data');
    }

    /**
     * List instance VPCs.
     * 
     * List the VPCs for an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_instance_vpcs')]
    public function listInstanceVpcs(
        string $instanceId,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/instances/{instanceId/vpcs', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Attach VPC to Instance.
     * 
     * Attach a VPC to an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string|null  $vpcId  The VPC ID to attach to this Instance.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'attach_instance_vpc')]
    public function attachInstanceVpc(
        string $instanceId,
        ?string $vpcId = null,
    ): array
    {
        return $this->client->post('/instances/{instanceId/vpcs/attach', [
            'vpc_id' => $vpcId,
        ]);
    }

    /**
     * Detach VPC from Instance.
     * 
     * Detach a VPC from an Instance.
     * 
     * @param  string  $instanceId  The Instance ID.
     * @param  string|null  $vpcId  The VPC ID to detach from this Instance.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'detach_instance_vpc')]
    public function detachInstanceVpc(
        string $instanceId,
        ?string $vpcId = null,
    ): array
    {
        return $this->client->post('/instances/{instanceId/vpcs/detach', [
            'vpc_id' => $vpcId,
        ]);
    }

}