<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /iso endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class IsoTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List ISOs.
     * 
     * Get the ISOs in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_isos')]
    public function listIsos(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/iso', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create ISO.
     * 
     * Create a new ISO in your account from url.
     * 
     * @param  string  $url  Public URL location of the ISO image to download. Example: https://example.com/my-iso.iso
     * @param  string|null  $description  The user-supplied description of the ISO
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_iso')]
    public function createIso(
        string $url,
        ?string $description = null,
    ): array
    {
        return $this->client->post('/iso', [
            'url' => $url,
            'description' => $description,
        ]);
    }

    /**
     * List Public ISOs.
     * 
     * List all Vultr Public ISOs.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_public_isos')]
    public function listPublicIsos(): array
    {
        return $this->getClient()->get('/iso-public');
    }

    /**
     * Delete ISO.
     * 
     * Delete an ISO.
     * 
     * @param  string  $isoId  The ISO id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_iso')]
    public function deleteIso(
        string $isoId,
    ): array
    {
        $this->getClient()->delete('/iso/{isoId');

        return ['success' => true];
    }

    /**
     * Get ISO.
     * 
     * Get information for an ISO.
     * 
     * @param  string  $isoId  The ISO id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'iso_get')]
    public function isoGet(
        string $isoId,
    ): array
    {
        return $this->getClient()->get('/iso/{isoId');
    }

    /**
     * Update ISO.
     * 
     * Update the description for an ISO.
     * 
     * @param  string  $isoId  The ISO id.
     * @param  string  $description  The user-supplied description for the ISO.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'iso_edit')]
    public function isoEdit(
        string $isoId,
        string $description,
    ): array
    {
        return $this->client->put('/iso/{isoId', [
            'description' => $description,
        ]);
    }

}