<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /kubernetes endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class KubernetesTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List all Kubernetes Clusters.
     * 
     * List all Kubernetes clusters currently deployed
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_kubernetes_clusters')]
    public function listKubernetesClusters(): array
    {
        return $this->getClient()->get('/kubernetes/clusters');
    }

    /**
     * Create Kubernetes Cluster.
     * 
     * Create Kubernetes Cluster
     * 
     * @param  string|null  $label  The label for your Kubernetes cluster.
     * @param  string  $region  Region you want to deploy VKE in. See Regions for more information.
     * @param  string  $version  Version of Kubernetes you want to deploy.
     * @param  string|null  $vpcId  The VPC id to use when deploying this VKE. Omitting or leaving this empty will configure a new VPC network with this deployment.
     * @param  bool|null  $haControlplanes  Whether a highly available control planes configuration should be deployed
 true
 false (default)
     * @param  bool|null  $enableFirewall  Whether a Firewall Group should be deployed and managed by this cluster
 true
 false (default)
     * @param  array|null  $oidc  Configure OpenID Connect (OIDC) support for this VKE cluster
     * @param  array|null  $nodePools
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_kubernetes_cluster')]
    public function createKubernetesCluster(
        string $region,
        string $version,
        ?string $label = null,
        ?string $vpcId = null,
        ?bool $haControlplanes = null,
        ?bool $enableFirewall = null,
        ?array $oidc = null,
        ?array $nodePools = null,
    ): array
    {
        return $this->client->post('/kubernetes/clusters', [
            'label' => $label,
            'region' => $region,
            'version' => $version,
            'vpc_id' => $vpcId,
            'ha_controlplanes' => $haControlplanes,
            'enable_firewall' => $enableFirewall,
            'oidc' => $oidc,
            'node_pools' => $nodePools,
        ]);
    }

    /**
     * Delete Kubernetes Cluster.
     * 
     * Delete Kubernetes Cluster
     * 
     * @param  string  $vkeId  The VKE ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_kubernetes_cluster')]
    public function deleteKubernetesCluster(
        string $vkeId,
    ): array
    {
        $this->getClient()->delete('/kubernetes/clusters/{vkeId');

        return ['success' => true];
    }

    /**
     * Get Kubernetes Cluster.
     * 
     * Get Kubernetes Cluster
     * 
     * @param  string  $vkeId  The VKE ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_kubernetes_clusters')]
    public function getKubernetesClusters(
        string $vkeId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId');
    }

    /**
     * Update Kubernetes Cluster.
     * 
     * Update Kubernetes Cluster
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $label  Label for the Kubernetes cluster
     * @param  array|null  $oidc  Configure OpenID Connect (OIDC) support for this VKE cluster
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_kubernetes_cluster')]
    public function updateKubernetesCluster(
        string $vkeId,
        string $label,
        ?array $oidc = null,
    ): array
    {
        return $this->client->put('/kubernetes/clusters/{vkeId', [
            'label' => $label,
            'oidc' => $oidc,
        ]);
    }

    /**
     * Get Kubernetes Available Upgrades.
     * 
     * Get the available upgrades for the specified Kubernetes cluster.
     * 
     * @param  string  $vkeId  The VKE ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_kubernetes_available_upgrades')]
    public function getKubernetesAvailableUpgrades(
        string $vkeId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId/available-upgrades');
    }

    /**
     * Get Kubernetes Cluster Kubeconfig.
     * 
     * Get Kubernetes Cluster Kubeconfig
     * 
     * @param  string  $vkeId  The VKE ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_kubernetes_clusters_config')]
    public function getKubernetesClustersConfig(
        string $vkeId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId/config');
    }

    /**
     * Delete VKE Cluster and All Related Resources.
     * 
     * Delete Kubernetes Cluster and all related resources.
     * 
     * @param  string  $vkeId
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_kubernetes_cluster_vke_id_delete_with_linked_resources')]
    public function deleteKubernetesClusterVkeIdDeleteWithLinkedResources(
        string $vkeId,
    ): array
    {
        $this->getClient()->delete('/kubernetes/clusters/{vkeId/delete-with-linked-resources');

        return ['success' => true];
    }

    /**
     * List NodePools.
     * 
     * List all available NodePools on a Kubernetes Cluster
     * 
     * @param  string  $vkeId  The VKE ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_nodepools')]
    public function getNodepools(
        string $vkeId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId/node-pools');
    }

    /**
     * Create NodePool.
     * 
     * Create NodePool for a Existing Kubernetes Cluster
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  int  $nodeQuantity  Number of instances in this nodepool
     * @param  string  $label  Label for the nodepool. You cannot change the label after a nodepool is created. You cannot have duplicate node pool labels in the same cluster.
     * @param  string  $plan  Plan that this nodepool will use
     * @param  string|null  $tag  Tag for node pool
     * @param  bool|null  $autoScaler  Option to use the auto scaler with your cluster. Default false.
     * @param  int|null  $minNodes  Auto scaler field for minimum nodes you want for your cluster. Default 1.
     * @param  int|null  $maxNodes  Auto scaler field for maximum nodes you want for your cluster. Default 1.
     * @param  array|null  $labels  Map of key/value pairs defining labels to automatically apply to all nodes in this nodepool. Labels will be applied to both new and existing nodes.
     * @param  array|null  $taints  Array of objects containing key, value, and effect.
     * @param  string|null  $userData  The user-supplied, base64 encoded user data for all nodes in nodepool (only applied on nodes created after user data is set).
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_nodepools')]
    public function createNodepools(
        string $vkeId,
        int $nodeQuantity,
        string $label,
        string $plan,
        ?string $tag = null,
        ?bool $autoScaler = null,
        ?int $minNodes = null,
        ?int $maxNodes = null,
        ?array $labels = null,
        ?array $taints = null,
        ?string $userData = null,
    ): array
    {
        return $this->client->post('/kubernetes/clusters/{vkeId/node-pools', [
            'node_quantity' => $nodeQuantity,
            'label' => $label,
            'plan' => $plan,
            'tag' => $tag,
            'auto_scaler' => $autoScaler,
            'min_nodes' => $minNodes,
            'max_nodes' => $maxNodes,
            'labels' => $labels,
            'taints' => $taints,
            'user_data' => $userData,
        ]);
    }

    /**
     * Delete Nodepool.
     * 
     * Delete a NodePool from a Kubernetes Cluster
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_nodepool')]
    public function deleteNodepool(
        string $vkeId,
        string $nodepoolId,
    ): array
    {
        $this->getClient()->delete('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId');

        return ['success' => true];
    }

    /**
     * Get NodePool.
     * 
     * Get Nodepool from a Kubernetes Cluster
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_nodepool')]
    public function getNodepool(
        string $vkeId,
        string $nodepoolId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId');
    }

    /**
     * Update Nodepool.
     * 
     * Update a Nodepool on a Kubernetes Cluster
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @param  int|null  $nodeQuantity  Number of instances in the NodePool. Minimum of 1 is required, but at least 3 is recommended.
     * @param  string|null  $tag  Tag for your node pool
     * @param  bool|null  $autoScaler  Option to use the auto scaler for your cluster. Default false.
     * @param  int|null  $minNodes  Auto scaler field for minimum nodes you want for your cluster. Default 1.
     * @param  int|null  $maxNodes  Auto scaler field for maximum nodes you want for your cluster. Default 1.
     * @param  array|null  $labels  Map of key/value pairs defining labels to automatically apply to all nodes in this nodepool. Labels will be applied to both new and existing nodes. Existing labels are not removed when adding or updating, but can be managed in the separate labels endpoints.
     * @param  array|null  $taints  Array of objects containing key, value, and effect. Existing taints are not removed when adding or updating, but can be managed in the separate taints endpoints.
     * @param  string|null  $userData  The user-supplied, base64 encoded user data for all nodes in nodepool (only applied on nodes created after user data is set).
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_nodepool')]
    public function updateNodepool(
        string $vkeId,
        string $nodepoolId,
        ?int $nodeQuantity = null,
        ?string $tag = null,
        ?bool $autoScaler = null,
        ?int $minNodes = null,
        ?int $maxNodes = null,
        ?array $labels = null,
        ?array $taints = null,
        ?string $userData = null,
    ): array
    {
        return $this->client->patch('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId', [
            'node_quantity' => $nodeQuantity,
            'tag' => $tag,
            'auto_scaler' => $autoScaler,
            'min_nodes' => $minNodes,
            'max_nodes' => $maxNodes,
            'labels' => $labels,
            'taints' => $taints,
            'user_data' => $userData,
        ]);
    }

    /**
     * List NodePool Labels.
     * 
     * List NodePool Labels on Kubernetes Nodepool
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_nodepool_labels')]
    public function listNodepoolLabels(
        string $vkeId,
        string $nodepoolId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/labels');
    }

    /**
     * Create NodePool Label.
     * 
     * Add NodePool Label to Existing Kubernetes Nodepool
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_nodepool_label')]
    public function createNodepoolLabel(
        string $vkeId,
        string $nodepoolId,
    ): array
    {
        return $this->client->post('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/labels');
    }

    /**
     * Delete NodePool Label.
     * 
     * Delete NodePool Label on Kubernetes Nodepool
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @param  string  $labelId  The NodePool Label ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_nodepool_label')]
    public function deleteNodepoolLabel(
        string $vkeId,
        string $nodepoolId,
        string $labelId,
    ): array
    {
        $this->getClient()->delete('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/labels/{labelId');

        return ['success' => true];
    }

    /**
     * Read NodePool Label.
     * 
     * Read NodePool Label on Kubernetes Nodepool
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @param  string  $labelId  The NodePool Label ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'read_nodepool_label')]
    public function readNodepoolLabel(
        string $vkeId,
        string $nodepoolId,
        string $labelId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/labels/{labelId');
    }

    /**
     * Delete NodePool Instance.
     * 
     * Delete a single nodepool instance from a given Nodepool
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @param  string  $nodeId  The Instance ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_nodepool_instance')]
    public function deleteNodepoolInstance(
        string $vkeId,
        string $nodepoolId,
        string $nodeId,
    ): array
    {
        $this->getClient()->delete('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/nodes/{nodeId');

        return ['success' => true];
    }

    /**
     * Recycle a NodePool Instance.
     * 
     * Recycle a specific NodePool Instance
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @param  string  $nodeId  Node ID
     * @return array<string, mixed>
     */
    #[McpTool(name: 'recycle_nodepool_instance')]
    public function recycleNodepoolInstance(
        string $vkeId,
        string $nodepoolId,
        string $nodeId,
    ): array
    {
        return $this->client->post('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/nodes/{nodeId/recycle');
    }

    /**
     * List NodePool Taints.
     * 
     * List NodePool Taints on Kubernetes Nodepool
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_nodepool_taints')]
    public function listNodepoolTaints(
        string $vkeId,
        string $nodepoolId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/taints');
    }

    /**
     * Create NodePool Taint.
     * 
     * Add NodePool Taint to Existing Kubernetes Nodepool
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_nodepool_taint')]
    public function createNodepoolTaint(
        string $vkeId,
        string $nodepoolId,
    ): array
    {
        return $this->client->post('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/taints');
    }

    /**
     * Delete NodePool Taint.
     * 
     * Delete NodePool Taint on Kubernetes Nodepool
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @param  string  $taintId  The NodePool Taint ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_nodepool_taint')]
    public function deleteNodepoolTaint(
        string $vkeId,
        string $nodepoolId,
        string $taintId,
    ): array
    {
        $this->getClient()->delete('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/taints/{taintId');

        return ['success' => true];
    }

    /**
     * Read NodePool Taint.
     * 
     * Read NodePool Taint on Kubernetes Nodepool
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $nodepoolId  The NodePool ID.
     * @param  string  $taintId  The NodePool Taint ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'read_nodepool_taint')]
    public function readNodepoolTaint(
        string $vkeId,
        string $nodepoolId,
        string $taintId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId/node-pools/{nodepoolId/taints/{taintId');
    }

    /**
     * Get Kubernetes Resources.
     * 
     * Get the block storage volumes and load balancers deployed by the specified Kubernetes cluster.
     * 
     * @param  string  $vkeId  The VKE ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_kubernetes_resources')]
    public function getKubernetesResources(
        string $vkeId,
    ): array
    {
        return $this->getClient()->get('/kubernetes/clusters/{vkeId/resources');
    }

    /**
     * Start Kubernetes Cluster Upgrade.
     * 
     * Start a Kubernetes cluster upgrade.
     * 
     * @param  string  $vkeId  The VKE ID.
     * @param  string  $upgradeVersion  The version you're upgrading to.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'start_kubernetes_cluster_upgrade')]
    public function startKubernetesClusterUpgrade(
        string $vkeId,
        string $upgradeVersion,
    ): array
    {
        return $this->client->post('/kubernetes/clusters/{vkeId/upgrades', [
            'upgrade_version' => $upgradeVersion,
        ]);
    }

    /**
     * Get Kubernetes Versions.
     * 
     * Get a list of supported Kubernetes versions
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_kubernetes_versions')]
    public function getKubernetesVersions(): array
    {
        return $this->getClient()->get('/kubernetes/versions');
    }

}