<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /load-balancers endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class LoadBalancerTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Load Balancers.
     * 
     * List the Load Balancers in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_load_balancers')]
    public function listLoadBalancers(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/load-balancers', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Load Balancer.
     * 
     * Create a new Load Balancer in a particular region.
     * 
     * @param  string|null  $region  The Region id to create this Load Balancer.
     * @param  string|null  $balancingAlgorithm  The balancing algorithm.

 roundrobin (default)
 leastconn
     * @param  bool|null  $sslRedirect  If true, this will redirect all HTTP traffic to HTTPS. You must have an HTTPS rule and SSL certificate installed on the load balancer to enable this option.

 true
 false
     * @param  bool|null  $http2  If true, this will enable HTTP2 traffic. You must have an HTTPS forwarding rule combo (HTTPS -> HTTPS) to enable this option.

 true
 false
     * @param  bool|null  $http3  If true, this will enable HTTP3/QUIC traffic. You must have HTTP2 enabled.

 true
 false
     * @param  int|null  $nodes  The number of nodes to add to the load balancer (1-99), must be an odd number. This defaults to 1.
     * @param  bool|null  $proxyProtocol  If true, you must configure backend nodes to accept Proxy protocol.

 true
 false (Default)
     * @param  int|null  $timeout  The maximum time allowed for the connection to remain inactive before timing out in seconds. This defaults to 600.
     * @param  array|null  $healthCheck  The health check configuration. See Load Balancer documentation.
     * @param  array|null  $forwardingRules  An array of forwarding rule objects.
     * @param  array|null  $stickySession  Enables sticky sessions for your load balancer when a cookie_name is provided.
     * @param  array|null  $ssl  An SSL certificate to install on the Load Balancer.
     * @param  string|null  $label  Label for your Load Balancer.
     * @param  array|null  $instances  An array of instances IDs that you want attached to the load balancer.
     * @param  array|null  $firewallRules  An array of firewall rule objects.
     * @param  string|null  $vpc  ID of the VPC you wish to use. If a VPC ID is omitted it will default to the public network.
     * @param  array|null  $autoSsl  The Auto SSL configuration. Must be using Vultr DNS for Auto SSL.
     * @param  array|null  $globalRegions  List of region objects with VPC information.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_load_balancer')]
    public function createLoadBalancer(
        ?string $region = null,
        ?string $balancingAlgorithm = null,
        ?bool $sslRedirect = null,
        ?bool $http2 = null,
        ?bool $http3 = null,
        ?int $nodes = null,
        ?bool $proxyProtocol = null,
        ?int $timeout = null,
        ?array $healthCheck = null,
        ?array $forwardingRules = null,
        ?array $stickySession = null,
        ?array $ssl = null,
        ?string $label = null,
        ?array $instances = null,
        ?array $firewallRules = null,
        ?string $vpc = null,
        ?array $autoSsl = null,
        ?array $globalRegions = null,
    ): array
    {
        return $this->client->post('/load-balancers', [
            'region' => $region,
            'balancing_algorithm' => $balancingAlgorithm,
            'ssl_redirect' => $sslRedirect,
            'http2' => $http2,
            'http3' => $http3,
            'nodes' => $nodes,
            'proxy_protocol' => $proxyProtocol,
            'timeout' => $timeout,
            'health_check' => $healthCheck,
            'forwarding_rules' => $forwardingRules,
            'sticky_session' => $stickySession,
            'ssl' => $ssl,
            'label' => $label,
            'instances' => $instances,
            'firewall_rules' => $firewallRules,
            'vpc' => $vpc,
            'auto_ssl' => $autoSsl,
            'global_regions' => $globalRegions,
        ]);
    }

    /**
     * Delete Load Balancer.
     * 
     * Delete a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_load_balancer')]
    public function deleteLoadBalancer(
        string $loadBalancerId,
    ): array
    {
        $this->getClient()->delete('/load-balancers/{loadBalancerId');

        return ['success' => true];
    }

    /**
     * Get Load Balancer.
     * 
     * Get information for a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_load_balancer')]
    public function getLoadBalancer(
        string $loadBalancerId,
    ): array
    {
        return $this->getClient()->get('/load-balancers/{loadBalancerId');
    }

    /**
     * Update Load Balancer.
     * 
     * Update information for a Load Balancer. All attributes are optional. If not set, the attributes will
     * retain their original values.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @param  array|null  $ssl  An SSL certificate to install on the Load Balancer.
     * @param  array|null  $stickySession  Enables sticky sessions for your load balancer when a cookie_name is provided.
     * @param  array|null  $forwardingRules  An array of forwarding rule objects.
     * @param  array|null  $healthCheck  The health check configuration. See Load Balancer documentation.
     * @param  bool|null  $proxyProtocol  If true, you must configure backend nodes to accept Proxy protocol.

 true
 false (Default)
     * @param  int|null  $timeout  The maximum time allowed for the connection to remain inactive before timing out in seconds. This defaults to 600.
     * @param  bool|null  $sslRedirect  If true, this will redirect all HTTP traffic to HTTPS. You must have an HTTPS rule and SSL certificate installed on the load balancer to enable this option.

 true
 false
     * @param  bool|null  $http2  If true, this will enable HTTP2 traffic. You must have an HTTPS forwarding rule combo (HTTPS -> HTTPS) to enable this option.

 true
 false
     * @param  bool|null  $http3  If true, this will enable HTTP3/QUIC traffic. You must have HTTP2 enabled.

 true
 false
     * @param  int|null  $nodes  The number of nodes to add to the load balancer (1-99), must be an odd number. This defaults to 1.
     * @param  string|null  $balancingAlgorithm  The balancing algorithm.

 roundrobin (default)
 leastconn
     * @param  array|null  $instances  Send the complete array of Instances IDs that should be attached to this Load Balancer. Instances will be attached or detached to match your array. For example, if Instances X, Y, and Z are currently attached, and you send [A,B,Z], then Instance A and B will be attached,  X and Y will be detached, and Z will remain attached.
     * @param  string|null  $label  The label for your Load Balancer
     * @param  string|null  $vpc  ID of the VPC you wish to use. If a VPC ID is omitted it will default to the public network.
     * @param  array|null  $firewallRules  An array of firewall rule objects.
     * @param  array|null  $autoSsl  The Auto SSL configuration. Must be using Vultr DNS for Auto SSL.
     * @param  array|null  $globalRegions  Array of Region ids to deploy child Load Balancers to.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_load_balancer')]
    public function updateLoadBalancer(
        string $loadBalancerId,
        ?array $ssl = null,
        ?array $stickySession = null,
        ?array $forwardingRules = null,
        ?array $healthCheck = null,
        ?bool $proxyProtocol = null,
        ?int $timeout = null,
        ?bool $sslRedirect = null,
        ?bool $http2 = null,
        ?bool $http3 = null,
        ?int $nodes = null,
        ?string $balancingAlgorithm = null,
        ?array $instances = null,
        ?string $label = null,
        ?string $vpc = null,
        ?array $firewallRules = null,
        ?array $autoSsl = null,
        ?array $globalRegions = null,
    ): array
    {
        return $this->client->patch('/load-balancers/{loadBalancerId', [
            'ssl' => $ssl,
            'sticky_session' => $stickySession,
            'forwarding_rules' => $forwardingRules,
            'health_check' => $healthCheck,
            'proxy_protocol' => $proxyProtocol,
            'timeout' => $timeout,
            'ssl_redirect' => $sslRedirect,
            'http2' => $http2,
            'http3' => $http3,
            'nodes' => $nodes,
            'balancing_algorithm' => $balancingAlgorithm,
            'instances' => $instances,
            'label' => $label,
            'vpc' => $vpc,
            'firewall_rules' => $firewallRules,
            'auto_ssl' => $autoSsl,
            'global_regions' => $globalRegions,
        ]);
    }

    /**
     * Disable Load Balancer Auto SSL.
     * 
     * Disable a Load Balancer Auto SSL. This will not remove an ssl certificate from the load balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_load_balancer_auto_ssl')]
    public function deleteLoadBalancerAutoSsl(
        string $loadBalancerId,
    ): array
    {
        $this->getClient()->delete('/load-balancers/{loadBalancerId/auto_ssl');

        return ['success' => true];
    }

    /**
     * List Forwarding Rules.
     * 
     * List the fowarding rules for a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_load_balancer_forwarding_rules')]
    public function listLoadBalancerForwardingRules(
        string $loadBalancerId,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/load-balancers/{loadBalancerId/forwarding-rules', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Forwarding Rule.
     * 
     * Create a new forwarding rule for a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @param  string  $frontendProtocol  The protocol on the Load Balancer to forward to the backend.

 HTTP
 HTTPS
 TCP
 UDP
     * @param  int  $frontendPort  The port number on the Load Balancer to forward to the backend.
     * @param  string  $backendProtocol  The protocol destination on the backend server.

 HTTP
 HTTPS
 TCP
 UDP
     * @param  int  $backendPort  The port number destination on the backend server.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_load_balancer_forwarding_rules')]
    public function createLoadBalancerForwardingRules(
        string $loadBalancerId,
        string $frontendProtocol,
        int $frontendPort,
        string $backendProtocol,
        int $backendPort,
    ): array
    {
        return $this->client->post('/load-balancers/{loadBalancerId/forwarding-rules', [
            'frontend_protocol' => $frontendProtocol,
            'frontend_port' => $frontendPort,
            'backend_protocol' => $backendProtocol,
            'backend_port' => $backendPort,
        ]);
    }

    /**
     * Delete Forwarding Rule.
     * 
     * Delete a Forwarding Rule on a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @param  string  $forwardingRuleId  The Forwarding Rule id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_load_balancer_forwarding_rule')]
    public function deleteLoadBalancerForwardingRule(
        string $loadBalancerId,
        string $forwardingRuleId,
    ): array
    {
        $this->getClient()->delete('/load-balancers/{loadBalancerId/forwarding-rules/{forwardingRuleId');

        return ['success' => true];
    }

    /**
     * Get Forwarding Rule.
     * 
     * Get information for a Forwarding Rule on a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @param  string  $forwardingRuleId  The Forwarding Rule id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_load_balancer_forwarding_rule')]
    public function getLoadBalancerForwardingRule(
        string $loadBalancerId,
        string $forwardingRuleId,
    ): array
    {
        return $this->getClient()->get('/load-balancers/{loadBalancerId/forwarding-rules/{forwardingRuleId');
    }

    /**
     * Delete Reverse DNS.
     * 
     * Delete a ipv6 reverse dns entry on a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_load_balancer_reverse_dns')]
    public function deleteLoadBalancerReverseDns(
        string $loadBalancerId,
    ): array
    {
        $this->getClient()->delete('/load-balancers/{loadBalancerId/reverse-dns');

        return ['success' => true];
    }

    /**
     * Get Reverse DNS.
     * 
     * Get Reverse DNS information for a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_load_balancer_reverse_dns')]
    public function getLoadBalancerReverseDns(
        string $loadBalancerId,
    ): array
    {
        return $this->getClient()->get('/load-balancers/{loadBalancerId/reverse-dns');
    }

    /**
     * Create Reverse DNS IPV6.
     * 
     * Create Reverse DNS (ipv6) for a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @param  array|null  $v6
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_load_balancer_reverse_dns_ipv6')]
    public function createLoadBalancerReverseDnsIpv6(
        string $loadBalancerId,
        ?array $v6 = null,
    ): array
    {
        return $this->client->post('/load-balancers/{loadBalancerId/reverse-dns', [
            'v6' => $v6,
        ]);
    }

    /**
     * Update Reverse DNS IPV4.
     * 
     * Update (ipv4) Reverse DNS for a Load Balancer.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @param  string|null  $v4  The Domain for the Reverse DNS Entry. If one exists it will be updated.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_load_balancer_reverse_dns_ipv4')]
    public function createLoadBalancerReverseDnsIpv4(
        string $loadBalancerId,
        ?string $v4 = null,
    ): array
    {
        return $this->client->put('/load-balancers/{loadBalancerId/reverse-dns', [
            'v4' => $v4,
        ]);
    }

    /**
     * Delete Load Balancer SSL.
     * 
     * Delete a Load Balancer SSL.
     * 
     * @param  string  $loadBalancerId  The Load Balancer id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_load_balancer_ssl')]
    public function deleteLoadBalancerSsl(
        string $loadBalancerId,
    ): array
    {
        $this->getClient()->delete('/load-balancers/{loadBalancerId/ssl');

        return ['success' => true];
    }

    /**
     * List Firewall Rules.
     * 
     * List the firewall rules for a Load Balancer.
     * 
     * @param  string  $loadbalancerId
     * @param  string|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_loadbalancer_firewall_rules')]
    public function listLoadbalancerFirewallRules(
        string $loadbalancerId,
        ?string $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/load-balancers/{loadbalancerId/firewall-rules', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Firewall Rules.
     * 
     * Create the firewall rules for a Load Balancer.
     * 
     * @param  string  $loadbalancerId
     * @param  array  $firewallRules  An array of firewall rule objects.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_loadbalancer_firewall_rules')]
    public function createLoadbalancerFirewallRules(
        string $loadbalancerId,
        array $firewallRules,
    ): array
    {
        return $this->client->post('/load-balancers/{loadbalancerId/firewall-rules', [
            'firewall_rules' => $firewallRules,
        ]);
    }

    /**
     * Delete Firewall Rule.
     * 
     * Delete a firewall rule for a Load Balancer.
     * 
     * @param  string  $loadbalancerId
     * @param  string  $firewallRuleId
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_loadbalancer_firewall_rule')]
    public function deleteLoadbalancerFirewallRule(
        string $loadbalancerId,
        string $firewallRuleId,
    ): array
    {
        $this->getClient()->delete('/load-balancers/{loadbalancerId/firewall-rules/{firewallRuleId');

        return ['success' => true];
    }

    /**
     * Get Firewall Rule.
     * 
     * Get a firewall rule for a Load Balancer.
     * 
     * @param  string  $loadbalancerId
     * @param  string  $firewallRuleId
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_loadbalancer_firewall_rule')]
    public function getLoadbalancerFirewallRule(
        string $loadbalancerId,
        string $firewallRuleId,
    ): array
    {
        return $this->getClient()->get('/load-balancers/{loadbalancerId/firewall-rules/{firewallRuleId');
    }

}