<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /logs endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class LogsTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Logs.
     * 
     * List the Logs for your account.
     * 
     * @param  string|null  $startTime  A UTC timestamp for the start of the time period from which to return logs. start_time is an inclusive endpoint. Logs with a timestamp equal to, or after start_time are included in the response<br>
<span style="color: red">This field is required if the end_time field is not provided.</span></br>
Expected Format: yyyy-mm-ddThh:mm:ssZ<br>
EX: 2025-06-26T00:00:00Z<br>
start_time must be after to the date added for start_time<br>
start_time and end_time may not be more than 30 days and 1 hour apart<br>
If no start_time is provided a time 30 days and 1 hour prior to the end_time will be used by default
     * @param  string|null  $endTime  A UTC timestamp for the end of the time period from which to return logs. end_time is an exclusive endpoint.  Only logs with a timestamp before the end_time are included in the response. <br>
<span style="color: red">This field is required if the start_time field is not provided.</span></br>
Expected Format: yyyy-mm-ddThh:mm:ssZ<br>
EX: 2025-06-26T00:00:00Z<br>
end_time must be before the date added for start_time<br>
start_time and end_time may not be more than 30 days and 1 hour apart<br>
If no end_time is provided the current time will be used  by default
     * @param  string|null  $logLevel  Filter the logs by the level assigned to the log.
 info
 debug
 warning
 error
* critical
     * @param  string|null  $resourceType  Filter the logs by the type of a resource such as an instances, bare-metals, kubernetes, etc.<br>
resource_type must be an exact match to the value of the resource type set in the log.
     * @param  string|null  $resourceId  Filter the logs by the UUID of a specific resource such as an instance.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_logs')]
    public function listLogs(
        ?string $startTime = null,
        ?string $endTime = null,
        ?string $logLevel = null,
        ?string $resourceType = null,
        ?string $resourceId = null,
    ): array
    {
        return $this->getClient()->get('/logs', [
            'start_time' => $startTime,
            'end_time' => $endTime,
            'log_level' => $logLevel,
            'resource_type' => $resourceType,
            'resource_id' => $resourceId,
        ]);
    }

}