<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /databases endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class ManagedDatabasesTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Managed Databases.
     * 
     * List all Managed Databases in your account.
     * 
     * @param  string|null  $label  Filter by label.
     * @param  string|null  $tag  Filter by specific tag.
     * @param  string|null  $region  Filter by Region id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_databases')]
    public function listDatabases(
        ?string $label = null,
        ?string $tag = null,
        ?string $region = null,
    ): array
    {
        return $this->getClient()->get('/databases', [
            'label' => $label,
            'tag' => $tag,
            'region' => $region,
        ]);
    }

    /**
     * Create Managed Database.
     * 
     * Create a new Managed Database in a region with the desired plan. Supply optional attributes as
     * desired.
     * 
     * @param  string  $databaseEngine  The database engine type for the Managed Database.
 mysql
 pg
 valkey
 kafka
     * @param  string  $databaseEngineVersion  The version of the chosen database engine type for the Managed Database.
 MySQL: 8
 PostgreSQL: 14 - 18
 Valkey: 8.1
 Kafka: 3.8 - 4.1
     * @param  string  $region  The Region id where the Managed Database is located.
     * @param  string  $plan  The Plan id to use when deploying this Managed Database.
     * @param  string  $label  A user-supplied label for this Managed Database.
     * @param  string|null  $tag  The user-supplied tag for this Managed Database.
     * @param  string|null  $vpcId  The VPC id to use when deploying this Managed Database. It can also be set to new to configure a new VPC network with this deployment.
     * @param  string|null  $maintenanceDow  The day of week for routine maintenance updates.
 monday
 tuesday
 wednesday
 thursday
 friday
 saturday
* sunday
     * @param  string|null  $maintenanceTime  The preferred time (UTC) for routine maintenance updates to occur in 24-hour HH:00 format (e.g. 01:00, 13:00, 23:00, etc.).
     * @param  string|null  $backupHour  The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
     * @param  string|null  $backupMinute  The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
     * @param  float|null  $pendingCharges  Charges due for this subscription at the end of the billing period.
     * @param  array|null  $trustedIps  A list of IP addresses allowed to access the Managed Database in CIDR notation (defaults to /32 if excluded).
     * @param  array|null  $mysqlSqlModes  A list of SQL modes to enable on the Managed Database (MySQL engine types only).
 ALLOW_INVALID_DATES
 ANSI (Combination Mode)
 ANSI_QUOTES
 ERROR_FOR_DIVISION_BY_ZERO
 HIGH_NOT_PRECEDENCE
 IGNORE_SPACE
 NO_AUTO_VALUE_ON_ZERO
 NO_DIR_IN_CREATE
 NO_ENGINE_SUBSTITUTION
 NO_UNSIGNED_SUBTRACTION
 NO_ZERO_DATE
 NO_ZERO_IN_DATE
 ONLY_FULL_GROUP_BY
 PIPES_AS_CONCAT
 REAL_AS_FLOAT
 STRICT_ALL_TABLES
 STRICT_TRANS_TABLES
 TIME_TRUNCATE_FRACTIONAL
* TRADITIONAL (Combination Mode)
     * @param  bool|null  $mysqlRequirePrimaryKey  Require a primary key for all tables on the Managed Database (MySQL engine types only).
     * @param  bool|null  $mysqlSlowQueryLog  Enable or disable slow query logging on the Managed Database (MySQL engine types only).
     * @param  int|null  $mysqlLongQueryTime  The number of seconds to denote a slow query when logging is enabled (MySQL engine types only).
     * @param  string|null  $evictionPolicy  Set the data eviction policy for the Managed Database (Valkey engine types only)
     * @param  bool|null  $enableKafkaRest  Enable or disable Kafka REST support on the Managed Database (Kafka engine types only on business plans or higher).
     * @param  bool|null  $enableSchemaRegistry  Enable or disable Schema Registry support on the Managed Database (Kafka engine types only on business plans or higher).
     * @param  bool|null  $enableKafkaConnect  Enable or disable Kafka Connect support on the Managed Database (Kafka engine types only on business plans or higher).
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_database')]
    public function createDatabase(
        string $databaseEngine,
        string $databaseEngineVersion,
        string $region,
        string $plan,
        string $label,
        ?string $tag = null,
        ?string $vpcId = null,
        ?string $maintenanceDow = null,
        ?string $maintenanceTime = null,
        ?string $backupHour = null,
        ?string $backupMinute = null,
        ?float $pendingCharges = null,
        ?array $trustedIps = null,
        ?array $mysqlSqlModes = null,
        ?bool $mysqlRequirePrimaryKey = null,
        ?bool $mysqlSlowQueryLog = null,
        ?int $mysqlLongQueryTime = null,
        ?string $evictionPolicy = null,
        ?bool $enableKafkaRest = null,
        ?bool $enableSchemaRegistry = null,
        ?bool $enableKafkaConnect = null,
    ): array
    {
        return $this->client->post('/databases', [
            'database_engine' => $databaseEngine,
            'database_engine_version' => $databaseEngineVersion,
            'region' => $region,
            'plan' => $plan,
            'label' => $label,
            'tag' => $tag,
            'vpc_id' => $vpcId,
            'maintenance_dow' => $maintenanceDow,
            'maintenance_time' => $maintenanceTime,
            'backup_hour' => $backupHour,
            'backup_minute' => $backupMinute,
            'pending_charges' => $pendingCharges,
            'trusted_ips' => $trustedIps,
            'mysql_sql_modes' => $mysqlSqlModes,
            'mysql_require_primary_key' => $mysqlRequirePrimaryKey,
            'mysql_slow_query_log' => $mysqlSlowQueryLog,
            'mysql_long_query_time' => $mysqlLongQueryTime,
            'eviction_policy' => $evictionPolicy,
            'enable_kafka_rest' => $enableKafkaRest,
            'enable_schema_registry' => $enableSchemaRegistry,
            'enable_kafka_connect' => $enableKafkaConnect,
        ]);
    }

    /**
     * Get Available Services.
     * 
     * Get a list of available services
     * @return array<string, mixed>
     */
    #[McpTool(name: 'available_services')]
    public function availableServices(): array
    {
        return $this->getClient()->get('/databases/available-services');
    }

    /**
     * List Managed Database Plans.
     * 
     * List all Managed Databases plans.
     * 
     * @param  string|null  $engine  Filter by engine type

 mysql
 pg
 valkey
 kafka
     * @param  int|null  $nodes  Filter by number of nodes.
     * @param  string|null  $region  Filter by Region id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_database_plans')]
    public function listDatabasePlans(
        ?string $engine = null,
        ?int $nodes = null,
        ?string $region = null,
    ): array
    {
        return $this->getClient()->get('/databases/plans', [
            'engine' => $engine,
            'nodes' => $nodes,
            'region' => $region,
        ]);
    }

    /**
     * Delete Managed Database.
     * 
     * Delete a Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_database')]
    public function deleteDatabase(
        string $databaseId,
    ): array
    {
        $this->getClient()->delete('/databases/{databaseId');

        return ['success' => true];
    }

    /**
     * Get Managed Database.
     * 
     * Get information about a Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_database')]
    public function getDatabase(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId');
    }

    /**
     * Update Managed Database.
     * 
     * Update information for a Managed Database. All attributes are optional. If not set, the attributes
     * will retain their original values.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string|null  $region  The Region id where the Managed Database is located.
     * @param  string|null  $plan  The Plan id for this Managed Database.
     * @param  string|null  $label  A user-supplied label for this Managed Database.
     * @param  string|null  $tag  The user-supplied tag for this Managed Database.
     * @param  string|null  $vpcId  The VPC id for this Managed Database.
     * @param  string|null  $maintenanceDow  The day of week for routine maintenance updates.
 monday
 tuesday
 wednesday
 thursday
 friday
 saturday
* sunday
     * @param  string|null  $maintenanceTime  The preferred time (UTC) for routine maintenance updates to occur in 24-hour HH:00 format (e.g. 01:00, 13:00, 23:00, etc.).
     * @param  string|null  $backupHour  The preferred hour of the day (UTC) for daily backups to take place (unavailable for Kafka engine types).
     * @param  string|null  $backupMinute  The preferred minute of the backup hour for daily backups to take place (unavailable for Kafka engine types).
     * @param  float|null  $pendingCharges  Charges due for this subscription at the end of the billing period.
     * @param  string|null  $clusterTimeZone  The configured time zone for the Managed Database in TZ database format (e.g. UTC, America/New_York, Europe/London, etc.).
     * @param  array|null  $trustedIps  A list of IP addresses allowed to access the Managed Database in CIDR notation (defaults to /32 if excluded).
     * @param  array|null  $mysqlSqlModes  A list of SQL modes to enable on the Managed Database (MySQL engine types only).
 ALLOW_INVALID_DATES
 ANSI (Combination Mode)
 ANSI_QUOTES
 ERROR_FOR_DIVISION_BY_ZERO
 HIGH_NOT_PRECEDENCE
 IGNORE_SPACE
 NO_AUTO_VALUE_ON_ZERO
 NO_DIR_IN_CREATE
 NO_ENGINE_SUBSTITUTION
 NO_UNSIGNED_SUBTRACTION
 NO_ZERO_DATE
 NO_ZERO_IN_DATE
 ONLY_FULL_GROUP_BY
 PIPES_AS_CONCAT
 REAL_AS_FLOAT
 STRICT_ALL_TABLES
 STRICT_TRANS_TABLES
 TIME_TRUNCATE_FRACTIONAL
* TRADITIONAL (Combination Mode)
     * @param  bool|null  $mysqlRequirePrimaryKey  Require a primary key for all tables on the Managed Database (MySQL engine types only).
     * @param  bool|null  $mysqlSlowQueryLog  Enable or disable slow query logging on the Managed Database (MySQL engine types only).
     * @param  int|null  $mysqlLongQueryTime  The number of seconds to denote a slow query when logging is enabled (MySQL engine types only).
     * @param  string|null  $evictionPolicy  Set the data eviction policy for the Managed Database (Valkey engine types only)
     * @param  bool|null  $enableKafkaRest  Enable or disable Kafka REST support on the Managed Database (Kafka engine types only on business plans or higher).
     * @param  bool|null  $enableSchemaRegistry  Enable or disable Schema Registry support on the Managed Database (Kafka engine types only on business plans or higher).
     * @param  bool|null  $enableKafkaConnect  Enable or disable Kafka Connect support on the Managed Database (Kafka engine types only on business plans or higher).
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_database')]
    public function updateDatabase(
        string $databaseId,
        ?string $region = null,
        ?string $plan = null,
        ?string $label = null,
        ?string $tag = null,
        ?string $vpcId = null,
        ?string $maintenanceDow = null,
        ?string $maintenanceTime = null,
        ?string $backupHour = null,
        ?string $backupMinute = null,
        ?float $pendingCharges = null,
        ?string $clusterTimeZone = null,
        ?array $trustedIps = null,
        ?array $mysqlSqlModes = null,
        ?bool $mysqlRequirePrimaryKey = null,
        ?bool $mysqlSlowQueryLog = null,
        ?int $mysqlLongQueryTime = null,
        ?string $evictionPolicy = null,
        ?bool $enableKafkaRest = null,
        ?bool $enableSchemaRegistry = null,
        ?bool $enableKafkaConnect = null,
    ): array
    {
        return $this->client->put('/databases/{databaseId', [
            'region' => $region,
            'plan' => $plan,
            'label' => $label,
            'tag' => $tag,
            'vpc_id' => $vpcId,
            'maintenance_dow' => $maintenanceDow,
            'maintenance_time' => $maintenanceTime,
            'backup_hour' => $backupHour,
            'backup_minute' => $backupMinute,
            'pending_charges' => $pendingCharges,
            'cluster_time_zone' => $clusterTimeZone,
            'trusted_ips' => $trustedIps,
            'mysql_sql_modes' => $mysqlSqlModes,
            'mysql_require_primary_key' => $mysqlRequirePrimaryKey,
            'mysql_slow_query_log' => $mysqlSlowQueryLog,
            'mysql_long_query_time' => $mysqlLongQueryTime,
            'eviction_policy' => $evictionPolicy,
            'enable_kafka_rest' => $enableKafkaRest,
            'enable_schema_registry' => $enableSchemaRegistry,
            'enable_kafka_connect' => $enableKafkaConnect,
        ]);
    }

    /**
     * List Advanced Options.
     * 
     * List all configured and available advanced options for the Managed Database (MySQL, PostgreSQL, and
     * Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_advanced_options')]
    public function listAdvancedOptions(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/advanced-options');
    }

    /**
     * Update Advanced Options.
     * 
     * Updates an advanced configuration option for the Managed Database (MySQL, PostgreSQL, and Kafka
     * engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_advanced_options')]
    public function updateAdvancedOptions(
        string $databaseId,
    ): array
    {
        return $this->client->put('/databases/{databaseId/advanced-options');
    }

    /**
     * List Kafka Connect Advanced Options.
     * 
     * List all configured and available Kafka Connect advanced options for the Managed Database (Kafka
     * engine types only on business plans or higher).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_advanced_options_kafka_connect')]
    public function listAdvancedOptionsKafkaConnect(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/advanced-options/kafka-connect');
    }

    /**
     * Update Kafka Connect Advanced Options.
     * 
     * Updates a Kafka Connect advanced configuration option for the Managed Database (Kafka engine types
     * only on business plans or higher).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_advanced_options_kafka_connect')]
    public function updateAdvancedOptionsKafkaConnect(
        string $databaseId,
    ): array
    {
        return $this->client->put('/databases/{databaseId/advanced-options/kafka-connect');
    }

    /**
     * List Kafka REST Advanced Options.
     * 
     * List all configured and available Kafka REST advanced options for the Managed Database (Kafka engine
     * types only on business plans or higher).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_advanced_options_kafka_rest')]
    public function listAdvancedOptionsKafkaRest(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/advanced-options/kafka-rest');
    }

    /**
     * Update Kafka REST Advanced Options.
     * 
     * Updates a Kafka REST advanced configuration option for the Managed Database (Kafka engine types only
     * on business plans or higher).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_advanced_options_kafka_rest')]
    public function updateAdvancedOptionsKafkaRest(
        string $databaseId,
    ): array
    {
        return $this->client->put('/databases/{databaseId/advanced-options/kafka-rest');
    }

    /**
     * List Schema Registry Advanced Options.
     * 
     * List all configured and available Schema Registry advanced options for the Managed Database (Kafka
     * engine types only on business plans or higher).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_advanced_options_schema_registry')]
    public function listAdvancedOptionsSchemaRegistry(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/advanced-options/schema-registry');
    }

    /**
     * Update Schema Registry Advanced Options.
     * 
     * Updates a Schema Registry advanced configuration option for the Managed Database (Kafka engine types
     * only on business plans or higher).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_advanced_options_schema_registry')]
    public function updateAdvancedOptionsSchemaRegistry(
        string $databaseId,
    ): array
    {
        return $this->client->put('/databases/{databaseId/advanced-options/schema-registry');
    }

    /**
     * List Service Alerts.
     * 
     * List service alert messages for the Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $period  The time range to list Managed Database service alerts from.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_service_alerts')]
    public function listServiceAlerts(
        string $databaseId,
        string $period,
    ): array
    {
        return $this->client->post('/databases/{databaseId/alerts', [
            'period' => $period,
        ]);
    }

    /**
     * List Database Available Connectors.
     * 
     * List all available connectors for the Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_database_available_connectors')]
    public function listDatabaseAvailableConnectors(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/available-connectors');
    }

    /**
     * Get Database Connector Configuration Schema.
     * 
     * Get the configuration schema for the Managed Database connector (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $connectorClass  The database connector's identifying class.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_database_connector_configuration_schema')]
    public function getDatabaseConnectorConfigurationSchema(
        string $databaseId,
        string $connectorClass,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/available-connectors/{connectorClass/configuration');
    }

    /**
     * Get Backup Information.
     * 
     * Get backup information for the Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_backup_information')]
    public function getBackupInformation(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/backups');
    }

    /**
     * List Connection Pools.
     * 
     * List all connection pools within the Managed Database (PostgreSQL engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_connection_pools')]
    public function listConnectionPools(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/connection-pools');
    }

    /**
     * Create Connection Pool.
     * 
     * Create a new connection pool within the Managed Database (PostgreSQL engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $name  The name of the connection pool.
     * @param  string  $database  The logical database associated with the connection pool.
     * @param  string  $username  The database user associated with the connection pool.
     * @param  string  $mode  The mode for the connection pool.
 session
 transaction
* statement
     * @param  int  $size  The size of the connection pool.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_connection_pool')]
    public function createConnectionPool(
        string $databaseId,
        string $name,
        string $database,
        string $username,
        string $mode,
        int $size,
    ): array
    {
        return $this->client->post('/databases/{databaseId/connection-pools', [
            'name' => $name,
            'database' => $database,
            'username' => $username,
            'mode' => $mode,
            'size' => $size,
        ]);
    }

    /**
     * Delete Connection Pool.
     * 
     * Delete a connection pool within a Managed Database (PostgreSQL engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $poolName  The connection pool name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_connection_pool')]
    public function deleteConnectionPool(
        string $databaseId,
        string $poolName,
    ): array
    {
        $this->getClient()->delete('/databases/{databaseId/connection-pools/{poolName');

        return ['success' => true];
    }

    /**
     * Get Connection Pool.
     * 
     * Get information about a Managed Database connection pool (PostgreSQL engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $poolName  The connection pool name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_connection_pool')]
    public function getConnectionPool(
        string $databaseId,
        string $poolName,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/connection-pools/{poolName');
    }

    /**
     * Update Connection Pool.
     * 
     * Update connection-pool information within a Managed Database (PostgreSQL engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $poolName  The connection pool name.
     * @param  string|null  $database  The logical database associated with the connection pool.
     * @param  string|null  $username  The database user associated with the connection pool.
     * @param  string|null  $mode  The mode for the connection pool.
 session
 transaction
* statement
     * @param  int|null  $size  The size of the connection pool.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_connection_pool')]
    public function updateConnectionPool(
        string $databaseId,
        string $poolName,
        ?string $database = null,
        ?string $username = null,
        ?string $mode = null,
        ?int $size = null,
    ): array
    {
        return $this->client->put('/databases/{databaseId/connection-pools/{poolName', [
            'database' => $database,
            'username' => $username,
            'mode' => $mode,
            'size' => $size,
        ]);
    }

    /**
     * List Database Connectors.
     * 
     * List all connectors within the Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_database_connectors')]
    public function listDatabaseConnectors(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/connectors');
    }

    /**
     * Create Database Connector.
     * 
     * Create a new connector within the Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $name  The name for the database connector.
     * @param  string  $class  The class for the database connector.
     * @param  string  $topics  A comma-separated list of topics to use with the database connector.
     * @param  array|null  $config  A JSON object containing the configuration properties you wish to use with this database connector. See Get Database Connector Configuration Schema for a list of available/required options for a connector.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_database_connector')]
    public function createDatabaseConnector(
        string $databaseId,
        string $name,
        string $class,
        string $topics,
        ?array $config = null,
    ): array
    {
        return $this->client->post('/databases/{databaseId/connectors', [
            'name' => $name,
            'class' => $class,
            'topics' => $topics,
            'config' => $config,
        ]);
    }

    /**
     * Delete Database Connector.
     * 
     * Delete a connector within a Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $connectorName  The database connector's name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_database_connector')]
    public function deleteDatabaseConnector(
        string $databaseId,
        string $connectorName,
    ): array
    {
        $this->getClient()->delete('/databases/{databaseId/connectors/{connectorName');

        return ['success' => true];
    }

    /**
     * Get Database Connector.
     * 
     * Get information about a Managed Database connector (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $connectorName  The database connector's name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_database_connector')]
    public function getDatabaseConnector(
        string $databaseId,
        string $connectorName,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/connectors/{connectorName');
    }

    /**
     * Update Database Connector.
     * 
     * Update connector information within a Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $connectorName  The database connector's name.
     * @param  string|null  $topics  A comma-separated list of topics to use with the database connector.
     * @param  array|null  $config  A JSON object containing the configuration properties you wish to use with this database connector. See Get Database Connector Configuration Schema for a list of available/required options for a connector. Updating this will replace the entire configuration object currently set.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_database_connector')]
    public function updateDatabaseConnector(
        string $databaseId,
        string $connectorName,
        ?string $topics = null,
        ?array $config = null,
    ): array
    {
        return $this->client->put('/databases/{databaseId/connectors/{connectorName', [
            'topics' => $topics,
            'config' => $config,
        ]);
    }

    /**
     * Pause Database Connector.
     * 
     * Pause a connector within a Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $connectorName  The database connector's name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'pause_database_connector')]
    public function pauseDatabaseConnector(
        string $databaseId,
        string $connectorName,
    ): array
    {
        return $this->client->post('/databases/{databaseId/connectors/{connectorName/pause');
    }

    /**
     * Restart Database Connector.
     * 
     * Restart a connector within a Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $connectorName  The database connector's name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'restart_database_connector')]
    public function restartDatabaseConnector(
        string $databaseId,
        string $connectorName,
    ): array
    {
        return $this->client->post('/databases/{databaseId/connectors/{connectorName/restart');
    }

    /**
     * Resume Database Connector.
     * 
     * Resume a paused connector within a Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $connectorName  The database connector's name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'resume_database_connector')]
    public function resumeDatabaseConnector(
        string $databaseId,
        string $connectorName,
    ): array
    {
        return $this->client->post('/databases/{databaseId/connectors/{connectorName/resume');
    }

    /**
     * Get Database Connector Status.
     * 
     * Get status information about a Managed Database connector (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $connectorName  The database connector's name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_database_connector_status')]
    public function getDatabaseConnectorStatus(
        string $databaseId,
        string $connectorName,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/connectors/{connectorName/status');
    }

    /**
     * Restart Database Connector Task.
     * 
     * Restart a task within a Managed Database connector (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $connectorName  The database connector's name.
     * @param  string  $taskId  The connector task's ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'restart_database_connector_task')]
    public function restartDatabaseConnectorTask(
        string $databaseId,
        string $connectorName,
        string $taskId,
    ): array
    {
        return $this->client->post('/databases/{databaseId/connectors/{connectorName/tasks/{taskId/restart');
    }

    /**
     * List Logical Databases.
     * 
     * List all logical databases within the Managed Database (MySQL and PostgreSQL only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_database_dbs')]
    public function listDatabaseDbs(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/dbs');
    }

    /**
     * Create Logical Database.
     * 
     * Create a new logical database within the Managed Database (MySQL and PostgreSQL only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $name  The name of the logical database.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_database_db')]
    public function createDatabaseDb(
        string $databaseId,
        string $name,
    ): array
    {
        return $this->client->post('/databases/{databaseId/dbs', [
            'name' => $name,
        ]);
    }

    /**
     * Delete Logical Database.
     * 
     * Delete a logical database within a Managed Database (MySQL and PostgreSQL only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $dbName  The logical database name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_database_db')]
    public function deleteDatabaseDb(
        string $databaseId,
        string $dbName,
    ): array
    {
        $this->getClient()->delete('/databases/{databaseId/dbs/{dbName');

        return ['success' => true];
    }

    /**
     * Get Logical Database.
     * 
     * Get information about a logical database within a Managed Database (MySQL and PostgreSQL only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $dbName  The logical database name.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_database_db')]
    public function getDatabaseDb(
        string $databaseId,
        string $dbName,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/dbs/{dbName');
    }

    /**
     * Fork Managed Database.
     * 
     * Fork a Managed Database to a new subscription from a backup.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $label  A user-supplied label for this Managed Database.
     * @param  string  $region  The Region id where the Managed Database is located.
     * @param  string  $plan  The Plan id to use when deploying this Managed Database.
     * @param  string|null  $vpcId  The VPC id to use when deploying this Managed Database. It can also be set to new to configure a new VPC network with this deployment.
     * @param  string|null  $type  The type of backup restoration to use for this Managed Database.
 pitr: Point-in-time recovery
 basebackup: Latest backup (default if omitted)
     * @param  string|null  $date  The backup date to use when restoring the Managed Database in YYYY-MM-DD date format. Required for pitr type requests.
     * @param  string|null  $time  The backup time to use when restoring the Managed Database in HH-MM-SS time format (24-hour UTC). Required for pitr type requests.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'database_fork')]
    public function databaseFork(
        string $databaseId,
        string $label,
        string $region,
        string $plan,
        ?string $vpcId = null,
        ?string $type = null,
        ?string $date = null,
        ?string $time = null,
    ): array
    {
        return $this->client->post('/databases/{databaseId/fork', [
            'label' => $label,
            'region' => $region,
            'plan' => $plan,
            'vpc_id' => $vpcId,
            'type' => $type,
            'date' => $date,
            'time' => $time,
        ]);
    }

    /**
     * List Maintenance Updates.
     * 
     * List all available maintenance updates within the Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_maintenance_updates')]
    public function listMaintenanceUpdates(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/maintenance');
    }

    /**
     * Start Maintenance Updates.
     * 
     * Start maintenance updates for the Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'start_maintenance_updates')]
    public function startMaintenanceUpdates(
        string $databaseId,
    ): array
    {
        return $this->client->post('/databases/{databaseId/maintenance');
    }

    /**
     * Detach Migration.
     * 
     * Detach a migration from the Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'database_detach_migration')]
    public function databaseDetachMigration(
        string $databaseId,
    ): array
    {
        $this->getClient()->delete('/databases/{databaseId/migration');

        return ['success' => true];
    }

    /**
     * Get Migration Status.
     * 
     * View the status of a migration attached to the Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'view_migration_status')]
    public function viewMigrationStatus(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/migration');
    }

    /**
     * Start Migration.
     * 
     * Start a migration to the Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $host  The host name of the source server.
     * @param  int  $port  The connection port of the source server.
     * @param  string  $username  The username of the source server. Uses default for Valkey if left empty or unset.
     * @param  string  $password  The password of the source server.
     * @param  string|null  $database  The database of the source server. Required for MySQL/PostgreSQL engine types, but excluded for Valkey.
     * @param  string|null  $ignoredDatabases  Comma-separated list of ignored databases on the source server. Excluded for Valkey engine types.
     * @param  bool  $ssl  The true/false value for whether SSL is needed to connect to the source server.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'database_start_migration')]
    public function databaseStartMigration(
        string $databaseId,
        string $host,
        int $port,
        string $username,
        string $password,
        bool $ssl,
        ?string $database = null,
        ?string $ignoredDatabases = null,
    ): array
    {
        return $this->client->post('/databases/{databaseId/migration', [
            'host' => $host,
            'port' => $port,
            'username' => $username,
            'password' => $password,
            'database' => $database,
            'ignored_databases' => $ignoredDatabases,
            'ssl' => $ssl,
        ]);
    }

    /**
     * Promote Read-Only Replica.
     * 
     * Promote a read-only replica node to its own primary Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'database_promote_read_replica')]
    public function databasePromoteReadReplica(
        string $databaseId,
    ): array
    {
        return $this->client->post('/databases/{databaseId/promote-read-replica');
    }

    /**
     * List Database Quotas.
     * 
     * List all quotas within the Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_database_quotas')]
    public function listDatabaseQuotas(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/quotas');
    }

    /**
     * Create Database Quota.
     * 
     * Create a new quota within the Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $clientId  The client ID for the database quota. Note: Creating a new quota with the same client ID and user will overwrite the previous record.
     * @param  string  $user  The user for the database quota.
     * @param  int  $consumerByteRate  The consumer byte rate for the database quota.
     * @param  int  $producerByteRate  The producer byte rate for the database quota.
     * @param  int  $requestPercentage  The CPU request percentage for the database quota.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_database_quota')]
    public function createDatabaseQuota(
        string $databaseId,
        string $clientId,
        string $user,
        int $consumerByteRate,
        int $producerByteRate,
        int $requestPercentage,
    ): array
    {
        return $this->client->post('/databases/{databaseId/quotas', [
            'client_id' => $clientId,
            'user' => $user,
            'consumer_byte_rate' => $consumerByteRate,
            'producer_byte_rate' => $producerByteRate,
            'request_percentage' => $requestPercentage,
        ]);
    }

    /**
     * Delete Database Quota.
     * 
     * Delete a quota within a Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $clientId  The database quota's client ID.
     * @param  string  $username  The database quota's user.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_database_quota')]
    public function deleteDatabaseQuota(
        string $databaseId,
        string $clientId,
        string $username,
    ): array
    {
        $this->getClient()->delete('/databases/{databaseId/quotas/{clientId/{username');

        return ['success' => true];
    }

    /**
     * Get Database Quota.
     * 
     * Get information about a Managed Database quota (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $clientId  The database quota's client ID.
     * @param  string  $username  The database quota's user.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_database_quota')]
    public function getDatabaseQuota(
        string $databaseId,
        string $clientId,
        string $username,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/quotas/{clientId/{username');
    }

    /**
     * Update Database Quota.
     * 
     * Update quota information within a Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $clientId  The database quota's client ID.
     * @param  string  $username  The database quota's user.
     * @param  int  $consumerByteRate  The consumer byte rate for the database quota.
     * @param  int  $producerByteRate  The producer byte rate for the database quota.
     * @param  int  $requestPercentage  The CPU request percentage for the database quota.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_database_quota')]
    public function updateDatabaseQuota(
        string $databaseId,
        string $clientId,
        string $username,
        int $consumerByteRate,
        int $producerByteRate,
        int $requestPercentage,
    ): array
    {
        return $this->client->put('/databases/{databaseId/quotas/{clientId/{username', [
            'consumer_byte_rate' => $consumerByteRate,
            'producer_byte_rate' => $producerByteRate,
            'request_percentage' => $requestPercentage,
        ]);
    }

    /**
     * Add Read-Only Replica.
     * 
     * Create a read-only replica node for the Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $region  The Region id where the Managed Database is located.
     * @param  string  $label  A user-supplied label for this Managed Database.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'database_add_read_replica')]
    public function databaseAddReadReplica(
        string $databaseId,
        string $region,
        string $label,
    ): array
    {
        return $this->client->post('/databases/{databaseId/read-replica', [
            'region' => $region,
            'label' => $label,
        ]);
    }

    /**
     * Restore from Backup.
     * 
     * Create a new Managed Database from a backup.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $label  A user-supplied label for this Managed Database.
     * @param  string|null  $type  The type of backup restoration to use for this Managed Database.
 pitr: Point-in-time recovery
 basebackup: Latest backup (default if omitted)
     * @param  string|null  $date  The backup date to use when restoring the Managed Database in YYYY-MM-DD date format. Required for pitr type requests.
     * @param  string|null  $time  The backup time to use when restoring the Managed Database in HH-MM-SS time format (24-hour UTC). Required for pitr type requests.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'database_restore_from_backup')]
    public function databaseRestoreFromBackup(
        string $databaseId,
        string $label,
        ?string $type = null,
        ?string $date = null,
        ?string $time = null,
    ): array
    {
        return $this->client->post('/databases/{databaseId/restore', [
            'label' => $label,
            'type' => $type,
            'date' => $date,
            'time' => $time,
        ]);
    }

    /**
     * List Database Topics.
     * 
     * List all topics within the Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_database_topics')]
    public function listDatabaseTopics(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/topics');
    }

    /**
     * Create Database Topic.
     * 
     * Create a new topic within the Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $name  The name for the database topic.
     * @param  int  $partitions  The number of partitions for the database topic.
     * @param  int  $replication  The replication factor for the database topic.
     * @param  int  $retentionHours  The retention hours for the database topic.
     * @param  int  $retentionBytes  The retention bytes for the database topic.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_database_topic')]
    public function createDatabaseTopic(
        string $databaseId,
        string $name,
        int $partitions,
        int $replication,
        int $retentionHours,
        int $retentionBytes,
    ): array
    {
        return $this->client->post('/databases/{databaseId/topics', [
            'name' => $name,
            'partitions' => $partitions,
            'replication' => $replication,
            'retention_hours' => $retentionHours,
            'retention_bytes' => $retentionBytes,
        ]);
    }

    /**
     * Delete Database Topic.
     * 
     * Delete a topic within a Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $topicName  The database topic.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_database_topic')]
    public function deleteDatabaseTopic(
        string $databaseId,
        string $topicName,
    ): array
    {
        $this->getClient()->delete('/databases/{databaseId/topics/{topicName');

        return ['success' => true];
    }

    /**
     * Get Database Topic.
     * 
     * Get information about a Managed Database topic (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $topicName  The database topic.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_database_topic')]
    public function getDatabaseTopic(
        string $databaseId,
        string $topicName,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/topics/{topicName');
    }

    /**
     * Update Database Topic.
     * 
     * Update topic information within a Managed Database (Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $topicName  The database topic.
     * @param  int|null  $partitions  The number of partitions for the database topic.
     * @param  int|null  $replication  The replication factor for the database topic.
     * @param  int|null  $retentionHours  The retention hours for the database topic.
     * @param  int|null  $retentionBytes  The retention bytes for the database topic.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_database_topic')]
    public function updateDatabaseTopic(
        string $databaseId,
        string $topicName,
        ?int $partitions = null,
        ?int $replication = null,
        ?int $retentionHours = null,
        ?int $retentionBytes = null,
    ): array
    {
        return $this->client->put('/databases/{databaseId/topics/{topicName', [
            'partitions' => $partitions,
            'replication' => $replication,
            'retention_hours' => $retentionHours,
            'retention_bytes' => $retentionBytes,
        ]);
    }

    /**
     * Get Database Usage Information.
     * 
     * Get disk, memory, and vCPU usage information for a Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_database_usage')]
    public function getDatabaseUsage(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/usage');
    }

    /**
     * List Database Users.
     * 
     * List all database users within the Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_database_users')]
    public function listDatabaseUsers(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/users');
    }

    /**
     * Create Database User.
     * 
     * Create a new database user within the Managed Database. Supply optional attributes as desired.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $username  The username of the database user.
     * @param  string|null  $password  The password for the database user. This can be omitted to auto-generate a secure password.
     * @param  string|null  $encryption  The password encryption type for the database user (MySQL engine types only).
 caching_sha2_password (default if omitted)
 mysql_native_password
     * @param  string|null  $permission  The permission level for the database user (Kafka engine types only).
 admin
 read
 write
 readwrite
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_database_user')]
    public function createDatabaseUser(
        string $databaseId,
        string $username,
        ?string $password = null,
        ?string $encryption = null,
        ?string $permission = null,
    ): array
    {
        return $this->client->post('/databases/{databaseId/users', [
            'username' => $username,
            'password' => $password,
            'encryption' => $encryption,
            'permission' => $permission,
        ]);
    }

    /**
     * Delete Database User.
     * 
     * Delete a database user within a Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $username  The database user.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_database_user')]
    public function deleteDatabaseUser(
        string $databaseId,
        string $username,
    ): array
    {
        $this->getClient()->delete('/databases/{databaseId/users/{username');

        return ['success' => true];
    }

    /**
     * Get Database User.
     * 
     * Get information about a Managed Database user.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $username  The database user.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_database_user')]
    public function getDatabaseUser(
        string $databaseId,
        string $username,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/users/{username');
    }

    /**
     * Update Database User.
     * 
     * Update database user information within a Managed Database.
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $username  The database user.
     * @param  string  $password  The password for the database user. This can be empty to auto-generate a new secure password.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_database_user')]
    public function updateDatabaseUser(
        string $databaseId,
        string $username,
        string $password,
    ): array
    {
        return $this->client->put('/databases/{databaseId/users/{username', [
            'password' => $password,
        ]);
    }

    /**
     * Set Database User Access Control.
     * 
     * Configure access control settings for a Managed Database user (Valkey and Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $username  The database user.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'set_database_user_acl')]
    public function setDatabaseUserAcl(
        string $databaseId,
        string $username,
    ): array
    {
        return $this->client->put('/databases/{databaseId/users/{username/access-control');
    }

    /**
     * List Available Versions.
     * 
     * List all available version upgrades within the Managed Database (PostgreSQL and Kafka engine types
     * only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_available_versions')]
    public function listAvailableVersions(
        string $databaseId,
    ): array
    {
        return $this->getClient()->get('/databases/{databaseId/version-upgrade');
    }

    /**
     * Start Version Upgrade.
     * 
     * Start a version upgrade for the Managed Database (PostgreSQL and Kafka engine types only).
     * 
     * @param  string  $databaseId  The Managed Database ID.
     * @param  string  $version  The version number to upgrade the Managed Database to.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'start_version_upgrade')]
    public function startVersionUpgrade(
        string $databaseId,
        string $version,
    ): array
    {
        return $this->client->post('/databases/{databaseId/version-upgrade', [
            'version' => $version,
        ]);
    }

}