<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /marketplace endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class MarketplaceTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Marketplace Apps.
     * 
     * List all Marketplace Apps owned by the authenticated vendor account.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_marketplace_apps')]
    public function listMarketplaceApps(): array
    {
        return $this->getClient()->get('/marketplace/apps');
    }

    /**
     * List Marketplace App Variables.
     * 
     * List all user-supplied variables for a Marketplace App.
     * 
     * @param  string  $imageId  The application's Image ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_marketplace_app_variables')]
    public function listMarketplaceAppVariables(
        string $imageId,
    ): array
    {
        return $this->getClient()->get('/marketplace/apps/{imageId/variables');
    }

}