<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /v2/oidc endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class OidcTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * OIDC Authorization Endpoint.
     * 
     * Initiate an OIDC authorization flow.
     * 
     * @param  string|null  $responseType  The response type (e.g., "code").
     * @param  string|null  $clientId  The client ID.
     * @param  string|null  $redirectUri  The redirect URI after authorization.
     * @param  string|null  $scope  The requested scopes (e.g., "openid").
     * @param  string|null  $state  An opaque value for security.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'oidc_authorize')]
    public function oidcAuthorize(
        ?string $responseType = null,
        ?string $clientId = null,
        ?string $redirectUri = null,
        ?string $scope = null,
        ?string $state = null,
    ): array
    {
        return $this->getClient()->get('/v2/oidc/authorize', [
            'response_type' => $responseType,
            'client_id' => $clientId,
            'redirect_uri' => $redirectUri,
            'scope' => $scope,
            'state' => $state,
        ]);
    }

    /**
     * List OIDC Issuers.
     * 
     * Get a list of all OIDC Issuers in your account.
     * 
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_oidc_issuers')]
    public function listOidcIssuers(
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/oidc/issuer', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create OIDC Issuer.
     * 
     * Create a new OIDC Issuer.
     * 
     * @param  string|null  $source  The issuer source type.
     * @param  string|null  $uri  The JWKS URI for the issuer.
     * @param  string|null  $sourceId  The source identifier for the issuer.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_oidc_issuer')]
    public function createOidcIssuer(
        ?string $source = null,
        ?string $uri = null,
        ?string $sourceId = null,
    ): array
    {
        return $this->client->post('/v2/oidc/issuer', [
            'source' => $source,
            'uri' => $uri,
            'source_id' => $sourceId,
        ]);
    }

    /**
     * Delete OIDC Issuer.
     * 
     * Delete an OIDC Issuer.
     * 
     * @param  string  $issuerId  The OIDC Issuer ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_oidc_issuer')]
    public function deleteOidcIssuer(
        string $issuerId,
    ): array
    {
        $this->getClient()->delete('/v2/oidc/issuer/{issuerId');

        return ['success' => true];
    }

    /**
     * Get OIDC Issuer.
     * 
     * Get information about an OIDC Issuer.
     * 
     * @param  string  $issuerId  The OIDC Issuer ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_oidc_issuer')]
    public function getOidcIssuer(
        string $issuerId,
    ): array
    {
        return $this->getClient()->get('/v2/oidc/issuer/{issuerId');
    }

    /**
     * Update OIDC Issuer.
     * 
     * Update an OIDC Issuer.
     * 
     * @param  string  $issuerId  The OIDC Issuer ID.
     * @param  string|null  $source  The issuer source type.
     * @param  string|null  $uri  The JWKS URI for the issuer.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_oidc_issuer')]
    public function updateOidcIssuer(
        string $issuerId,
        ?string $source = null,
        ?string $uri = null,
    ): array
    {
        return $this->client->patch('/v2/oidc/issuer/{issuerId', [
            'source' => $source,
            'uri' => $uri,
        ]);
    }

    /**
     * Get OIDC Issuer JWKS.
     * 
     * Get the JSON Web Key Set (JWKS) for an OIDC Issuer.
     * 
     * @param  string  $issuerId  The OIDC Issuer ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_oidc_issuer_jwks')]
    public function getOidcIssuerJwks(
        string $issuerId,
    ): array
    {
        return $this->getClient()->get('/v2/oidc/issuer/{issuerId/jwks');
    }

    /**
     * Get OIDC JWKS.
     * 
     * Get the JSON Web Key Set (JWKS) for OIDC token verification.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_oidc_jwks')]
    public function getOidcJwks(): array
    {
        return $this->getClient()->get('/v2/oidc/jwks');
    }

    /**
     * List OIDC Providers.
     * 
     * Get a list of all OIDC Providers in your account.
     * 
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_oidc_providers')]
    public function listOidcProviders(
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/oidc/provider', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create OIDC Provider.
     * 
     * Create a new OIDC Provider.
     * 
     * @param  string|null  $name  The provider name.
     * @param  string|null  $issuerId  The OIDC Issuer ID to associate with this provider.
     * @param  string|null  $privateKeyB64  Base64-encoded private key for the provider.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_oidc_provider')]
    public function createOidcProvider(
        ?string $name = null,
        ?string $issuerId = null,
        ?string $privateKeyB64 = null,
    ): array
    {
        return $this->client->post('/v2/oidc/provider', [
            'name' => $name,
            'issuer_id' => $issuerId,
            'private_key_b64' => $privateKeyB64,
        ]);
    }

    /**
     * Delete OIDC Provider.
     * 
     * Delete an OIDC Provider.
     * 
     * @param  string  $providerId  The OIDC Provider ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_oidc_provider')]
    public function deleteOidcProvider(
        string $providerId,
    ): array
    {
        $this->getClient()->delete('/v2/oidc/provider/{providerId');

        return ['success' => true];
    }

    /**
     * Get OIDC Provider.
     * 
     * Get information about an OIDC Provider.
     * 
     * @param  string  $providerId  The OIDC Provider ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_oidc_provider')]
    public function getOidcProvider(
        string $providerId,
    ): array
    {
        return $this->getClient()->get('/v2/oidc/provider/{providerId');
    }

    /**
     * Get OIDC Provider Discovery.
     * 
     * Get the OpenID Connect discovery document for an OIDC Provider.
     * 
     * @param  string  $providerId  The OIDC Provider ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_oidc_provider_discovery')]
    public function getOidcProviderDiscovery(
        string $providerId,
    ): array
    {
        return $this->getClient()->get('/v2/oidc/provider/{providerId/.well-known/openid-configuration');
    }

    /**
     * Create OIDC Provider Token.
     * 
     * Create an OIDC token via the specified provider.
     * 
     * @param  string  $providerId  The OIDC Provider ID.
     * @param  string|null  $grantType  The OAuth 2.0 grant type.
     * @param  string|null  $subjectToken  The subject token for token exchange.
     * @param  string|null  $subjectTokenType  The type of the subject token.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_oidc_provider_token')]
    public function createOidcProviderToken(
        string $providerId,
        ?string $grantType = null,
        ?string $subjectToken = null,
        ?string $subjectTokenType = null,
    ): array
    {
        return $this->client->post('/v2/oidc/provider/{providerId/token', [
            'grant_type' => $grantType,
            'subject_token' => $subjectToken,
            'subject_token_type' => $subjectTokenType,
        ]);
    }

    /**
     * Get OIDC Token Info.
     * 
     * Get information about the current OIDC token.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_oidc_token')]
    public function getOidcToken(): array
    {
        return $this->getClient()->get('/v2/oidc/token');
    }

    /**
     * Get OIDC User Info.
     * 
     * Get information about the authenticated user from OIDC.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_oidc_userinfo')]
    public function getOidcUserinfo(): array
    {
        return $this->getClient()->get('/v2/oidc/userinfo');
    }

}