<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /v2 endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class OrganizationsTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Invitations.
     * 
     * List all pending invitations for your organization.
     * 
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_invitations')]
    public function listInvitations(
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/invitation', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Invitation.
     * 
     * Invite a user to your organization.
     * 
     * @param  string|null  $emailInvited  The email address to invite.
     * @param  array|null  $permissions  Permissions to grant the invited user.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_invitation')]
    public function createInvitation(
        ?string $emailInvited = null,
        ?array $permissions = null,
    ): array
    {
        return $this->client->post('/v2/invitation', [
            'email_invited' => $emailInvited,
            'permissions' => $permissions,
        ]);
    }

    /**
     * Get Invitation.
     * 
     * Get information about an Invitation.
     * 
     * @param  string  $id  The Invitation ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_invitation')]
    public function getInvitation(
        string $id,
    ): array
    {
        return $this->getClient()->get('/v2/invitation/{id');
    }

    /**
     * Resend Invitation.
     * 
     * Resend an invitation email.
     * 
     * @param  string  $id  The Invitation ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'resend_invitation')]
    public function resendInvitation(
        string $id,
    ): array
    {
        return $this->client->post('/v2/invitation/{id/resend');
    }

    /**
     * List Organizations.
     * 
     * Get a list of all Organizations in your account.
     * 
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_organizations')]
    public function listOrganizations(
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/organizations', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Get Organization.
     * 
     * Get information about an Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_organization')]
    public function getOrganization(
        string $id,
    ): array
    {
        return $this->getClient()->get('/v2/organizations/{id');
    }

    /**
     * Update Organization.
     * 
     * Update information for an Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @param  string|null  $name  The organization name.
     * @param  string|null  $type  The organization type.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_organization')]
    public function updateOrganization(
        string $id,
        ?string $name = null,
        ?string $type = null,
    ): array
    {
        return $this->client->put('/v2/organizations/{id', [
            'name' => $name,
            'type' => $type,
        ]);
    }

    /**
     * Get Organization SCIM Config.
     * 
     * Get the SCIM configuration for an Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_organization_scim')]
    public function getOrganizationScim(
        string $id,
    ): array
    {
        return $this->getClient()->get('/v2/organizations/{id/scim');
    }

    /**
     * Disable SCIM.
     * 
     * Disable SCIM provisioning for an Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'disable_organization_scim')]
    public function disableOrganizationScim(
        string $id,
    ): array
    {
        return $this->client->post('/v2/organizations/{id/scim/disable');
    }

    /**
     * Enable SCIM.
     * 
     * Enable SCIM provisioning for an Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'enable_organization_scim')]
    public function enableOrganizationScim(
        string $id,
    ): array
    {
        return $this->client->post('/v2/organizations/{id/scim/enable');
    }

    /**
     * Rotate SCIM Token.
     * 
     * Rotate the SCIM authentication token for an Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'rotate_organization_scim_token')]
    public function rotateOrganizationScimToken(
        string $id,
    ): array
    {
        return $this->client->post('/v2/organizations/{id/scim/token');
    }

    /**
     * List Suspended Organization Users.
     * 
     * List all suspended users in the Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_organization_suspended_users')]
    public function listOrganizationSuspendedUsers(
        string $id,
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/v2/organizations/{id/suspended-users', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Remove User from Organization.
     * 
     * Remove a user from the Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @param  string  $userId  The User ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'remove_organization_user')]
    public function removeOrganizationUser(
        string $id,
        string $userId,
    ): array
    {
        $this->getClient()->delete('/v2/organizations/{id/user/{userId');

        return ['success' => true];
    }

    /**
     * Suspend Organization User.
     * 
     * Suspend a user in the Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @param  string  $userId  The User ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'suspend_organization_user')]
    public function suspendOrganizationUser(
        string $id,
        string $userId,
    ): array
    {
        return $this->client->put('/v2/organizations/{id/user/{userId/suspend');
    }

    /**
     * Unsuspend Organization User.
     * 
     * Unsuspend a user in the Organization.
     * 
     * @param  string  $id  The Organization ID.
     * @param  string  $userId  The User ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'unsuspend_organization_user')]
    public function unsuspendOrganizationUser(
        string $id,
        string $userId,
    ): array
    {
        return $this->client->put('/v2/organizations/{id/user/{userId/unsuspend');
    }

}