<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /plans endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class PlanTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Plans.
     * 
     * Get a list of all VPS plans at Vultr.
     * 
     * The response is an array of JSON plan objects, with unique id with sub-fields in the general format
     * of:
     * 
     *   <type>-<number of cores>-<memory size>-<optional modifier>
     * 
     * For example: vc2-24c-96gb-sc1
     * 
     * More about the sub-fields:
     * 
     *  <type>: The Vultr type code. For example, vc2, vhf, vdc, etc.
     *  <number of cores>: The number of cores, such as 4c for "4 cores", 8c for "8 cores", etc.
     *  <memory size>: Size in GB, such as 32gb.
     *  <optional modifier>: Some plans include a modifier for internal identification purposes, such as
     * CPU type or location surcharges.
     * 
     * > Note: This information about plan id format is for general education. Vultr may change the
     * sub-field format or values at any time. You should not attempt to parse the plan ID sub-fields in
     * your code for any specific purpose.
     * 
     * @param  string|null  $type  Filter the results by type.

| Type | Description |
|----------|-----------------|
| all | All available types |
| vc2 | Cloud Compute |
| vdc | Dedicated Cloud |
| vhf | High Frequency Compute |
| vhp | High Performance |
| voc | All Optimized Cloud types |
| voc-g | General Purpose Optimized Cloud |
| voc-c | CPU Optimized Cloud |
| voc-m | Memory Optimized Cloud |
| voc-s | Storage Optimized Cloud |
| vcg | Cloud GPU |
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @param  string|null  $os  Filter the results by operating system.

|   | Type | Description |
| - | ------ | ------------- |
|   | windows | All available plans that support windows |
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_plans')]
    public function listPlans(
        ?string $type = null,
        ?int $perPage = null,
        ?string $cursor = null,
        ?string $os = null,
    ): array
    {
        return $this->getClient()->get('/plans', [
            'type' => $type,
            'per_page' => $perPage,
            'cursor' => $cursor,
            'os' => $os,
        ]);
    }

    /**
     * List Bare Metal Plans.
     * 
     * Get a list of all Bare Metal plans at Vultr.
     * 
     * The response is an array of JSON plan objects, with unique id with sub-fields in the general format
     * of:
     * 
     *   <type>-<number of cores>-<memory size>-<optional modifier>
     * 
     * For example: vc2-24c-96gb-sc1
     * 
     * More about the sub-fields:
     * 
     *  <type>: The Vultr type code. For example, vc2, vhf, vdc, etc.
     *  <number of cores>: The number of cores, such as 4c for "4 cores", 8c for "8 cores", etc.
     *  <memory size>: Size in GB, such as 32gb.
     *  <optional modifier>: Some plans include a modifier for internal identification purposes, such as
     * CPU type or location surcharges.
     * 
     * > Note: This information about plan id format is for general education. Vultr may change the
     * sub-field format or values at any time. You should not attempt to parse the plan ID sub-fields in
     * your code for any specific purpose.
     * 
     * @param  string|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_metal_plans')]
    public function listMetalPlans(
        ?string $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/plans-metal', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

}