<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /regions endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class RegionTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Regions.
     * 
     * List all Regions at Vultr.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_regions')]
    public function listRegions(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/regions', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * List available plans in region.
     * 
     * Get a list of the available plans in Region region-id. Not all plans are available in all regions.
     * 
     * @param  string  $regionId  The Region id.
     * @param  string|null  $type  Filter the results by type.

| Type | Description |
|----------|-----------------|
| all | All available types |
| vc2 | Cloud Compute |
| vdc | Dedicated Cloud |
| vhf | High Frequency Compute |
| vhp | High Performance |
| voc | All Optimized Cloud types |
| voc-g | General Purpose Optimized Cloud |
| voc-c | CPU Optimized Cloud |
| voc-m | Memory Optimized Cloud |
| voc-s | Storage Optimized Cloud |
| vbm | Bare Metal |
| vcg | Cloud GPU |
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_available_plans_region')]
    public function listAvailablePlansRegion(
        string $regionId,
        ?string $type = null,
    ): array
    {
        return $this->getClient()->get('/regions/{regionId/availability', [
            'type' => $type,
        ]);
    }

}