<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /reserved-ips endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class ReservedIpTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Reserved IPs.
     * 
     * List all Reserved IPs in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_reserved_ips')]
    public function listReservedIps(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/reserved-ips', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Reserved IP.
     * 
     * Create a new Reserved IP. The region and ip_type attributes are required.
     * 
     * @param  string  $region  The Region id where the Reserved IP will be created.
     * @param  string  $ipType  The type of IP address.

 v4
 v6
     * @param  string|null  $label  The user-supplied label.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_reserved_ip')]
    public function createReservedIp(
        string $region,
        string $ipType,
        ?string $label = null,
    ): array
    {
        return $this->client->post('/reserved-ips', [
            'region' => $region,
            'ip_type' => $ipType,
            'label' => $label,
        ]);
    }

    /**
     * Convert Instance IP to Reserved IP.
     * 
     * Convert the ip_address of an existing instance into a Reserved IP.
     * 
     * @param  string  $ipAddress  The IP address to convert.
     * @param  string|null  $label  A user-supplied label for this IP address.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'convert_reserved_ip')]
    public function convertReservedIp(
        string $ipAddress,
        ?string $label = null,
    ): array
    {
        return $this->client->post('/reserved-ips/convert', [
            'ip_address' => $ipAddress,
            'label' => $label,
        ]);
    }

    /**
     * Delete Reserved IP.
     * 
     * Delete a Reserved IP.
     * 
     * @param  string  $reservedIp  The Reserved IP id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_reserved_ip')]
    public function deleteReservedIp(
        string $reservedIp,
    ): array
    {
        $this->getClient()->delete('/reserved-ips/{reservedIp');

        return ['success' => true];
    }

    /**
     * Get Reserved IP.
     * 
     * Get information about a Reserved IP.
     * 
     * @param  string  $reservedIp  The Reserved IP id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_reserved_ip')]
    public function getReservedIp(
        string $reservedIp,
    ): array
    {
        return $this->getClient()->get('/reserved-ips/{reservedIp');
    }

    /**
     * Update Reserved IP.
     * 
     * Update information on a Reserved IP.
     * 
     * @param  string  $reservedIp  The Reserved IP id.
     * @param  string  $label
     * @return array<string, mixed>
     */
    #[McpTool(name: 'patch_reserved_ips_reserved_ip')]
    public function patchReservedIpsReservedIp(
        string $reservedIp,
        string $label,
    ): array
    {
        return $this->client->patch('/reserved-ips/{reservedIp', [
            'label' => $label,
        ]);
    }

    /**
     * Attach Reserved IP.
     * 
     * Attach a Reserved IP to an compute instance or a baremetal instance - instance_id.
     * 
     * @param  string  $reservedIp  The Reserved IP id
     * @param  string  $instanceId  Attach the Reserved IP to a Compute Instance id or a Bare Metal Instance id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'attach_reserved_ip')]
    public function attachReservedIp(
        string $reservedIp,
        string $instanceId,
    ): array
    {
        return $this->client->post('/reserved-ips/{reservedIp/attach', [
            'instance_id' => $instanceId,
        ]);
    }

    /**
     * Detach Reserved IP.
     * 
     * Detach a Reserved IP.
     * 
     * @param  string  $reservedIp  The Reserved IP id
     * @return array<string, mixed>
     */
    #[McpTool(name: 'detach_reserved_ip')]
    public function detachReservedIp(
        string $reservedIp,
    ): array
    {
        return $this->client->post('/reserved-ips/{reservedIp/detach');
    }

}