<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /object-storage endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class S3Tools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Object Storages.
     * 
     * Get a list of all Object Storage in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_object_storages')]
    public function listObjectStorages(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/object-storage', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Object Storage.
     * 
     * Create new Object Storage. The cluster_id attribute is required.
     * 
     * @param  int  $clusterId  The Cluster id where the Object Storage will be created.
     * @param  int  $tierId  The Tier id of the tier to set up for. Must be one of available tiers for the cluster.
     * @param  string|null  $label  The user-supplied label for this Object Storage.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_object_storage')]
    public function createObjectStorage(
        int $clusterId,
        int $tierId,
        ?string $label = null,
    ): array
    {
        return $this->client->post('/object-storage', [
            'cluster_id' => $clusterId,
            'tier_id' => $tierId,
            'label' => $label,
        ]);
    }

    /**
     * Get All Clusters.
     * 
     * Get a list of all Object Storage Clusters.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_object_storage_clusters')]
    public function listObjectStorageClusters(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/object-storage/clusters', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Get All Cluster Tiers.
     * 
     * Get a list of all Object Storage Tiers for a given Cluster.
     * 
     * @param  string  $clusterId  The Cluster id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_object_storage_cluster_tiers')]
    public function listObjectStorageClusterTiers(
        string $clusterId,
    ): array
    {
        return $this->getClient()->get('/object-storage/clusters/{clusterId/tiers');
    }

    /**
     * Get All Tiers.
     * 
     * Get a list of all Object Storage Tiers.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_object_storage_tiers')]
    public function listObjectStorageTiers(): array
    {
        return $this->getClient()->get('/object-storage/tiers');
    }

    /**
     * Delete Object Storage.
     * 
     * Delete an Object Storage.
     * 
     * @param  string  $objectStorageId  The Object Storage id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_object_storage')]
    public function deleteObjectStorage(
        string $objectStorageId,
    ): array
    {
        $this->getClient()->delete('/object-storage/{objectStorageId');

        return ['success' => true];
    }

    /**
     * Get Object Storage.
     * 
     * Get information about an Object Storage.
     * 
     * @param  string  $objectStorageId  The Object Storage id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_object_storage')]
    public function getObjectStorage(
        string $objectStorageId,
    ): array
    {
        return $this->getClient()->get('/object-storage/{objectStorageId');
    }

    /**
     * Update Object Storage.
     * 
     * Update the label for an Object Storage.
     * 
     * @param  string  $objectStorageId  The Object Storage id.
     * @param  string  $label  The user-supplied label for the Object Storage.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_object_storage')]
    public function updateObjectStorage(
        string $objectStorageId,
        string $label,
    ): array
    {
        return $this->client->put('/object-storage/{objectStorageId', [
            'label' => $label,
        ]);
    }

    /**
     * Create Bucket.
     * 
     * Create new Bucket.
     * 
     * @param  string  $objectStorageId  The Object Storage id.
     * @param  string  $bucketName  The user-supplied name of the bucket.
     * @param  bool|null  $versioning  Enable versioning.
     * @param  bool|null  $objectLock  Enable object lock. Automatically enables versioning.
     * @param  bool|null  $archival  Enable archival mode. Cannot be mixed with versioning/object lock.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_object_storage_bucket')]
    public function createObjectStorageBucket(
        string $objectStorageId,
        string $bucketName,
        ?bool $versioning = null,
        ?bool $objectLock = null,
        ?bool $archival = null,
    ): array
    {
        return $this->client->post('/object-storage/{objectStorageId/bucket', [
            'bucket_name' => $bucketName,
            'versioning' => $versioning,
            'object_lock' => $objectLock,
            'archival' => $archival,
        ]);
    }

    /**
     * Delete Bucket.
     * 
     * Delete a Bucket.
     * 
     * @param  string  $objectStorageId  The Object Storage id.
     * @param  string  $bucketName  The name of the bucket.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_object_storage_bucket')]
    public function deleteObjectStorageBucket(
        string $objectStorageId,
        string $bucketName,
    ): array
    {
        $this->getClient()->delete('/object-storage/{objectStorageId/bucket/{bucketName');

        return ['success' => true];
    }

    /**
     * Enable Bucket Archival.
     * 
     * Set the archival status of a Bucket.
     * 
     * @param  string  $objectStorageId  The Object Storage id.
     * @param  string  $bucketName  The name of the bucket.
     * @param  bool  $archival
     * @return array<string, mixed>
     */
    #[McpTool(name: 'set_object_storage_bucket_archival')]
    public function setObjectStorageBucketArchival(
        string $objectStorageId,
        string $bucketName,
        bool $archival,
    ): array
    {
        return $this->client->post('/object-storage/{objectStorageId/bucket/{bucketName/archival', [
            'archival' => $archival,
        ]);
    }

    /**
     * Delete Bucket Lifecycle Policy.
     * 
     * Delete the Bucket Lifecycle Policy.
     * 
     * @param  string  $objectStorageId  The Object Storage id.
     * @param  string  $bucketName  The name of the bucket.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_object_storage_bucket_lifecycle_policy')]
    public function deleteObjectStorageBucketLifecyclePolicy(
        string $objectStorageId,
        string $bucketName,
    ): array
    {
        $this->getClient()->delete('/object-storage/{objectStorageId/bucket/{bucketName/lifecycle');

        return ['success' => true];
    }

    /**
     * Set Bucket Lifecycle Policy.
     * 
     * Set the lifecycle policy of a Bucket.
     * 
     * @param  string  $objectStorageId  The Object Storage id.
     * @param  string  $bucketName  The name of the bucket.
     * @param  array  $archiveRules
     * @return array<string, mixed>
     */
    #[McpTool(name: 'set_object_storage_bucket_lifecycle')]
    public function setObjectStorageBucketLifecycle(
        string $objectStorageId,
        string $bucketName,
        array $archiveRules,
    ): array
    {
        return $this->client->post('/object-storage/{objectStorageId/bucket/{bucketName/lifecycle', [
            'archive_rules' => $archiveRules,
        ]);
    }

    /**
     * Regenerate Object Storage Keys.
     * 
     * Regenerate the keys for an Object Storage.
     * 
     * @param  string  $objectStorageId  The Object Storage id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'regenerate_object_storage_keys')]
    public function regenerateObjectStorageKeys(
        string $objectStorageId,
    ): array
    {
        return $this->client->post('/object-storage/{objectStorageId/regenerate-keys');
    }

}