<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /scim endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class ScimTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List SCIM Groups.
     * 
     * List Groups in your Organization via the SCIM 2.0 protocol. Authenticate using the SCIM token
     * obtained from the Organization SCIM configuration.
     * 
     * @param  int|null  $startIndex  The 1-based index of the first result in the current set of list results.
     * @param  int|null  $count  Specifies the desired maximum number of query results per page.
     * @param  string|null  $filter  Filter expression to select specific resources (e.g., displayName eq "my-group").
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_list_groups')]
    public function scimListGroups(
        ?int $startIndex = null,
        ?int $count = null,
        ?string $filter = null,
    ): array
    {
        return $this->getClient()->get('/scim/v2/Groups', [
            'startIndex' => $startIndex,
            'count' => $count,
            'filter' => $filter,
        ]);
    }

    /**
     * Create SCIM Group.
     * 
     * Create a new Group in your Organization via the SCIM 2.0 protocol. Authenticate using the SCIM token
     * obtained from the Organization SCIM configuration.
     * 
     * @param  array|null  $schemas  SCIM schemas (must include urn:ietf:params:scim:schemas:core:2.0:Group).
     * @param  string|null  $displayName  The group display name.
     * @param  string|null  $externalId  An external identifier for the group.
     * @param  array|null  $members
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_create_group')]
    public function scimCreateGroup(
        ?array $schemas = null,
        ?string $displayName = null,
        ?string $externalId = null,
        ?array $members = null,
    ): array
    {
        return $this->client->post('/scim/v2/Groups', [
            'schemas' => $schemas,
            'displayName' => $displayName,
            'externalId' => $externalId,
            'members' => $members,
        ]);
    }

    /**
     * Delete SCIM Group.
     * 
     * Delete a Group via the SCIM 2.0 protocol. Authenticate using the SCIM token obtained from the
     * Organization SCIM configuration.
     * 
     * @param  string  $id  The SCIM Group ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_delete_group')]
    public function scimDeleteGroup(
        string $id,
    ): array
    {
        $this->getClient()->delete('/scim/v2/Groups/{id');

        return ['success' => true];
    }

    /**
     * Get SCIM Group.
     * 
     * Get a Group by ID via the SCIM 2.0 protocol. Authenticate using the SCIM token obtained from the
     * Organization SCIM configuration.
     * 
     * @param  string  $id  The SCIM Group ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_get_group')]
    public function scimGetGroup(
        string $id,
    ): array
    {
        return $this->getClient()->get('/scim/v2/Groups/{id');
    }

    /**
     * Patch SCIM Group.
     * 
     * Partially update a Group via the SCIM 2.0 protocol. Authenticate using the SCIM token obtained from
     * the Organization SCIM configuration.
     * 
     * @param  string  $id  The SCIM Group ID.
     * @param  array|null  $schemas  SCIM schemas (must include urn:ietf:params:scim:api:messages:2.0:PatchOp).
     * @param  array|null  $operations
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_patch_group')]
    public function scimPatchGroup(
        string $id,
        ?array $schemas = null,
        ?array $operations = null,
    ): array
    {
        return $this->client->patch('/scim/v2/Groups/{id', [
            'schemas' => $schemas,
            'Operations' => $operations,
        ]);
    }

    /**
     * Update SCIM Group.
     * 
     * Replace a Group via the SCIM 2.0 protocol. Authenticate using the SCIM token obtained from the
     * Organization SCIM configuration.
     * 
     * @param  string  $id  The SCIM Group ID.
     * @param  array|null  $schemas  SCIM schemas (must include urn:ietf:params:scim:schemas:core:2.0:Group).
     * @param  string|null  $displayName  The group display name.
     * @param  string|null  $externalId  An external identifier for the group.
     * @param  array|null  $members
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_update_group')]
    public function scimUpdateGroup(
        string $id,
        ?array $schemas = null,
        ?string $displayName = null,
        ?string $externalId = null,
        ?array $members = null,
    ): array
    {
        return $this->client->put('/scim/v2/Groups/{id', [
            'schemas' => $schemas,
            'displayName' => $displayName,
            'externalId' => $externalId,
            'members' => $members,
        ]);
    }

    /**
     * List SCIM Users.
     * 
     * List Users in your Organization via the SCIM 2.0 protocol. Authenticate using the SCIM token
     * obtained from the Organization SCIM configuration.
     * 
     * @param  int|null  $startIndex  The 1-based index of the first result in the current set of list results.
     * @param  int|null  $count  Specifies the desired maximum number of query results per page.
     * @param  string|null  $filter  Filter expression to select specific resources (e.g., userName eq "user@example.com").
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_list_users')]
    public function scimListUsers(
        ?int $startIndex = null,
        ?int $count = null,
        ?string $filter = null,
    ): array
    {
        return $this->getClient()->get('/scim/v2/Users', [
            'startIndex' => $startIndex,
            'count' => $count,
            'filter' => $filter,
        ]);
    }

    /**
     * Create SCIM User.
     * 
     * Create a new User in your Organization via the SCIM 2.0 protocol. Authenticate using the SCIM token
     * obtained from the Organization SCIM configuration.
     * 
     * @param  array|null  $schemas  SCIM schemas (must include urn:ietf:params:scim:schemas:core:2.0:User).
     * @param  string|null  $userName  The user's email address.
     * @param  array|null  $name
     * @param  string|null  $displayName
     * @param  bool|null  $active
     * @param  array|null  $phoneNumbers
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_create_user')]
    public function scimCreateUser(
        ?array $schemas = null,
        ?string $userName = null,
        ?array $name = null,
        ?string $displayName = null,
        ?bool $active = null,
        ?array $phoneNumbers = null,
    ): array
    {
        return $this->client->post('/scim/v2/Users', [
            'schemas' => $schemas,
            'userName' => $userName,
            'name' => $name,
            'displayName' => $displayName,
            'active' => $active,
            'phoneNumbers' => $phoneNumbers,
        ]);
    }

    /**
     * Delete SCIM User.
     * 
     * Delete a User via the SCIM 2.0 protocol. Authenticate using the SCIM token obtained from the
     * Organization SCIM configuration.
     * 
     * @param  string  $id  The SCIM User ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_delete_user')]
    public function scimDeleteUser(
        string $id,
    ): array
    {
        $this->getClient()->delete('/scim/v2/Users/{id');

        return ['success' => true];
    }

    /**
     * Get SCIM User.
     * 
     * Get a User by ID via the SCIM 2.0 protocol. Authenticate using the SCIM token obtained from the
     * Organization SCIM configuration.
     * 
     * @param  string  $id  The SCIM User ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_get_user')]
    public function scimGetUser(
        string $id,
    ): array
    {
        return $this->getClient()->get('/scim/v2/Users/{id');
    }

    /**
     * Patch SCIM User.
     * 
     * Partially update a User via the SCIM 2.0 protocol. Authenticate using the SCIM token obtained from
     * the Organization SCIM configuration.
     * 
     * @param  string  $id  The SCIM User ID.
     * @param  array|null  $schemas  SCIM schemas (must include urn:ietf:params:scim:api:messages:2.0:PatchOp).
     * @param  array|null  $operations
     * @return array<string, mixed>
     */
    #[McpTool(name: 'scim_patch_user')]
    public function scimPatchUser(
        string $id,
        ?array $schemas = null,
        ?array $operations = null,
    ): array
    {
        return $this->client->patch('/scim/v2/Users/{id', [
            'schemas' => $schemas,
            'Operations' => $operations,
        ]);
    }

}