<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /inference endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class ServerlessInferenceTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Serverless Inference.
     * 
     * List all Serverless Inference subscriptions in your account.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_inference')]
    public function listInference(): array
    {
        return $this->getClient()->get('/inference');
    }

    /**
     * Create Serverless Inference.
     * 
     * Create a new Serverless Inference subscription.
     * 
     * @param  string  $label  A user-supplied label for this Serverless Inference subscription.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_inference')]
    public function createInference(
        string $label,
    ): array
    {
        return $this->client->post('/inference', [
            'label' => $label,
        ]);
    }

    /**
     * Delete Serverless Inference.
     * 
     * Delete a Serverless Inference subscription.
     * 
     * @param  string  $inferenceId  The Inference ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_inference')]
    public function deleteInference(
        string $inferenceId,
    ): array
    {
        $this->getClient()->delete('/inference/{inferenceId');

        return ['success' => true];
    }

    /**
     * Get Serverless Inference.
     * 
     * Get information about a Serverless Inference subscription.
     * 
     * @param  string  $inferenceId  The Inference ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_inference')]
    public function getInference(
        string $inferenceId,
    ): array
    {
        return $this->getClient()->get('/inference/{inferenceId');
    }

    /**
     * Update Serverless Inference.
     * 
     * Update information for a Serverless Inference subscription.
     * 
     * @param  string  $inferenceId  The Inference ID.
     * @param  string|null  $label  A user-supplied label for this Serverless Inference subscription.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_inference')]
    public function updateInference(
        string $inferenceId,
        ?string $label = null,
    ): array
    {
        return $this->client->patch('/inference/{inferenceId', [
            'label' => $label,
        ]);
    }

    /**
     * Get Serverless Inference Usage Information.
     * 
     * Get usage information for a Serverless Inference subscription.
     * 
     * @param  string  $inferenceId  The Inference ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_inference_usage')]
    public function getInferenceUsage(
        string $inferenceId,
    ): array
    {
        return $this->getClient()->get('/inference/{inferenceId/usage');
    }

}