<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /snapshots endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class SnapshotTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Snapshots.
     * 
     * Get information about all Snapshots in your account.
     * 
     * @param  string|null  $description  Filter the list of Snapshots by description
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_snapshots')]
    public function listSnapshots(
        ?string $description = null,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/snapshots', [
            'description' => $description,
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Snapshot.
     * 
     * Create a new Snapshot for instance_id.
     * 
     * @param  string  $instanceId  Create a Snapshot for this Instance id.
     * @param  string|null  $description  The user-supplied description of the Snapshot.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_snapshot')]
    public function createSnapshot(
        string $instanceId,
        ?string $description = null,
    ): array
    {
        return $this->client->post('/snapshots', [
            'instance_id' => $instanceId,
            'description' => $description,
        ]);
    }

    /**
     * Create Snapshot from URL.
     * 
     * Create a new Snapshot from a RAW image located at url.
     * 
     * @param  string  $url  The public URL containing a RAW image.
     * @param  string|null  $description  The user-supplied description of the Snapshot.
     * @param  bool|null  $uefi  Whether or not the snapshot uses UEFI.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_snapshot_create_from_url')]
    public function createSnapshotCreateFromUrl(
        string $url,
        ?string $description = null,
        ?bool $uefi = null,
    ): array
    {
        return $this->client->post('/snapshots/create-from-url', [
            'url' => $url,
            'description' => $description,
            'uefi' => $uefi,
        ]);
    }

    /**
     * Delete Snapshot.
     * 
     * Delete a Snapshot.
     * 
     * @param  string  $snapshotId  The Snapshot id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_snapshot')]
    public function deleteSnapshot(
        string $snapshotId,
    ): array
    {
        $this->getClient()->delete('/snapshots/{snapshotId');

        return ['success' => true];
    }

    /**
     * Get Snapshot.
     * 
     * Get information about a Snapshot.
     * 
     * @param  string  $snapshotId  The Snapshot id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_snapshot')]
    public function getSnapshot(
        string $snapshotId,
    ): array
    {
        return $this->getClient()->get('/snapshots/{snapshotId');
    }

    /**
     * Update Snapshot.
     * 
     * Update the description for a Snapshot.
     * 
     * @param  string  $snapshotId  The Snapshot id.
     * @param  string  $description  The user-supplied description for the Snapshot.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'put_snapshots_snapshot_id')]
    public function putSnapshotsSnapshotId(
        string $snapshotId,
        string $description,
    ): array
    {
        return $this->client->put('/snapshots/{snapshotId', [
            'description' => $description,
        ]);
    }

}