<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /ssh-keys endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class SshKeyTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List SSH Keys.
     * 
     * List all SSH Keys in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_ssh_keys')]
    public function listSshKeys(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/ssh-keys', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create SSH key.
     * 
     * Create a new SSH Key for use with future instances. This does not update any running instances.
     * 
     * @param  string  $name  The user-supplied name for this SSH Key.
     * @param  string  $sshKey  The SSH Key.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_ssh_key')]
    public function createSshKey(
        string $name,
        string $sshKey,
    ): array
    {
        return $this->client->post('/ssh-keys', [
            'name' => $name,
            'ssh_key' => $sshKey,
        ]);
    }

    /**
     * Delete SSH Key.
     * 
     * Delete an SSH Key.
     * 
     * @param  string  $sshKeyId  The SSH Key id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_ssh_key')]
    public function deleteSshKey(
        string $sshKeyId,
    ): array
    {
        $this->getClient()->delete('/ssh-keys/{sshKeyId');

        return ['success' => true];
    }

    /**
     * Get SSH Key.
     * 
     * Get information about an SSH Key.
     * 
     * @param  string  $sshKeyId  The SSH Key id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_ssh_key')]
    public function getSshKey(
        string $sshKeyId,
    ): array
    {
        return $this->getClient()->get('/ssh-keys/{sshKeyId');
    }

    /**
     * Update SSH Key.
     * 
     * Update an SSH Key. The attributes name and ssh_key are optional. If not set, the attributes will
     * retain their original values. New deployments will use the updated key, but this action does not
     * update previously deployed instances.
     * 
     * @param  string  $sshKeyId  The SSH Key id.
     * @param  string|null  $name  The user-supplied name for this SSH Key.
     * @param  string|null  $sshKey  The SSH Key.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_ssh_key')]
    public function updateSshKey(
        string $sshKeyId,
        ?string $name = null,
        ?string $sshKey = null,
    ): array
    {
        return $this->client->patch('/ssh-keys/{sshKeyId', [
            'name' => $name,
            'ssh_key' => $sshKey,
        ]);
    }

}