<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /startup-scripts endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class StartupTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Startup Scripts.
     * 
     * Get a list of all Startup Scripts.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_startup_scripts')]
    public function listStartupScripts(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/startup-scripts', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Startup Script.
     * 
     * Create a new Startup Script. The name and script attributes are required, and scripts are base-64
     * encoded.
     * 
     * @param  string  $name  The name of the Startup Script.
     * @param  string|null  $type  The Startup Script type.

 boot (default)
 pxe
     * @param  string  $script  The base-64 encoded Startup Script.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_startup_script')]
    public function createStartupScript(
        string $name,
        string $script,
        ?string $type = null,
    ): array
    {
        return $this->client->post('/startup-scripts', [
            'name' => $name,
            'type' => $type,
            'script' => $script,
        ]);
    }

    /**
     * Delete Startup Script.
     * 
     * Delete a Startup Script.
     * 
     * @param  string  $startupId  The Startup Script id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_startup_script')]
    public function deleteStartupScript(
        string $startupId,
    ): array
    {
        $this->getClient()->delete('/startup-scripts/{startupId');

        return ['success' => true];
    }

    /**
     * Get Startup Script.
     * 
     * Get information for a Startup Script.
     * 
     * @param  string  $startupId  The Startup Script id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_startup_script')]
    public function getStartupScript(
        string $startupId,
    ): array
    {
        return $this->getClient()->get('/startup-scripts/{startupId');
    }

    /**
     * Update Startup Script.
     * 
     * Update a Startup Script. The attributes name and script are optional. If not set, the attributes
     * will retain their original values. The script attribute is base-64 encoded. New deployments will use
     * the updated script, but this action does not update previously deployed instances.
     * 
     * @param  string  $startupId  The Startup Script id.
     * @param  string|null  $name  The name of the Startup Script.
     * @param  string|null  $script  The base-64 encoded Startup Script.
     * @param  string|null  $type  The Startup Script type.

boot (default)
pxe
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_startup_script')]
    public function updateStartupScript(
        string $startupId,
        ?string $name = null,
        ?string $script = null,
        ?string $type = null,
    ): array
    {
        return $this->client->patch('/startup-scripts/{startupId', [
            'name' => $name,
            'script' => $script,
            'type' => $type,
        ]);
    }

}