<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /storage-gateways endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class StorageGatewaysTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List storage gateways.
     * 
     * Get a list of all Storage Gateways in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_storage_gateways')]
    public function listStorageGateways(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/storage-gateways', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Storage Gateway.
     * 
     * @param  string  $label  The user-supplied label for this Storage Gateway.
     * @param  string  $type  The gateway type
     * @param  string  $region  The Region id for this Storage Gateway.
     * @param  array  $exportConfig
     * @param  string  $networkConfig
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_storage_gateway')]
    public function createStorageGateway(
        string $label,
        string $type,
        string $region,
        array $exportConfig,
        string $networkConfig,
    ): array
    {
        return $this->client->post('/storage-gateways', [
            'label' => $label,
            'type' => $type,
            'region' => $region,
            'export_config' => $exportConfig,
            'network_config' => $networkConfig,
        ]);
    }

    /**
     * Delete Storage Gateway.
     * 
     * Delete a Storage Gateway.
     * 
     * @param  string  $storageGatewayId  The Storage Gateway id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_storage_gateway')]
    public function deleteStorageGateway(
        string $storageGatewayId,
    ): array
    {
        $this->getClient()->delete('/storage-gateways/{storageGatewayId');

        return ['success' => true];
    }

    /**
     * Get Storage Gateway.
     * 
     * Get information about a Storage Gateway.
     * 
     * @param  string  $storageGatewayId  The Storage Gateway id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_storage_gateway')]
    public function getStorageGateway(
        string $storageGatewayId,
    ): array
    {
        return $this->getClient()->get('/storage-gateways/{storageGatewayId');
    }

    /**
     * Update Storage Gateway.
     * 
     * Update the label for a Storage Gateway.
     * 
     * @param  string  $storageGatewayId  The Storage Gateway id.
     * @param  string  $label  The user-supplied label for the Storage Gateway.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_storage_gateway')]
    public function updateStorageGateway(
        string $storageGatewayId,
        string $label,
    ): array
    {
        return $this->client->put('/storage-gateways/{storageGatewayId', [
            'label' => $label,
        ]);
    }

    /**
     * Add a new export to this storage gateway.
     * 
     * @param  string  $storageGatewayId  The Storage Gateway id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'add_storage_gateway_export')]
    public function addStorageGatewayExport(
        string $storageGatewayId,
    ): array
    {
        return $this->client->post('/storage-gateways/{storageGatewayId/exports');
    }

    /**
     * Delete Storage Gateway Export.
     * 
     * Delete a Storage Gateway Export.
     * 
     * @param  string  $storageGatewayId  The Storage Gateway id.
     * @param  string  $exportId  The Storage Gateway export id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_storage_gateway_export')]
    public function deleteStorageGatewayExport(
        string $storageGatewayId,
        string $exportId,
    ): array
    {
        $this->getClient()->delete('/storage-gateways/{storageGatewayId/exports/{exportId');

        return ['success' => true];
    }

}