<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /subaccounts endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class SubaccountTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Sub-Accounts.
     * 
     * Get information about all sub-accounts for your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_subaccounts')]
    public function listSubaccounts(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/subaccounts', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create Sub-Account.
     * 
     * Create a new subaccount.
     * 
     * @param  string  $email  Create a new sub-account with this email address.
     * @param  string|null  $subaccountName  Your name for this sub-account.
     * @param  string|null  $subaccountId  Your ID for this sub-account.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_subaccount')]
    public function createSubaccount(
        string $email,
        ?string $subaccountName = null,
        ?string $subaccountId = null,
    ): array
    {
        return $this->client->post('/subaccounts', [
            'email' => $email,
            'subaccount_name' => $subaccountName,
            'subaccount_id' => $subaccountId,
        ]);
    }

}