<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /tickets endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class TicketsTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List Tickets.
     * 
     * List all open customer tickets on the account.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_tickets')]
    public function listTickets(): array
    {
        return $this->getClient()->get('/tickets');
    }

    /**
     * Create Ticket.
     * 
     * Create a new ticket.
     * 
     * @param  string  $subject  Text describing the subject for this ticket.
     * @param  string  $description  Detailed text describing the reason for this ticket - will be created as first entry in ticket.
     * @param  string|null  $subUuid  UUID of the subscription that should be related to this ticket.
     * @param  string|null  $category  Which category the ticket is for. If specified, must be one of these values - General Support, Account Cancellation, Billing Questions, Marketplace, API v2.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_ticket')]
    public function createTicket(
        string $subject,
        string $description,
        ?string $subUuid = null,
        ?string $category = null,
    ): array
    {
        return $this->client->post('/tickets', [
            'subject' => $subject,
            'description' => $description,
            'sub-uuid' => $subUuid,
            'category' => $category,
        ]);
    }

    /**
     * Get Ticket.
     * 
     * Get information about a ticket.
     * 
     * @param  string  $reference  The reference.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_ticket')]
    public function getTicket(
        string $reference,
    ): array
    {
        return $this->getClient()->get('/tickets/{reference');
    }

    /**
     * Close Ticket.
     * 
     * Close an open ticket.
     * 
     * @param  string  $reference  The reference.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'close_ticket')]
    public function closeTicket(
        string $reference,
    ): array
    {
        return $this->client->post('/tickets/{reference');
    }

    /**
     * List Ticket Replies.
     * 
     * List all replies for a given ticket. If attachments exist, their metadata is included, but not the
     * contents.
     * 
     * @param  string  $reference  The reference.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_ticket_replies')]
    public function listTicketReplies(
        string $reference,
    ): array
    {
        return $this->getClient()->get('/tickets/{reference/replies');
    }

    /**
     * Create Ticket Reply.
     * 
     * Create a new reply to an existing ticket.
     * 
     * @param  string  $reference  The reference.
     * @param  string  $description  Reply message
     * @param  array|null  $attachments
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_reply')]
    public function createReply(
        string $reference,
        string $description,
        ?array $attachments = null,
    ): array
    {
        return $this->client->post('/tickets/{reference/replies', [
            'description' => $description,
            'attachments' => $attachments,
        ]);
    }

    /**
     * Get Ticket Reply Attachment.
     * 
     * Get a ticket reply attachment.
     * 
     * @param  string  $reference  The reference.
     * @param  string  $ticketReplyIndex  The index.
     * @param  string  $ticketAttachmentIndex  The attachments index.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_ticket_reply_attachment')]
    public function getTicketReplyAttachment(
        string $reference,
        string $ticketReplyIndex,
        string $ticketAttachmentIndex,
    ): array
    {
        return $this->getClient()->get('/tickets/{reference/replies/{ticketReplyIndex/attachments/{ticketAttachmentIndex');
    }

    /**
     * Rate Ticket Reply.
     * 
     * Rate a ticket reply from Vultr.
     * 
     * @param  string  $reference  The reference.
     * @param  string  $ticketReplyIndex  The index.
     * @param  string  $comment  Rating message
     * @param  float  $rating  1 for positive, -1 for negative, 0 for neutral
     * @return array<string, mixed>
     */
    #[McpTool(name: 'review_ticket_reply')]
    public function reviewTicketReply(
        string $reference,
        string $ticketReplyIndex,
        string $comment,
        float $rating,
    ): array
    {
        return $this->client->post('/tickets/{reference/replies/{ticketReplyIndex/review', [
            'comment' => $comment,
            'rating' => $rating,
        ]);
    }

}