<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /users endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class UsersTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * Get Users.
     * 
     * Get a list of all Users in your account.
     * 
     * @param  float|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_users')]
    public function listUsers(
        ?float $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/users', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create User.
     * 
     * Create a new User. The email, first_name, last_name, and password attributes are required.
     * 
     * @param  string  $email  The User's email address.
     * @param  string  $firstName  The User's first name.
     * @param  string  $lastName  The User's last name.
     * @param  string  $password  The User's password.
     * @param  bool|null  $apiEnabled  API access is permitted for this User.

 true (default)
 false
     * @param  array|null  $acls  An array of permissions granted.

 abuse
 activity_logs
 alerts
 billing
 dns
 firewall
 loadbalancer
 manage\_users
 objstore
 provisioning
 subscriptions
 subscriptions\_view
 support
 upgrade
     * @param  bool|null  $serviceUser  Create this user as a service user (API-only access, no portal login).
Service users will receive their API key upon creation.

 true
 false (default)
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_user')]
    public function createUser(
        string $email,
        string $firstName,
        string $lastName,
        string $password,
        ?bool $apiEnabled = null,
        ?array $acls = null,
        ?bool $serviceUser = null,
    ): array
    {
        return $this->client->post('/users', [
            'email' => $email,
            'first_name' => $firstName,
            'last_name' => $lastName,
            'password' => $password,
            'api_enabled' => $apiEnabled,
            'acls' => $acls,
            'service_user' => $serviceUser,
        ]);
    }

    /**
     * Delete User.
     * 
     * Delete a User.
     * 
     * @param  string  $userId  The User id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_user')]
    public function deleteUser(
        string $userId,
    ): array
    {
        $this->getClient()->delete('/users/{userId');

        return ['success' => true];
    }

    /**
     * Get User.
     * 
     * Get information about a User.
     * 
     * @param  string  $userId  The User id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_user')]
    public function getUser(
        string $userId,
    ): array
    {
        return $this->getClient()->get('/users/{userId');
    }

    /**
     * Update User.
     * 
     * Update information for a User. All attributes are optional. If not set, the attributes will retain
     * their original values.
     * 
     * @param  string  $userId  The User id.
     * @param  string|null  $email  The User's email address.
     * @param  bool|null  $apiEnabled  API access is permitted for this User.

 true (default)
 false
     * @param  array|null  $acls  An array of permission granted. Valid values:

 abuse
 activity_logs
 alerts
 billing
 dns
 firewall
 loadbalancer
 manage\_users
 objstore
 provisioning
 subscriptions
 subscriptions\_view
 support
 upgrade
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_user')]
    public function updateUser(
        string $userId,
        ?string $email = null,
        ?bool $apiEnabled = null,
        ?array $acls = null,
    ): array
    {
        return $this->client->patch('/users/{userId', [
            'email' => $email,
            'api_enabled' => $apiEnabled,
            'acls' => $acls,
        ]);
    }

    /**
     * List User API Keys.
     * 
     * Gets all API keys for the target user. API keys returned by this method are masked. Only root users
     * or users with manage users permission can access this endpoint.
     * 
     * @param  string  $userId  The User id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_user_api_keys')]
    public function listUserApiKeys(
        string $userId,
    ): array
    {
        return $this->getClient()->get('/users/{userId/apikeys');
    }

    /**
     * Create User API Key.
     * 
     * Adds an API key to the target user's API key list. Only root users or users with manage users
     * permission can access this endpoint.
     * 
     * @param  string  $userId  The User id.
     * @param  string|null  $name  Custom name of the API key.
     * @param  bool|null  $expire  Will the API key expire?
     * @param  string|null  $dateExpire  Date when the API key expires. Only valid when expire is true.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_user_api_key')]
    public function createUserApiKey(
        string $userId,
        ?string $name = null,
        ?bool $expire = null,
        ?string $dateExpire = null,
    ): array
    {
        return $this->client->post('/users/{userId/apikeys', [
            'name' => $name,
            'expire' => $expire,
            'date_expire' => $dateExpire,
        ]);
    }

    /**
     * Delete User API Key.
     * 
     * Delete an API key from the target user's API key list. Only root users or users with manage users
     * permission can access this endpoint.
     * 
     * @param  string  $userId  The User id.
     * @param  string  $apikeyId  The API key id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_user_api_key')]
    public function deleteUserApiKey(
        string $userId,
        string $apikeyId,
    ): array
    {
        $this->getClient()->delete('/users/{userId/apikeys/{apikeyId');

        return ['success' => true];
    }

    /**
     * Get User API Key.
     * 
     * Gets information about a user's API key. API keys returned by this method are masked. Only root
     * users or users with manage users permission can access this endpoint.
     * 
     * @param  string  $userId  The User id.
     * @param  string  $apikeyId  The API key id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_user_api_key')]
    public function getUserApiKey(
        string $userId,
        string $apikeyId,
    ): array
    {
        return $this->getClient()->get('/users/{userId/apikeys/{apikeyId');
    }

    /**
     * Remove IP from User Whitelist.
     * 
     * Remove an IP address or subnet from a User's whitelist. Only root users or users with manage users
     * permission can access this endpoint.
     * 
     * @param  string  $userId  The User id.
     * @param  string  $subnet  The IP address or subnet to remove.
     * @param  int  $subnetSize  The subnet size.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'remove_user_ip_whitelist')]
    public function removeUserIpWhitelist(
        string $userId,
        string $subnet,
        int $subnetSize,
    ): array
    {
        $this->getClient()->delete('/users/{userId/ip-whitelist');

        return ['success' => true];
    }

    /**
     * List User IP Whitelist.
     * 
     * Get the IP whitelist for a User. Only root users or users with manage users permission can access
     * this endpoint.
     * 
     * @param  string  $userId  The User id.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_user_ip_whitelist')]
    public function listUserIpWhitelist(
        string $userId,
    ): array
    {
        return $this->getClient()->get('/users/{userId/ip-whitelist');
    }

    /**
     * Add IP to User Whitelist.
     * 
     * Add an IP address or subnet to a User's whitelist. Only root users or users with manage users
     * permission can access this endpoint.
     * 
     * @param  string  $userId  The User id.
     * @param  string  $subnet  The IP address or subnet to whitelist.
     * @param  int  $subnetSize  The subnet size. For IPv4: 0 (allow all) or 8-32. For IPv6: 0 (allow all) or 20-128.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'add_user_ip_whitelist')]
    public function addUserIpWhitelist(
        string $userId,
        string $subnet,
        int $subnetSize,
    ): array
    {
        return $this->client->post('/users/{userId/ip-whitelist', [
            'subnet' => $subnet,
            'subnet_size' => $subnetSize,
        ]);
    }

    /**
     * Get User IP Whitelist Entry.
     * 
     * Get a specific IP whitelist entry for a User. Only root users or users with manage users permission
     * can access this endpoint.
     * 
     * @param  string  $userId  The User id.
     * @param  string  $subnet  The IP address or subnet.
     * @param  int  $subnetSize  The subnet size.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_user_ip_whitelist_entry')]
    public function getUserIpWhitelistEntry(
        string $userId,
        string $subnet,
        int $subnetSize,
    ): array
    {
        return $this->getClient()->get('/users/{userId/ip-whitelist/entry', [
            'subnet' => $subnet,
            'subnet_size' => $subnetSize,
        ]);
    }

}