<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /vfs endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class VfsTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List VFSs.
     * 
     * Retrieve a list of all VFS subscriptions for the account
     * @return array<string, mixed>
     */
    #[McpTool(name: 'listVFS')]
    public function listVFS(): array
    {
        return $this->getClient()->get('/vfs');
    }

    /**
     * Create VFS.
     * 
     * Create a new VFS subscription with the specified configuration
     * 
     * @param  string  $region  Region identifier where to create the VFS
     * @param  string  $label  User-defined label for the VFS subscription
     * @param  array  $storageSize
     * @param  string|null  $diskType  Type of storage disk (defaults to nvme if not specified)
     * @param  array|null  $tags  Optional tags to apply to the VFS subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'createVFS')]
    public function createVFS(
        string $region,
        string $label,
        array $storageSize,
        ?string $diskType = null,
        ?array $tags = null,
    ): array
    {
        return $this->client->post('/vfs', [
            'region' => $region,
            'label' => $label,
            'storage_size' => $storageSize,
            'disk_type' => $diskType,
            'tags' => $tags,
        ]);
    }

    /**
     * List VFS Regions.
     * 
     * Retrieve a list of all regions where VFS can be deployed
     * @return array<string, mixed>
     */
    #[McpTool(name: 'listRegions')]
    public function listRegions(): array
    {
        return $this->getClient()->get('/vfs/regions');
    }

    /**
     * Delete VFS.
     * 
     * Delete a specific VFS subscription by ID
     * 
     * @param  string  $vfsId  ID of the VFS subscription to retrieve
     * @return array<string, mixed>
     */
    #[McpTool(name: 'deleteVFS')]
    public function deleteVFS(
        string $vfsId,
    ): array
    {
        $this->getClient()->delete('/vfs/{vfsId');

        return ['success' => true];
    }

    /**
     * Get VFS.
     * 
     * Retrieve a specific VFS subscription by ID
     * 
     * @param  string  $vfsId  ID of the VFS subscription to retrieve
     * @return array<string, mixed>
     */
    #[McpTool(name: 'getVFS')]
    public function getVFS(
        string $vfsId,
    ): array
    {
        return $this->getClient()->get('/vfs/{vfsId');
    }

    /**
     * Update VFS.
     * 
     * Update a VFS subscription's label or storage size
     * 
     * @param  string|null  $label  New label for the VFS subscription
     * @param  array|null  $storageSize  New storage size (can only increase, not decrease)
     * @return array<string, mixed>
     */
    #[McpTool(name: 'updateVFS')]
    public function updateVFS(
        ?string $label = null,
        ?array $storageSize = null,
    ): array
    {
        return $this->client->put('/vfs/{vfs_id}', [
            'label' => $label,
            'storage_size' => $storageSize,
        ]);
    }

    /**
     * List VFS Attachments.
     * 
     * Retrieve a list of all attachments for a specific VFS subscription
     * 
     * @param  string  $vfsId  ID of the VFS subscription
     * @return array<string, mixed>
     */
    #[McpTool(name: 'listVFSAttachments')]
    public function listVFSAttachments(
        string $vfsId,
    ): array
    {
        return $this->getClient()->get('/vfs/{vfsId/attachments');
    }

    /**
     * Delete VFS Attachment.
     * 
     * Detach a VPS instance from a VFS subscription
     * 
     * @param  string  $vfsId  ID of the VFS subscription
     * @param  string  $vpsId  ID of the VPS subscription to attach
     * @return array<string, mixed>
     */
    #[McpTool(name: 'deleteVFSAttachment')]
    public function deleteVFSAttachment(
        string $vfsId,
        string $vpsId,
    ): array
    {
        $this->getClient()->delete('/vfs/{vfsId/attachments/{vpsId');

        return ['success' => true];
    }

    /**
     * Get VFS Attachment.
     * 
     * Retrieve details about a specific VFS-VPS attachment
     * 
     * @param  string  $vfsId  ID of the VFS subscription
     * @param  string  $vpsId  ID of the VPS subscription to attach
     * @return array<string, mixed>
     */
    #[McpTool(name: 'getVFSAttachment')]
    public function getVFSAttachment(
        string $vfsId,
        string $vpsId,
    ): array
    {
        return $this->getClient()->get('/vfs/{vfsId/attachments/{vpsId');
    }

    /**
     * Attach VPS Instance to VFS.
     * 
     * Attach a VPS instance to a VFS subscription
     * 
     * @param  string  $vfsId  ID of the VFS subscription
     * @param  string  $vpsId  ID of the VPS subscription to attach
     * @return array<string, mixed>
     */
    #[McpTool(name: 'createVFSAttachment')]
    public function createVFSAttachment(
        string $vfsId,
        string $vpsId,
    ): array
    {
        return $this->client->put('/vfs/{vfsId/attachments/{vpsId');
    }

}