<?php

declare(strict_types=1);

namespace Vultr\Mcp\Tools;

use Mcp\Capability\Attribute\McpTool;
use Mcp\Exception\ToolCallException;
use Vultr\Mcp\Utils\VultrClient;
use Vultr\Mcp\Utils\VultrClientFactory;

/**
 * MCP tools for Vultr /vpcs endpoints.
 *
 * AUTO-GENERATED by {@see \Vultr\Mcp\Generator\OpenApiGenerator}.
 * Re-run `php bin/generate.php` to regenerate from the latest OpenAPI spec.
 *
 * Do not edit this file manually — changes will be overwritten.
 */
final class VpcsTools
{
    /**
     * @param VultrClientFactory $clientFactory Factory for per-request VultrClient instances.
     */
    public function __construct(
        private readonly VultrClientFactory $clientFactory,
    ) {}

    /**
     * Resolve the VultrClient for the current request.
     */
    private function getClient(): VultrClient
    {
        return $this->clientFactory->create();
    }

    /**
     * List VPCs.
     * 
     * Get a list of all VPCs in your account.
     * 
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_vpcs')]
    public function listVpcs(
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/vpcs', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create a VPC.
     * 
     * Create a new VPC in a region. VPCs should use RFC1918 private address space:
     * 
     *     10.0.0.0    - 10.255.255.255  (10/8 prefix)
     *     172.16.0.0  - 172.31.255.255  (172.16/12 prefix)
     *     192.168.0.0 - 192.168.255.255 (192.168/16 prefix)
     * 
     * @param  string  $region  Create the VPC in this Region id.
     * @param  string|null  $description  A description of the VPC.
     * @param  string|null  $v4Subnet  The IPv4 VPC address. For example: 10.99.0.0<br><span style="color: red">If v4_subnet_mask is specified then v4_subnet is a required field.</span>
     * @param  int|null  $v4SubnetMask  The number of bits for the netmask in CIDR notation. Example: 24<br><span style="color: red">If v4_subnet is specified then v4_subnet_mask is a required field.</span>
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_vpc')]
    public function createVpc(
        string $region,
        ?string $description = null,
        ?string $v4Subnet = null,
        ?int $v4SubnetMask = null,
    ): array
    {
        return $this->client->post('/vpcs', [
            'region' => $region,
            'description' => $description,
            'v4_subnet' => $v4Subnet,
            'v4_subnet_mask' => $v4SubnetMask,
        ]);
    }

    /**
     * Delete a VPC.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_vpc')]
    public function deleteVpc(
        string $vpcId,
    ): array
    {
        $this->getClient()->delete('/vpcs/{vpcId');

        return ['success' => true];
    }

    /**
     * Get a VPC.
     * 
     * Get information about a VPC.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_vpc')]
    public function getVpc(
        string $vpcId,
    ): array
    {
        return $this->getClient()->get('/vpcs/{vpcId');
    }

    /**
     * Update a VPC.
     * 
     * Update information for a VPC.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $description  The VPC description.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_vpc')]
    public function updateVpc(
        string $vpcId,
        string $description,
    ): array
    {
        return $this->client->put('/vpcs/{vpcId', [
            'description' => $description,
        ]);
    }

    /**
     * List VPC Attachments.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_vpc_attachments')]
    public function listVpcAttachments(
        string $vpcId,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/vpcs/{vpcId/attachments', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * List NAT Gateways.
     * 
     * List all NAT Gateways for this VPC Network.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_nat_gateways')]
    public function listNatGateways(
        string $vpcId,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/vpcs/{vpcId/nat-gateway', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create NAT Gateway.
     * 
     * Create a new NAT Gateway associated with this VPC Network. Supply optional attributes as desired.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string|null  $label  The user-supplied label for this NAT Gateway.
     * @param  string|null  $tag  The user-supplied tag for this NAT Gateway.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_nat_gateway')]
    public function createNatGateway(
        string $vpcId,
        ?string $label = null,
        ?string $tag = null,
    ): array
    {
        return $this->client->post('/vpcs/{vpcId/nat-gateway', [
            'label' => $label,
            'tag' => $tag,
        ]);
    }

    /**
     * Delete NAT Gateway.
     * 
     * Delete a NAT Gateway.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_nat_gateway')]
    public function deleteNatGateway(
        string $vpcId,
        string $natGatewayId,
    ): array
    {
        $this->getClient()->delete('/vpcs/{vpcId/nat-gateway/{natGatewayId');

        return ['success' => true];
    }

    /**
     * Get NAT Gateway.
     * 
     * Get information about a NAT Gateway.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_nat_gateway')]
    public function getNatGateway(
        string $vpcId,
        string $natGatewayId,
    ): array
    {
        return $this->getClient()->get('/vpcs/{vpcId/nat-gateway/{natGatewayId');
    }

    /**
     * Update NAT Gateway.
     * 
     * Update information for a NAT Gateway. All attributes are optional. If not set, the attributes will
     * retain their original values.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  string|null  $label  The user-supplied label for this NAT Gateway.
     * @param  string|null  $tag  The user-supplied tag for this NAT Gateway.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_nat_gateway')]
    public function updateNatGateway(
        string $vpcId,
        string $natGatewayId,
        ?string $label = null,
        ?string $tag = null,
    ): array
    {
        return $this->client->put('/vpcs/{vpcId/nat-gateway/{natGatewayId', [
            'label' => $label,
            'tag' => $tag,
        ]);
    }

    /**
     * List NAT Gateway Firewall Rules.
     * 
     * List all Firewall Rules for this NAT Gateway.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_nat_gateway_firewall_rules')]
    public function listNatGatewayFirewallRules(
        string $vpcId,
        string $natGatewayId,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/firewall-rules', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create NAT Gateway Firewall Rule.
     * 
     * Create a new Firewall Rule associated with this NAT Gateway. Supply optional attributes as desired.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  string|null  $protocol  The protocol for this firewall rule

 tcp
 udp
     * @param  string|null  $port  The port or port range for this firewall rule.
     * @param  string|null  $subnet  The IP address representing a subnet for this firewall rule.
     * @param  string|null  $subnetSize  The number of bits for the netmask in CIDR notation. Example: 24
     * @param  string|null  $notes  The user-supplied notes for this firewall rule.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_nat_gateway_firewall_rule')]
    public function createNatGatewayFirewallRule(
        string $vpcId,
        string $natGatewayId,
        ?string $protocol = null,
        ?string $port = null,
        ?string $subnet = null,
        ?string $subnetSize = null,
        ?string $notes = null,
    ): array
    {
        return $this->client->post('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/firewall-rules', [
            'protocol' => $protocol,
            'port' => $port,
            'subnet' => $subnet,
            'subnet_size' => $subnetSize,
            'notes' => $notes,
        ]);
    }

    /**
     * Delete NAT Gateway Firewall Rule.
     * 
     * Delete a NAT Gateway Firewall Rule.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  string  $firewallRuleId  The Firewall Rule ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_nat_gateway_firewall_rule')]
    public function deleteNatGatewayFirewallRule(
        string $vpcId,
        string $natGatewayId,
        string $firewallRuleId,
    ): array
    {
        $this->getClient()->delete('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/firewall-rules/{firewallRuleId');

        return ['success' => true];
    }

    /**
     * Get NAT Gateway Firewall Rule.
     * 
     * Get information about a NAT Gateway Firewall Rule.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  string  $firewallRuleId  The Firewall Rule ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_nat_gateway_firewall_rule')]
    public function getNatGatewayFirewallRule(
        string $vpcId,
        string $natGatewayId,
        string $firewallRuleId,
    ): array
    {
        return $this->getClient()->get('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/firewall-rules/{firewallRuleId');
    }

    /**
     * Update NAT Gateway Firewall Rule.
     * 
     * Update information for a NAT Gateway Firewall Rule. All attributes are optional. If not set, the
     * attributes will retain their original values.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  string  $firewallRuleId  The Firewall Rule ID.
     * @param  string|null  $notes  The user-supplied notes for this firewall rule.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_nat_gateway_firewall_rule')]
    public function updateNatGatewayFirewallRule(
        string $vpcId,
        string $natGatewayId,
        string $firewallRuleId,
        ?string $notes = null,
    ): array
    {
        return $this->client->put('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/firewall-rules/{firewallRuleId', [
            'notes' => $notes,
        ]);
    }

    /**
     * List NAT Gateway Port Forwarding Rules.
     * 
     * List all Port Forwarding Rules for this NAT Gateway.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  int|null  $perPage  Number of items requested per page. Default is 100 and Max is 500.
     * @param  string|null  $cursor  Cursor for paging. See Meta and Pagination.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'list_nat_gateway_port_forwarding_rules')]
    public function listNatGatewayPortForwardingRules(
        string $vpcId,
        string $natGatewayId,
        ?int $perPage = null,
        ?string $cursor = null,
    ): array
    {
        return $this->getClient()->get('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/port-forwarding-rules', [
            'per_page' => $perPage,
            'cursor' => $cursor,
        ]);
    }

    /**
     * Create NAT Gateway Port Forwarding Rule.
     * 
     * Create a new Port Forwarding Rule associated with this NAT Gateway. Supply optional attributes as
     * desired.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  string|null  $name  The name of this port forwarding rule.
     * @param  string|null  $protocol  The protocol for this port forwarding rule

 tcp
 udp
* both
     * @param  int|null  $externalPort  The external port associated with this port forwarding rule.
     * @param  string|null  $internalIp  The internal IP address associated with this port forwarding rule.
     * @param  int|null  $internalPort  The internal port associated with this port forwarding rule.
     * @param  bool|null  $enabled  Whether this port forwarding rule is enabled.
     * @param  string|null  $description  The user-supplied description for this port forwarding rule.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'create_nat_gateway_port_forwarding_rule')]
    public function createNatGatewayPortForwardingRule(
        string $vpcId,
        string $natGatewayId,
        ?string $name = null,
        ?string $protocol = null,
        ?int $externalPort = null,
        ?string $internalIp = null,
        ?int $internalPort = null,
        ?bool $enabled = null,
        ?string $description = null,
    ): array
    {
        return $this->client->post('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/port-forwarding-rules', [
            'name' => $name,
            'protocol' => $protocol,
            'external_port' => $externalPort,
            'internal_ip' => $internalIp,
            'internal_port' => $internalPort,
            'enabled' => $enabled,
            'description' => $description,
        ]);
    }

    /**
     * Delete NAT Gateway Port Forwarding Rule.
     * 
     * Delete a NAT Gateway port-forwarding Rule.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  string  $portForwardingRuleId  The Port Forwarding Rule ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'delete_nat_gateway_port_forwarding_rule')]
    public function deleteNatGatewayPortForwardingRule(
        string $vpcId,
        string $natGatewayId,
        string $portForwardingRuleId,
    ): array
    {
        $this->getClient()->delete('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/port-forwarding-rules/{portForwardingRuleId');

        return ['success' => true];
    }

    /**
     * Get NAT Gateway Port Forwarding Rule.
     * 
     * Get information about a NAT Gateway Port Forwarding Rule.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  string  $portForwardingRuleId  The Port Forwarding Rule ID.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'get_nat_gateway_port_forwarding_rule')]
    public function getNatGatewayPortForwardingRule(
        string $vpcId,
        string $natGatewayId,
        string $portForwardingRuleId,
    ): array
    {
        return $this->getClient()->get('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/port-forwarding-rules/{portForwardingRuleId');
    }

    /**
     * Update NAT Gateway Port Forwarding Rule.
     * 
     * Update information for a NAT Gateway Port Forwarding Rule. All attributes are optional. If not set,
     * the attributes will retain their original values.
     * 
     * @param  string  $vpcId  The VPC ID.
     * @param  string  $natGatewayId  The NAT Gateway ID.
     * @param  string  $portForwardingRuleId  The Port Forwarding Rule ID.
     * @param  string|null  $name  The name of this port forwarding rule.
     * @param  string|null  $protocol  The protocol for this port forwarding rule

 tcp
 udp
* both
     * @param  int|null  $externalPort  The external port associated with this port forwarding rule.
     * @param  string|null  $internalIp  The internal IP address associated with this port forwarding rule.
     * @param  int|null  $internalPort  The internal port associated with this port forwarding rule.
     * @param  bool|null  $enabled  Whether this port forwarding rule is enabled.
     * @param  string|null  $description  The user-supplied description for this port forwarding rule.
     * @return array<string, mixed>
     */
    #[McpTool(name: 'update_nat_gateway_port_forwarding_rule')]
    public function updateNatGatewayPortForwardingRule(
        string $vpcId,
        string $natGatewayId,
        string $portForwardingRuleId,
        ?string $name = null,
        ?string $protocol = null,
        ?int $externalPort = null,
        ?string $internalIp = null,
        ?int $internalPort = null,
        ?bool $enabled = null,
        ?string $description = null,
    ): array
    {
        return $this->client->put('/vpcs/{vpcId/nat-gateway/{natGatewayId/global/port-forwarding-rules/{portForwardingRuleId', [
            'name' => $name,
            'protocol' => $protocol,
            'external_port' => $externalPort,
            'internal_ip' => $internalIp,
            'internal_port' => $internalPort,
            'enabled' => $enabled,
            'description' => $description,
        ]);
    }

}